// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/shared"
	"net/http"
)

// Reason why the contract is not assignable. If the reason is "MULTIPLE", the contract is not assignable because multiple contracts were found and the business logic does not allow it.
type Reason string

const (
	ReasonDraft    Reason = "DRAFT"
	ReasonMultiple Reason = "MULTIPLE"
)

func (e Reason) ToPointer() *Reason {
	return &e
}
func (e *Reason) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "DRAFT":
		fallthrough
	case "MULTIPLE":
		*e = Reason(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Reason: %v", v)
	}
}

// AddContractByIdentifiersECPResponseBody - Contract was found but is not assignable in its current state.
type AddContractByIdentifiersECPResponseBody struct {
	// Error message
	Message *string `json:"message,omitempty"`
	// Reason why the contract is not assignable. If the reason is "MULTIPLE", the contract is not assignable because multiple contracts were found and the business logic does not allow it.
	Reason Reason `json:"reason"`
}

func (a *AddContractByIdentifiersECPResponseBody) GetMessage() *string {
	if a == nil {
		return nil
	}
	return a.Message
}

func (a *AddContractByIdentifiersECPResponseBody) GetReason() Reason {
	if a == nil {
		return Reason("")
	}
	return a.Reason
}

// AddContractByIdentifiersResponseBody - Contract(s) assigned successfully.
type AddContractByIdentifiersResponseBody struct {
	Data []shared.EntityItem `json:"data,omitempty"`
	Hits float64             `json:"hits"`
}

func (a *AddContractByIdentifiersResponseBody) GetData() []shared.EntityItem {
	if a == nil {
		return nil
	}
	return a.Data
}

func (a *AddContractByIdentifiersResponseBody) GetHits() float64 {
	if a == nil {
		return 0.0
	}
	return a.Hits
}

type AddContractByIdentifiersResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The request could not be validated
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Contract(s) assigned successfully.
	Object *AddContractByIdentifiersResponseBody
	// Contract was found but is not assignable in its current state.
	Object1 *AddContractByIdentifiersECPResponseBody
}

func (a *AddContractByIdentifiersResponse) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *AddContractByIdentifiersResponse) GetErrorResp() *shared.ErrorResp {
	if a == nil {
		return nil
	}
	return a.ErrorResp
}

func (a *AddContractByIdentifiersResponse) GetStatusCode() int {
	if a == nil {
		return 0
	}
	return a.StatusCode
}

func (a *AddContractByIdentifiersResponse) GetRawResponse() *http.Response {
	if a == nil {
		return nil
	}
	return a.RawResponse
}

func (a *AddContractByIdentifiersResponse) GetObject() *AddContractByIdentifiersResponseBody {
	if a == nil {
		return nil
	}
	return a.Object
}

func (a *AddContractByIdentifiersResponse) GetObject1() *AddContractByIdentifiersECPResponseBody {
	if a == nil {
		return nil
	}
	return a.Object1
}
