// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/shared"
	"net/http"
)

type CanTriggerPortalFlowRequest struct {
	// Request of trigger portal flow
	TriggerPortalFlow shared.TriggerPortalFlow `request:"mediaType=application/json"`
	// Origin of the portal
	Origin shared.Origin `queryParam:"style=form,explode=true,name=origin"`
}

func (o *CanTriggerPortalFlowRequest) GetTriggerPortalFlow() shared.TriggerPortalFlow {
	if o == nil {
		return shared.TriggerPortalFlow{}
	}
	return o.TriggerPortalFlow
}

func (o *CanTriggerPortalFlowRequest) GetOrigin() shared.Origin {
	if o == nil {
		return shared.Origin("")
	}
	return o.Origin
}

// CanTriggerPortalFlowResponseBody - Can Trigger Portal Flow
type CanTriggerPortalFlowResponseBody struct {
	// Whether the flow can be triggered
	CanTrigger *bool `json:"can_trigger,omitempty"`
}

func (o *CanTriggerPortalFlowResponseBody) GetCanTrigger() *bool {
	if o == nil {
		return nil
	}
	return o.CanTrigger
}

type CanTriggerPortalFlowResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Can Trigger Portal Flow
	Object *CanTriggerPortalFlowResponseBody
}

func (o *CanTriggerPortalFlowResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CanTriggerPortalFlowResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CanTriggerPortalFlowResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CanTriggerPortalFlowResponse) GetObject() *CanTriggerPortalFlowResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
