// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/shared"
	"net/http"
)

type CheckContactExistsV3Request struct {
	// Request payload
	ContactExistsRequest shared.ContactExistsRequest `request:"mediaType=application/json"`
	// PortalId of the portal
	PortalID string `queryParam:"style=form,explode=true,name=portal_id"`
}

func (c *CheckContactExistsV3Request) GetContactExistsRequest() shared.ContactExistsRequest {
	if c == nil {
		return shared.ContactExistsRequest{}
	}
	return c.ContactExistsRequest
}

func (c *CheckContactExistsV3Request) GetPortalID() string {
	if c == nil {
		return ""
	}
	return c.PortalID
}

// CheckContactExistsV3ResponseBody - Return result true|false if the contact with given identifiers exists.
type CheckContactExistsV3ResponseBody struct {
	// Entity ID
	ContactID *string `json:"contactId,omitempty"`
	// Whether the contact exists with the given identifier values
	Exists *bool `json:"exists,omitempty"`
}

func (c *CheckContactExistsV3ResponseBody) GetContactID() *string {
	if c == nil {
		return nil
	}
	return c.ContactID
}

func (c *CheckContactExistsV3ResponseBody) GetExists() *bool {
	if c == nil {
		return nil
	}
	return c.Exists
}

type CheckContactExistsV3Response struct {
	// HTTP response content type for this operation
	ContentType string
	// The request could not be validated
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Return result true|false if the contact with given identifiers exists.
	Object *CheckContactExistsV3ResponseBody
}

func (c *CheckContactExistsV3Response) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CheckContactExistsV3Response) GetErrorResp() *shared.ErrorResp {
	if c == nil {
		return nil
	}
	return c.ErrorResp
}

func (c *CheckContactExistsV3Response) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CheckContactExistsV3Response) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CheckContactExistsV3Response) GetObject() *CheckContactExistsV3ResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
