// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/shared"
	"net/http"
)

// Type - One of supported activity types
type Type string

const (
	TypePortalUserResetPassword Type = "PortalUserResetPassword"
)

func (e Type) ToPointer() *Type {
	return &e
}
func (e *Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PortalUserResetPassword":
		*e = Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Type: %v", v)
	}
}

type CreateCustomEntityActivityRequestBody struct {
	// One of supported activity types
	Type Type `json:"type"`
}

func (c *CreateCustomEntityActivityRequestBody) GetType() Type {
	if c == nil {
		return Type("")
	}
	return c.Type
}

type CreateCustomEntityActivityRequest struct {
	RequestBody *CreateCustomEntityActivityRequestBody `request:"mediaType=application/json"`
	// Comma-separated list of entities which the activity primarily concerns. Deprecated - ignored as the list of entities is automatically determined now.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Entities []string `queryParam:"style=form,explode=false,name=entities"`
}

func (c *CreateCustomEntityActivityRequest) GetRequestBody() *CreateCustomEntityActivityRequestBody {
	if c == nil {
		return nil
	}
	return c.RequestBody
}

func (c *CreateCustomEntityActivityRequest) GetEntities() []string {
	if c == nil {
		return nil
	}
	return c.Entities
}

type CreateCustomEntityActivityResponse struct {
	// Success
	ActivityItem *shared.ActivityItem
	// HTTP response content type for this operation
	ContentType string
	// Could not authenticate the user
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *CreateCustomEntityActivityResponse) GetActivityItem() *shared.ActivityItem {
	if c == nil {
		return nil
	}
	return c.ActivityItem
}

func (c *CreateCustomEntityActivityResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateCustomEntityActivityResponse) GetErrorResp() *shared.ErrorResp {
	if c == nil {
		return nil
	}
	return c.ErrorResp
}

func (c *CreateCustomEntityActivityResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateCustomEntityActivityResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}
