// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/shared"
	"net/http"
)

type CreateUserRequest struct {
	// Portal user payload
	CreateUserRequest shared.CreateUserRequest `request:"mediaType=application/json"`
	// Origin of the portal
	Origin string `queryParam:"style=form,explode=true,name=origin"`
}

func (c *CreateUserRequest) GetCreateUserRequest() shared.CreateUserRequest {
	if c == nil {
		return shared.CreateUserRequest{}
	}
	return c.CreateUserRequest
}

func (c *CreateUserRequest) GetOrigin() string {
	if c == nil {
		return ""
	}
	return c.Origin
}

type CreateUserMessage string

const (
	CreateUserMessageUserCreatedSuccessfully CreateUserMessage = "User created successfully"
)

func (e CreateUserMessage) ToPointer() *CreateUserMessage {
	return &e
}
func (e *CreateUserMessage) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "User created successfully":
		*e = CreateUserMessage(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateUserMessage: %v", v)
	}
}

// CreateUserResponseBody - User created successfully.
type CreateUserResponseBody struct {
	Message CreateUserMessage `json:"message"`
}

func (c *CreateUserResponseBody) GetMessage() CreateUserMessage {
	if c == nil {
		return CreateUserMessage("")
	}
	return c.Message
}

type CreateUserResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The request could not be validated
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// User created successfully.
	Object *CreateUserResponseBody
}

func (c *CreateUserResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateUserResponse) GetErrorResp() *shared.ErrorResp {
	if c == nil {
		return nil
	}
	return c.ErrorResp
}

func (c *CreateUserResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateUserResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateUserResponse) GetObject() *CreateUserResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
