// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/shared"
	"net/http"
)

type DeletePortalUserMessage string

const (
	DeletePortalUserMessageUserSuccesfullyDeleted DeletePortalUserMessage = "User Succesfully Deleted"
)

func (e DeletePortalUserMessage) ToPointer() *DeletePortalUserMessage {
	return &e
}
func (e *DeletePortalUserMessage) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "User Succesfully Deleted":
		*e = DeletePortalUserMessage(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DeletePortalUserMessage: %v", v)
	}
}

// DeletePortalUserResponseBody - Portal user deleted successfully.
type DeletePortalUserResponseBody struct {
	// Entity ID
	Data    *string                  `json:"data,omitempty"`
	Message *DeletePortalUserMessage `json:"message,omitempty"`
}

func (d *DeletePortalUserResponseBody) GetData() *string {
	if d == nil {
		return nil
	}
	return d.Data
}

func (d *DeletePortalUserResponseBody) GetMessage() *DeletePortalUserMessage {
	if d == nil {
		return nil
	}
	return d.Message
}

type DeletePortalUserResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Could not authenticate the user
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Portal user deleted successfully.
	Object *DeletePortalUserResponseBody
}

func (d *DeletePortalUserResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeletePortalUserResponse) GetErrorResp() *shared.ErrorResp {
	if d == nil {
		return nil
	}
	return d.ErrorResp
}

func (d *DeletePortalUserResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeletePortalUserResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeletePortalUserResponse) GetObject() *DeletePortalUserResponseBody {
	if d == nil {
		return nil
	}
	return d.Object
}
