// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/shared"
	"net/http"
)

type GetAllowedMeterReadingRangeRequest struct {
	// Additional entities to include in the context for variable interpolation in the hook.
	ContextEntities []shared.ContextEntity `queryParam:"style=form,explode=true,name=context_entities"`
	// The ID of the meter.
	MeterID string `pathParam:"style=simple,explode=false,name=meter_id"`
	// Origin of the portal
	Origin *string `queryParam:"style=form,explode=true,name=origin"`
	// If not provided, the system will default to now.
	Timestamp *string `queryParam:"style=form,explode=true,name=timestamp"`
}

func (g *GetAllowedMeterReadingRangeRequest) GetContextEntities() []shared.ContextEntity {
	if g == nil {
		return nil
	}
	return g.ContextEntities
}

func (g *GetAllowedMeterReadingRangeRequest) GetMeterID() string {
	if g == nil {
		return ""
	}
	return g.MeterID
}

func (g *GetAllowedMeterReadingRangeRequest) GetOrigin() *string {
	if g == nil {
		return nil
	}
	return g.Origin
}

func (g *GetAllowedMeterReadingRangeRequest) GetTimestamp() *string {
	if g == nil {
		return nil
	}
	return g.Timestamp
}

type GetAllowedMeterReadingRangeData struct {
	// Maximum allowed reading value
	MaxValue *float64 `json:"max_value,omitempty"`
	// The ID of the counter
	MeterCounterID *string `json:"meter_counter_id,omitempty"`
	// Minimum allowed reading value
	MinValue *float64 `json:"min_value,omitempty"`
}

func (g *GetAllowedMeterReadingRangeData) GetMaxValue() *float64 {
	if g == nil {
		return nil
	}
	return g.MaxValue
}

func (g *GetAllowedMeterReadingRangeData) GetMeterCounterID() *string {
	if g == nil {
		return nil
	}
	return g.MeterCounterID
}

func (g *GetAllowedMeterReadingRangeData) GetMinValue() *float64 {
	if g == nil {
		return nil
	}
	return g.MinValue
}

// GetAllowedMeterReadingRangeResponseBody - Allowed reading ranges for the meter.
type GetAllowedMeterReadingRangeResponseBody struct {
	Data []GetAllowedMeterReadingRangeData `json:"data,omitempty"`
}

func (g *GetAllowedMeterReadingRangeResponseBody) GetData() []GetAllowedMeterReadingRangeData {
	if g == nil {
		return nil
	}
	return g.Data
}

type GetAllowedMeterReadingRangeResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The request could not be validated
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Allowed reading ranges for the meter.
	Object *GetAllowedMeterReadingRangeResponseBody
}

func (g *GetAllowedMeterReadingRangeResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetAllowedMeterReadingRangeResponse) GetErrorResp() *shared.ErrorResp {
	if g == nil {
		return nil
	}
	return g.ErrorResp
}

func (g *GetAllowedMeterReadingRangeResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetAllowedMeterReadingRangeResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetAllowedMeterReadingRangeResponse) GetObject() *GetAllowedMeterReadingRangeResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
