// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/shared"
	"net/http"
)

// QueryParamType - Type of the context to retrieve
type QueryParamType string

const (
	QueryParamTypeFile QueryParamType = "file"
)

func (e QueryParamType) ToPointer() *QueryParamType {
	return &e
}
func (e *QueryParamType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "file":
		*e = QueryParamType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for QueryParamType: %v", v)
	}
}

type GetAutomationContextRequest struct {
	// Activity ID
	ActivityID string `queryParam:"style=form,explode=true,name=activity_id"`
	// Type of the context to retrieve
	Type QueryParamType `queryParam:"style=form,explode=true,name=type"`
}

func (g *GetAutomationContextRequest) GetActivityID() string {
	if g == nil {
		return ""
	}
	return g.ActivityID
}

func (g *GetAutomationContextRequest) GetType() QueryParamType {
	if g == nil {
		return QueryParamType("")
	}
	return g.Type
}

type GetAutomationContextResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Could not authenticate the user
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Retrieved the automation context successfully.
	Object map[string]map[string]any
}

func (g *GetAutomationContextResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetAutomationContextResponse) GetErrorResp() *shared.ErrorResp {
	if g == nil {
		return nil
	}
	return g.ErrorResp
}

func (g *GetAutomationContextResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetAutomationContextResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetAutomationContextResponse) GetObject() map[string]map[string]any {
	if g == nil {
		return nil
	}
	return g.Object
}
