// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/shared"
	"net/http"
)

// GetAllPortalConfigsResponseBody - All portal configs retrieved successfully.
type GetAllPortalConfigsResponseBody struct {
	Data []shared.PortalConfig `json:"data,omitempty"`
}

func (g *GetAllPortalConfigsResponseBody) GetData() []shared.PortalConfig {
	if g == nil {
		return nil
	}
	return g.Data
}

type GetAllPortalConfigsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Could not authenticate the user
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// All portal configs retrieved successfully.
	Object *GetAllPortalConfigsResponseBody
}

func (g *GetAllPortalConfigsResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetAllPortalConfigsResponse) GetErrorResp() *shared.ErrorResp {
	if g == nil {
		return nil
	}
	return g.ErrorResp
}

func (g *GetAllPortalConfigsResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetAllPortalConfigsResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetAllPortalConfigsResponse) GetObject() *GetAllPortalConfigsResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
