// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/shared"
	"net/http"
	"time"
)

type GetAllContractsRequest struct {
	From *float64 `default:"0" queryParam:"style=form,explode=true,name=from"`
	Size *float64 `default:"100" queryParam:"style=form,explode=true,name=size"`
}

func (g GetAllContractsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAllContractsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAllContractsRequest) GetFrom() *float64 {
	if g == nil {
		return nil
	}
	return g.From
}

func (g *GetAllContractsRequest) GetSize() *float64 {
	if g == nil {
		return nil
	}
	return g.Size
}

// BillingPeriod - The billing period associated with the contract.
type BillingPeriod string

const (
	BillingPeriodWeekly       BillingPeriod = "weekly"
	BillingPeriodMonthly      BillingPeriod = "monthly"
	BillingPeriodEveryQuarter BillingPeriod = "every_quarter"
	BillingPeriodEvery6Months BillingPeriod = "every_6_months"
	BillingPeriodYearly       BillingPeriod = "yearly"
)

func (e BillingPeriod) ToPointer() *BillingPeriod {
	return &e
}
func (e *BillingPeriod) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "weekly":
		fallthrough
	case "monthly":
		fallthrough
	case "every_quarter":
		fallthrough
	case "every_6_months":
		fallthrough
	case "yearly":
		*e = BillingPeriod(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BillingPeriod: %v", v)
	}
}

// Branch - The branch associated with the contract.
type Branch string

const (
	BranchPower           Branch = "power"
	BranchGas             Branch = "gas"
	BranchWater           Branch = "water"
	BranchWasteWater      Branch = "waste_water"
	BranchDistrictHeating Branch = "district_heating"
)

func (e Branch) ToPointer() *Branch {
	return &e
}
func (e *Branch) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "power":
		fallthrough
	case "gas":
		fallthrough
	case "water":
		fallthrough
	case "waste_water":
		fallthrough
	case "district_heating":
		*e = Branch(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Branch: %v", v)
	}
}

// NoticeTimeUnit - The unit of time for the notice period.
type NoticeTimeUnit string

const (
	NoticeTimeUnitWeeks  NoticeTimeUnit = "weeks"
	NoticeTimeUnitMonths NoticeTimeUnit = "months"
	NoticeTimeUnitYears  NoticeTimeUnit = "years"
)

func (e NoticeTimeUnit) ToPointer() *NoticeTimeUnit {
	return &e
}
func (e *NoticeTimeUnit) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "weeks":
		fallthrough
	case "months":
		fallthrough
	case "years":
		*e = NoticeTimeUnit(v)
		return nil
	default:
		return fmt.Errorf("invalid value for NoticeTimeUnit: %v", v)
	}
}

// RenewalDurationUnit - The unit of time for the renewal period.
type RenewalDurationUnit string

const (
	RenewalDurationUnitWeeks  RenewalDurationUnit = "weeks"
	RenewalDurationUnitMonths RenewalDurationUnit = "months"
	RenewalDurationUnitYears  RenewalDurationUnit = "years"
)

func (e RenewalDurationUnit) ToPointer() *RenewalDurationUnit {
	return &e
}
func (e *RenewalDurationUnit) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "weeks":
		fallthrough
	case "months":
		fallthrough
	case "years":
		*e = RenewalDurationUnit(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RenewalDurationUnit: %v", v)
	}
}

// GetAllContractsStatus - The status of the contract.
type GetAllContractsStatus string

const (
	GetAllContractsStatusDraft             GetAllContractsStatus = "draft"
	GetAllContractsStatusInApprovalProcess GetAllContractsStatus = "in_approval_process"
	GetAllContractsStatusApproved          GetAllContractsStatus = "approved"
	GetAllContractsStatusActive            GetAllContractsStatus = "active"
	GetAllContractsStatusDeactivated       GetAllContractsStatus = "deactivated"
	GetAllContractsStatusRevoked           GetAllContractsStatus = "revoked"
	GetAllContractsStatusTerminated        GetAllContractsStatus = "terminated"
	GetAllContractsStatusExpired           GetAllContractsStatus = "expired"
)

func (e GetAllContractsStatus) ToPointer() *GetAllContractsStatus {
	return &e
}
func (e *GetAllContractsStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "draft":
		fallthrough
	case "in_approval_process":
		fallthrough
	case "approved":
		fallthrough
	case "active":
		fallthrough
	case "deactivated":
		fallthrough
	case "revoked":
		fallthrough
	case "terminated":
		fallthrough
	case "expired":
		*e = GetAllContractsStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetAllContractsStatus: %v", v)
	}
}

// GetAllContractsData - The contract entity
type GetAllContractsData struct {
	AdditionalProperties any `additionalProperties:"true" json:"-"`
	// Creation timestamp of the entity
	CreatedAt time.Time `json:"_created_at"`
	// Entity ID
	ID string `json:"_id"`
	// Organization ID the entity belongs to
	Org string `json:"_org"`
	// Array of entity tags
	Tags []string `json:"_tags,omitempty"`
	// Title of the entity
	Title string `json:"_title"`
	// Last update timestamp of the entity
	UpdatedAt time.Time `json:"_updated_at"`
	// The account number associated with the contract.
	AccountNumber *string `json:"account_number,omitempty"`
	// Any additional addresses associated with the contract.
	AdditionalAddresses *string `json:"additional_addresses,omitempty"`
	// Current balance of the contract in cents. (precision 2)
	Balance *int64 `json:"balance,omitempty"`
	// Currency code in ISO 4217 format
	BalanceCurrency *string `json:"balance_currency,omitempty"`
	// The billing address associated with the contract.
	BillingAddress *string `json:"billing_address,omitempty"`
	// Defines the day of the month in which the installments are due.
	BillingDueDay *int64 `json:"billing_due_day,omitempty"`
	// The duration of the billing period.
	BillingDurationAmount *float64 `json:"billing_duration_amount,omitempty"`
	// The billing period associated with the contract.
	BillingPeriod *BillingPeriod `default:"weekly" json:"billing_period"`
	// The branch associated with the contract.
	Branch *Branch `json:"branch,omitempty"`
	// The name of the contract.
	ContractName *string `json:"contract_name,omitempty"`
	// The unique identifier of the contract.
	ContractNumber *string `json:"contract_number,omitempty"`
	// The delivery address associated with the contract.
	DeliveryAddress *string `json:"delivery_address,omitempty"`
	// A brief description of the contract.
	Description *string `json:"description,omitempty"`
	// Set amount for installments in cents. (precision 2)
	InstallmentAmount *int64                 `json:"installment_amount,omitempty"`
	JourneyActions    *shared.JourneyActions `json:"journey_actions,omitempty"`
	// The amount of notice required for termination of the contract.
	NoticeTimeAmount *float64 `json:"notice_time_amount,omitempty"`
	// The unit of time for the notice period.
	NoticeTimeUnit *NoticeTimeUnit `default:"months" json:"notice_time_unit"`
	// The duration of the renewal period.
	RenewalDurationAmount *float64 `json:"renewal_duration_amount,omitempty"`
	// The unit of time for the renewal period.
	RenewalDurationUnit *RenewalDurationUnit `default:"months" json:"renewal_duration_unit"`
	// The start date of the contract.
	StartDate *string `json:"start_date,omitempty"`
	// The status of the contract.
	Status *GetAllContractsStatus `default:"draft" json:"status"`
	// The date on which the contract was terminated.
	TerminationDate *string `json:"termination_date,omitempty"`
	// The reason for the termination of the contract.
	TerminationReason *string `json:"termination_reason,omitempty"`
}

func (g GetAllContractsData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAllContractsData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAllContractsData) GetAdditionalProperties() any {
	if g == nil {
		return nil
	}
	return g.AdditionalProperties
}

func (g *GetAllContractsData) GetCreatedAt() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.CreatedAt
}

func (g *GetAllContractsData) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetAllContractsData) GetOrg() string {
	if g == nil {
		return ""
	}
	return g.Org
}

func (g *GetAllContractsData) GetTags() []string {
	if g == nil {
		return nil
	}
	return g.Tags
}

func (g *GetAllContractsData) GetTitle() string {
	if g == nil {
		return ""
	}
	return g.Title
}

func (g *GetAllContractsData) GetUpdatedAt() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.UpdatedAt
}

func (g *GetAllContractsData) GetAccountNumber() *string {
	if g == nil {
		return nil
	}
	return g.AccountNumber
}

func (g *GetAllContractsData) GetAdditionalAddresses() *string {
	if g == nil {
		return nil
	}
	return g.AdditionalAddresses
}

func (g *GetAllContractsData) GetBalance() *int64 {
	if g == nil {
		return nil
	}
	return g.Balance
}

func (g *GetAllContractsData) GetBalanceCurrency() *string {
	if g == nil {
		return nil
	}
	return g.BalanceCurrency
}

func (g *GetAllContractsData) GetBillingAddress() *string {
	if g == nil {
		return nil
	}
	return g.BillingAddress
}

func (g *GetAllContractsData) GetBillingDueDay() *int64 {
	if g == nil {
		return nil
	}
	return g.BillingDueDay
}

func (g *GetAllContractsData) GetBillingDurationAmount() *float64 {
	if g == nil {
		return nil
	}
	return g.BillingDurationAmount
}

func (g *GetAllContractsData) GetBillingPeriod() *BillingPeriod {
	if g == nil {
		return nil
	}
	return g.BillingPeriod
}

func (g *GetAllContractsData) GetBranch() *Branch {
	if g == nil {
		return nil
	}
	return g.Branch
}

func (g *GetAllContractsData) GetContractName() *string {
	if g == nil {
		return nil
	}
	return g.ContractName
}

func (g *GetAllContractsData) GetContractNumber() *string {
	if g == nil {
		return nil
	}
	return g.ContractNumber
}

func (g *GetAllContractsData) GetDeliveryAddress() *string {
	if g == nil {
		return nil
	}
	return g.DeliveryAddress
}

func (g *GetAllContractsData) GetDescription() *string {
	if g == nil {
		return nil
	}
	return g.Description
}

func (g *GetAllContractsData) GetInstallmentAmount() *int64 {
	if g == nil {
		return nil
	}
	return g.InstallmentAmount
}

func (g *GetAllContractsData) GetJourneyActions() *shared.JourneyActions {
	if g == nil {
		return nil
	}
	return g.JourneyActions
}

func (g *GetAllContractsData) GetNoticeTimeAmount() *float64 {
	if g == nil {
		return nil
	}
	return g.NoticeTimeAmount
}

func (g *GetAllContractsData) GetNoticeTimeUnit() *NoticeTimeUnit {
	if g == nil {
		return nil
	}
	return g.NoticeTimeUnit
}

func (g *GetAllContractsData) GetRenewalDurationAmount() *float64 {
	if g == nil {
		return nil
	}
	return g.RenewalDurationAmount
}

func (g *GetAllContractsData) GetRenewalDurationUnit() *RenewalDurationUnit {
	if g == nil {
		return nil
	}
	return g.RenewalDurationUnit
}

func (g *GetAllContractsData) GetStartDate() *string {
	if g == nil {
		return nil
	}
	return g.StartDate
}

func (g *GetAllContractsData) GetStatus() *GetAllContractsStatus {
	if g == nil {
		return nil
	}
	return g.Status
}

func (g *GetAllContractsData) GetTerminationDate() *string {
	if g == nil {
		return nil
	}
	return g.TerminationDate
}

func (g *GetAllContractsData) GetTerminationReason() *string {
	if g == nil {
		return nil
	}
	return g.TerminationReason
}

// GetAllContractsResponseBody - Contracts have been retrieved successfully.
type GetAllContractsResponseBody struct {
	Data []GetAllContractsData `json:"data,omitempty"`
}

func (g *GetAllContractsResponseBody) GetData() []GetAllContractsData {
	if g == nil {
		return nil
	}
	return g.Data
}

type GetAllContractsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Could not authenticate the user
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Contracts have been retrieved successfully.
	Object *GetAllContractsResponseBody
}

func (g *GetAllContractsResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetAllContractsResponse) GetErrorResp() *shared.ErrorResp {
	if g == nil {
		return nil
	}
	return g.ErrorResp
}

func (g *GetAllContractsResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetAllContractsResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetAllContractsResponse) GetObject() *GetAllContractsResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
