// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/shared"
	"net/http"
	"time"
)

type GetAllOrdersRequest struct {
	From *float64 `default:"0" queryParam:"style=form,explode=true,name=from"`
	Size *float64 `default:"100" queryParam:"style=form,explode=true,name=size"`
}

func (g GetAllOrdersRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAllOrdersRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAllOrdersRequest) GetFrom() *float64 {
	if g == nil {
		return nil
	}
	return g.From
}

func (g *GetAllOrdersRequest) GetSize() *float64 {
	if g == nil {
		return nil
	}
	return g.Size
}

type GetAllOrdersSchema string

const (
	GetAllOrdersSchemaOrder GetAllOrdersSchema = "order"
)

func (e GetAllOrdersSchema) ToPointer() *GetAllOrdersSchema {
	return &e
}
func (e *GetAllOrdersSchema) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "order":
		*e = GetAllOrdersSchema(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetAllOrdersSchema: %v", v)
	}
}

// GetAllOrdersData - The order entity
type GetAllOrdersData struct {
	AdditionalProperties any `additionalProperties:"true" json:"-"`
	// Creation timestamp of the entity
	CreatedAt time.Time `json:"_created_at"`
	// Entity ID
	ID string `json:"_id"`
	// Organization ID the entity belongs to
	Org    string             `json:"_org"`
	Schema GetAllOrdersSchema `json:"_schema"`
	// Array of entity tags
	Tags []string `json:"_tags,omitempty"`
	// Title of the entity
	Title string `json:"_title"`
	// Last update timestamp of the entity
	UpdatedAt      time.Time              `json:"_updated_at"`
	JourneyActions *shared.JourneyActions `json:"journey_actions,omitempty"`
}

func (g GetAllOrdersData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAllOrdersData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAllOrdersData) GetAdditionalProperties() any {
	if g == nil {
		return nil
	}
	return g.AdditionalProperties
}

func (g *GetAllOrdersData) GetCreatedAt() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.CreatedAt
}

func (g *GetAllOrdersData) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetAllOrdersData) GetOrg() string {
	if g == nil {
		return ""
	}
	return g.Org
}

func (g *GetAllOrdersData) GetSchema() GetAllOrdersSchema {
	if g == nil {
		return GetAllOrdersSchema("")
	}
	return g.Schema
}

func (g *GetAllOrdersData) GetTags() []string {
	if g == nil {
		return nil
	}
	return g.Tags
}

func (g *GetAllOrdersData) GetTitle() string {
	if g == nil {
		return ""
	}
	return g.Title
}

func (g *GetAllOrdersData) GetUpdatedAt() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.UpdatedAt
}

func (g *GetAllOrdersData) GetJourneyActions() *shared.JourneyActions {
	if g == nil {
		return nil
	}
	return g.JourneyActions
}

// GetAllOrdersResponseBody - The orders for the portal user returned successfully.
type GetAllOrdersResponseBody struct {
	Data []GetAllOrdersData `json:"data,omitempty"`
}

func (g *GetAllOrdersResponseBody) GetData() []GetAllOrdersData {
	if g == nil {
		return nil
	}
	return g.Data
}

type GetAllOrdersResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Could not authenticate the user
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The orders for the portal user returned successfully.
	Object *GetAllOrdersResponseBody
}

func (g *GetAllOrdersResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetAllOrdersResponse) GetErrorResp() *shared.ErrorResp {
	if g == nil {
		return nil
	}
	return g.ErrorResp
}

func (g *GetAllOrdersResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetAllOrdersResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetAllOrdersResponse) GetObject() *GetAllOrdersResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
