// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/shared"
	"net/http"
)

type GetExternalLinksV3Request struct {
	// Contact ID of the user
	ContactID *string `queryParam:"style=form,explode=true,name=contactId"`
	// PortalId of the portal
	PortalID *string `queryParam:"style=form,explode=true,name=portal_id"`
}

func (g *GetExternalLinksV3Request) GetContactID() *string {
	if g == nil {
		return nil
	}
	return g.ContactID
}

func (g *GetExternalLinksV3Request) GetPortalID() *string {
	if g == nil {
		return nil
	}
	return g.PortalID
}

type GetExternalLinksV3Response struct {
	// HTTP response content type for this operation
	ContentType string
	// Could not authenticate the user
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Portal config links retrieved successfully.
	Classes []shared.ExternalLink
}

func (g *GetExternalLinksV3Response) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetExternalLinksV3Response) GetErrorResp() *shared.ErrorResp {
	if g == nil {
		return nil
	}
	return g.ErrorResp
}

func (g *GetExternalLinksV3Response) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetExternalLinksV3Response) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetExternalLinksV3Response) GetClasses() []shared.ExternalLink {
	if g == nil {
		return nil
	}
	return g.Classes
}
