// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/shared"
	"net/http"
)

type GetEntityWorkflowsRequest struct {
	ID   string `pathParam:"style=simple,explode=false,name=id"`
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

func (g *GetEntityWorkflowsRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetEntityWorkflowsRequest) GetSlug() string {
	if g == nil {
		return ""
	}
	return g.Slug
}

// GetEntityWorkflowsResponseBody - List of workflows for the entity
type GetEntityWorkflowsResponseBody struct {
	WorkflowExecutions []map[string]any `json:"workflow_executions,omitempty"`
}

func (g *GetEntityWorkflowsResponseBody) GetWorkflowExecutions() []map[string]any {
	if g == nil {
		return nil
	}
	return g.WorkflowExecutions
}

type GetEntityWorkflowsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Could not authenticate the user
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of workflows for the entity
	Object *GetEntityWorkflowsResponseBody
}

func (g *GetEntityWorkflowsResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetEntityWorkflowsResponse) GetErrorResp() *shared.ErrorResp {
	if g == nil {
		return nil
	}
	return g.ErrorResp
}

func (g *GetEntityWorkflowsResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetEntityWorkflowsResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetEntityWorkflowsResponse) GetObject() *GetEntityWorkflowsResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
