// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/shared"
	"net/http"
	"time"
)

type GetEntityActivityFeedRequest struct {
	// Get activities after this timestamp
	After *time.Time `queryParam:"style=form,explode=true,name=after"`
	// get activities before this timestamp
	Before *time.Time `queryParam:"style=form,explode=true,name=before"`
	// start from page
	From *int64 `default:"0" queryParam:"style=form,explode=true,name=from"`
	// Entity id
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Include activities from related entities
	IncludeRelations *bool `default:"false" queryParam:"style=form,explode=true,name=include_relations"`
	// max number of results to return
	Size *int64 `default:"25" queryParam:"style=form,explode=true,name=size"`
	// Entity Type
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
	// Filter by activity type
	Type *string `queryParam:"style=form,explode=true,name=type"`
}

func (g GetEntityActivityFeedRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetEntityActivityFeedRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetEntityActivityFeedRequest) GetAfter() *time.Time {
	if g == nil {
		return nil
	}
	return g.After
}

func (g *GetEntityActivityFeedRequest) GetBefore() *time.Time {
	if g == nil {
		return nil
	}
	return g.Before
}

func (g *GetEntityActivityFeedRequest) GetFrom() *int64 {
	if g == nil {
		return nil
	}
	return g.From
}

func (g *GetEntityActivityFeedRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetEntityActivityFeedRequest) GetIncludeRelations() *bool {
	if g == nil {
		return nil
	}
	return g.IncludeRelations
}

func (g *GetEntityActivityFeedRequest) GetSize() *int64 {
	if g == nil {
		return nil
	}
	return g.Size
}

func (g *GetEntityActivityFeedRequest) GetSlug() string {
	if g == nil {
		return ""
	}
	return g.Slug
}

func (g *GetEntityActivityFeedRequest) GetType() *string {
	if g == nil {
		return nil
	}
	return g.Type
}

// GetEntityActivityFeedResponseBody - Success
type GetEntityActivityFeedResponseBody struct {
	Results []shared.ActivityItem `json:"results,omitempty"`
	Total   *int64                `json:"total,omitempty"`
}

func (g *GetEntityActivityFeedResponseBody) GetResults() []shared.ActivityItem {
	if g == nil {
		return nil
	}
	return g.Results
}

func (g *GetEntityActivityFeedResponseBody) GetTotal() *int64 {
	if g == nil {
		return nil
	}
	return g.Total
}

type GetEntityActivityFeedResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Success
	Object *GetEntityActivityFeedResponseBody
}

func (g *GetEntityActivityFeedResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetEntityActivityFeedResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetEntityActivityFeedResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetEntityActivityFeedResponse) GetObject() *GetEntityActivityFeedResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
