// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/shared"
	"net/http"
)

type GetPortalWidgetsRequest struct {
	// Contract context for widgets
	ContractID *string `queryParam:"style=form,explode=true,name=contract_id"`
	// Origin of the portal
	Origin *string `queryParam:"style=form,explode=true,name=origin"`
}

func (g *GetPortalWidgetsRequest) GetContractID() *string {
	if g == nil {
		return nil
	}
	return g.ContractID
}

func (g *GetPortalWidgetsRequest) GetOrigin() *string {
	if g == nil {
		return nil
	}
	return g.Origin
}

type GetPortalWidgetsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Could not authenticate the user
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Retrieved the portal widgets successfully.
	UpsertPortalWidget *shared.UpsertPortalWidget
}

func (g *GetPortalWidgetsResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetPortalWidgetsResponse) GetErrorResp() *shared.ErrorResp {
	if g == nil {
		return nil
	}
	return g.ErrorResp
}

func (g *GetPortalWidgetsResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetPortalWidgetsResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetPortalWidgetsResponse) GetUpsertPortalWidget() *shared.UpsertPortalWidget {
	if g == nil {
		return nil
	}
	return g.UpsertPortalWidget
}
