// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/shared"
	"net/http"
)

// GetPortalUserResponseBody - Portal user returned successfully.
type GetPortalUserResponseBody struct {
	// The portal user entity
	Data *shared.PortalUser `json:"data,omitempty"`
}

func (g *GetPortalUserResponseBody) GetData() *shared.PortalUser {
	if g == nil {
		return nil
	}
	return g.Data
}

type GetPortalUserResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Could not authenticate the user
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Portal user returned successfully.
	Object *GetPortalUserResponseBody
}

func (g *GetPortalUserResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetPortalUserResponse) GetErrorResp() *shared.ErrorResp {
	if g == nil {
		return nil
	}
	return g.ErrorResp
}

func (g *GetPortalUserResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetPortalUserResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetPortalUserResponse) GetObject() *GetPortalUserResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
