// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/shared"
	"net/http"
)

type GetPublicPortalConfigRequest struct {
	OrgID string `queryParam:"style=form,explode=true,name=org_id"`
	// Origin of the portal
	Origin string `queryParam:"style=form,explode=true,name=origin"`
}

func (g *GetPublicPortalConfigRequest) GetOrgID() string {
	if g == nil {
		return ""
	}
	return g.OrgID
}

func (g *GetPublicPortalConfigRequest) GetOrigin() string {
	if g == nil {
		return ""
	}
	return g.Origin
}

type GetPublicPortalConfigResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Internal Server Error
	ErrorResp *shared.ErrorResp
	// Portal config retrieved successfully.
	PortalConfig *shared.PortalConfig
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetPublicPortalConfigResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetPublicPortalConfigResponse) GetErrorResp() *shared.ErrorResp {
	if g == nil {
		return nil
	}
	return g.ErrorResp
}

func (g *GetPublicPortalConfigResponse) GetPortalConfig() *shared.PortalConfig {
	if g == nil {
		return nil
	}
	return g.PortalConfig
}

func (g *GetPublicPortalConfigResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetPublicPortalConfigResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
