// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/shared"
	"net/http"
)

type GetResolvedSeamlessLinkRequest struct {
	// ID of the App if the Portal Extension was installed from an App
	AppID *string `queryParam:"style=form,explode=true,name=app_id"`
	// If the request is in a context of certain entities (i.e. the user in in a context of a specific contract), links can be customized for that. Portal User and Contact entities are automatically part of the context.
	ContextEntities []shared.ContextEntity `queryParam:"style=form,explode=true,name=context_entities"`
	// ID of the Portal Extension
	ExtensionID string `queryParam:"style=form,explode=true,name=extension_id"`
	// ID of the Seamless Link
	LinkID string `queryParam:"style=form,explode=true,name=link_id"`
}

func (g *GetResolvedSeamlessLinkRequest) GetAppID() *string {
	if g == nil {
		return nil
	}
	return g.AppID
}

func (g *GetResolvedSeamlessLinkRequest) GetContextEntities() []shared.ContextEntity {
	if g == nil {
		return nil
	}
	return g.ContextEntities
}

func (g *GetResolvedSeamlessLinkRequest) GetExtensionID() string {
	if g == nil {
		return ""
	}
	return g.ExtensionID
}

func (g *GetResolvedSeamlessLinkRequest) GetLinkID() string {
	if g == nil {
		return ""
	}
	return g.LinkID
}

// GetResolvedSeamlessLinkResponseBody - Resolved portal seamless link retrieved successfully.
type GetResolvedSeamlessLinkResponseBody struct {
	// Resolved link
	Link *string `json:"link,omitempty"`
}

func (g *GetResolvedSeamlessLinkResponseBody) GetLink() *string {
	if g == nil {
		return nil
	}
	return g.Link
}

type GetResolvedSeamlessLinkResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Could not authenticate the user
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Resolved portal seamless link retrieved successfully.
	Object *GetResolvedSeamlessLinkResponseBody
}

func (g *GetResolvedSeamlessLinkResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetResolvedSeamlessLinkResponse) GetErrorResp() *shared.ErrorResp {
	if g == nil {
		return nil
	}
	return g.ErrorResp
}

func (g *GetResolvedSeamlessLinkResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetResolvedSeamlessLinkResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetResolvedSeamlessLinkResponse) GetObject() *GetResolvedSeamlessLinkResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
