// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/shared"
	"net/http"
)

type GetValidSecondaryAttributesData struct {
	// Name of the secondary attribute
	Name *string `json:"name,omitempty"`
	// Type of the secondary attribute
	Type *string `json:"type,omitempty"`
}

func (g *GetValidSecondaryAttributesData) GetName() *string {
	if g == nil {
		return nil
	}
	return g.Name
}

func (g *GetValidSecondaryAttributesData) GetType() *string {
	if g == nil {
		return nil
	}
	return g.Type
}

// GetValidSecondaryAttributesResponseBody - Valid secondary attributes for the contact entity are returned successfully.
type GetValidSecondaryAttributesResponseBody struct {
	Data []GetValidSecondaryAttributesData `json:"data,omitempty"`
}

func (g *GetValidSecondaryAttributesResponseBody) GetData() []GetValidSecondaryAttributesData {
	if g == nil {
		return nil
	}
	return g.Data
}

type GetValidSecondaryAttributesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Could not authenticate the user
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Valid secondary attributes for the contact entity are returned successfully.
	Object *GetValidSecondaryAttributesResponseBody
}

func (g *GetValidSecondaryAttributesResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetValidSecondaryAttributesResponse) GetErrorResp() *shared.ErrorResp {
	if g == nil {
		return nil
	}
	return g.ErrorResp
}

func (g *GetValidSecondaryAttributesResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetValidSecondaryAttributesResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetValidSecondaryAttributesResponse) GetObject() *GetValidSecondaryAttributesResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
