// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/shared"
	"net/http"
)

type ListPortalsInternalRequest struct {
	Fields []string `queryParam:"style=form,explode=false,name=fields"`
	From   *float64 `default:"0" queryParam:"style=form,explode=true,name=from"`
	Size   *float64 `default:"25" queryParam:"style=form,explode=true,name=size"`
}

func (l ListPortalsInternalRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListPortalsInternalRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListPortalsInternalRequest) GetFields() []string {
	if l == nil {
		return nil
	}
	return l.Fields
}

func (l *ListPortalsInternalRequest) GetFrom() *float64 {
	if l == nil {
		return nil
	}
	return l.From
}

func (l *ListPortalsInternalRequest) GetSize() *float64 {
	if l == nil {
		return nil
	}
	return l.Size
}

// ListPortalsInternalResponseBody - List of portals
type ListPortalsInternalResponseBody struct {
	// Total number of portals for pagination
	Hits    *float64              `json:"hits,omitempty"`
	Results []shared.PortalConfig `json:"results,omitempty"`
}

func (l *ListPortalsInternalResponseBody) GetHits() *float64 {
	if l == nil {
		return nil
	}
	return l.Hits
}

func (l *ListPortalsInternalResponseBody) GetResults() []shared.PortalConfig {
	if l == nil {
		return nil
	}
	return l.Results
}

type ListPortalsInternalResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of portals
	Object *ListPortalsInternalResponseBody
}

func (l *ListPortalsInternalResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListPortalsInternalResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListPortalsInternalResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListPortalsInternalResponse) GetObject() *ListPortalsInternalResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
