// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/shared"
	"net/http"
)

type ResendPartnerInvitationRequest struct {
	PartnerID string `pathParam:"style=simple,explode=false,name=partner_id"`
}

func (r *ResendPartnerInvitationRequest) GetPartnerID() string {
	if r == nil {
		return ""
	}
	return r.PartnerID
}

// ResendPartnerInvitationResponseBody - Partner invitation resent successfully
type ResendPartnerInvitationResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (r *ResendPartnerInvitationResponseBody) GetMessage() *string {
	if r == nil {
		return nil
	}
	return r.Message
}

type ResendPartnerInvitationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The request could not be validated
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Partner invitation resent successfully
	Object *ResendPartnerInvitationResponseBody
}

func (r *ResendPartnerInvitationResponse) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *ResendPartnerInvitationResponse) GetErrorResp() *shared.ErrorResp {
	if r == nil {
		return nil
	}
	return r.ErrorResp
}

func (r *ResendPartnerInvitationResponse) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *ResendPartnerInvitationResponse) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}

func (r *ResendPartnerInvitationResponse) GetObject() *ResendPartnerInvitationResponseBody {
	if r == nil {
		return nil
	}
	return r.Object
}
