// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/shared"
	"net/http"
)

// RevokeTokenRequestBody - Token payload
type RevokeTokenRequestBody struct {
	// Refresh Token to be revoked
	RefreshToken string `json:"refresh_token"`
}

func (r *RevokeTokenRequestBody) GetRefreshToken() string {
	if r == nil {
		return ""
	}
	return r.RefreshToken
}

type RevokeTokenMessage string

const (
	RevokeTokenMessageTokenRevokedSuccessfully RevokeTokenMessage = "Token revoked successfully"
)

func (e RevokeTokenMessage) ToPointer() *RevokeTokenMessage {
	return &e
}
func (e *RevokeTokenMessage) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Token revoked successfully":
		*e = RevokeTokenMessage(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RevokeTokenMessage: %v", v)
	}
}

// RevokeTokenResponseBody - Access Tokens revoked successfully for the given Refresh Token.
type RevokeTokenResponseBody struct {
	Message *RevokeTokenMessage `json:"message,omitempty"`
}

func (r *RevokeTokenResponseBody) GetMessage() *RevokeTokenMessage {
	if r == nil {
		return nil
	}
	return r.Message
}

type RevokeTokenResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Could not authenticate the user
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Access Tokens revoked successfully for the given Refresh Token.
	Object *RevokeTokenResponseBody
}

func (r *RevokeTokenResponse) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *RevokeTokenResponse) GetErrorResp() *shared.ErrorResp {
	if r == nil {
		return nil
	}
	return r.ErrorResp
}

func (r *RevokeTokenResponse) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *RevokeTokenResponse) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}

func (r *RevokeTokenResponse) GetObject() *RevokeTokenResponseBody {
	if r == nil {
		return nil
	}
	return r.Object
}
