// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/shared"
	"net/http"
)

type SearchPortalUserEntitiesResponseBodyType string

const (
	SearchPortalUserEntitiesResponseBodyTypeEntityResponseWithHits        SearchPortalUserEntitiesResponseBodyType = "EntityResponseWithHits"
	SearchPortalUserEntitiesResponseBodyTypeEntityResponseGroupedWithHits SearchPortalUserEntitiesResponseBodyType = "EntityResponseGroupedWithHits"
)

// SearchPortalUserEntitiesResponseBody - The entities have been retrieved successfully for the portal user.
type SearchPortalUserEntitiesResponseBody struct {
	EntityResponseWithHits        *shared.EntityResponseWithHits        `queryParam:"inline" union:"member"`
	EntityResponseGroupedWithHits *shared.EntityResponseGroupedWithHits `queryParam:"inline" union:"member"`

	Type SearchPortalUserEntitiesResponseBodyType
}

func CreateSearchPortalUserEntitiesResponseBodyEntityResponseWithHits(entityResponseWithHits shared.EntityResponseWithHits) SearchPortalUserEntitiesResponseBody {
	typ := SearchPortalUserEntitiesResponseBodyTypeEntityResponseWithHits

	return SearchPortalUserEntitiesResponseBody{
		EntityResponseWithHits: &entityResponseWithHits,
		Type:                   typ,
	}
}

func CreateSearchPortalUserEntitiesResponseBodyEntityResponseGroupedWithHits(entityResponseGroupedWithHits shared.EntityResponseGroupedWithHits) SearchPortalUserEntitiesResponseBody {
	typ := SearchPortalUserEntitiesResponseBodyTypeEntityResponseGroupedWithHits

	return SearchPortalUserEntitiesResponseBody{
		EntityResponseGroupedWithHits: &entityResponseGroupedWithHits,
		Type:                          typ,
	}
}

func (u *SearchPortalUserEntitiesResponseBody) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var entityResponseWithHits shared.EntityResponseWithHits = shared.EntityResponseWithHits{}
	if err := utils.UnmarshalJSON(data, &entityResponseWithHits, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  SearchPortalUserEntitiesResponseBodyTypeEntityResponseWithHits,
			Value: &entityResponseWithHits,
		})
	}

	var entityResponseGroupedWithHits shared.EntityResponseGroupedWithHits = shared.EntityResponseGroupedWithHits{}
	if err := utils.UnmarshalJSON(data, &entityResponseGroupedWithHits, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  SearchPortalUserEntitiesResponseBodyTypeEntityResponseGroupedWithHits,
			Value: &entityResponseGroupedWithHits,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for SearchPortalUserEntitiesResponseBody", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for SearchPortalUserEntitiesResponseBody", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(SearchPortalUserEntitiesResponseBodyType)
	switch best.Type {
	case SearchPortalUserEntitiesResponseBodyTypeEntityResponseWithHits:
		u.EntityResponseWithHits = best.Value.(*shared.EntityResponseWithHits)
		return nil
	case SearchPortalUserEntitiesResponseBodyTypeEntityResponseGroupedWithHits:
		u.EntityResponseGroupedWithHits = best.Value.(*shared.EntityResponseGroupedWithHits)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for SearchPortalUserEntitiesResponseBody", string(data))
}

func (u SearchPortalUserEntitiesResponseBody) MarshalJSON() ([]byte, error) {
	if u.EntityResponseWithHits != nil {
		return utils.MarshalJSON(u.EntityResponseWithHits, "", true)
	}

	if u.EntityResponseGroupedWithHits != nil {
		return utils.MarshalJSON(u.EntityResponseGroupedWithHits, "", true)
	}

	return nil, errors.New("could not marshal union type SearchPortalUserEntitiesResponseBody: all fields are null")
}

type SearchPortalUserEntitiesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Could not authenticate the user
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The entities have been retrieved successfully for the portal user.
	OneOf *SearchPortalUserEntitiesResponseBody
}

func (s *SearchPortalUserEntitiesResponse) GetContentType() string {
	if s == nil {
		return ""
	}
	return s.ContentType
}

func (s *SearchPortalUserEntitiesResponse) GetErrorResp() *shared.ErrorResp {
	if s == nil {
		return nil
	}
	return s.ErrorResp
}

func (s *SearchPortalUserEntitiesResponse) GetStatusCode() int {
	if s == nil {
		return 0
	}
	return s.StatusCode
}

func (s *SearchPortalUserEntitiesResponse) GetRawResponse() *http.Response {
	if s == nil {
		return nil
	}
	return s.RawResponse
}

func (s *SearchPortalUserEntitiesResponse) GetOneOf() *SearchPortalUserEntitiesResponseBody {
	if s == nil {
		return nil
	}
	return s.OneOf
}
