// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/shared"
	"net/http"
)

// SwapPortalConfigRequestBody - Source and target portal IDs
type SwapPortalConfigRequestBody struct {
	// Items to swap
	ItemsToSwap []shared.SwappableConfig `json:"items_to_swap,omitempty"`
	// ID of the portal
	SourcePortalID string `json:"source_portal_id"`
	// ID of the portal
	TargetPortalID string `json:"target_portal_id"`
}

func (s *SwapPortalConfigRequestBody) GetItemsToSwap() []shared.SwappableConfig {
	if s == nil {
		return nil
	}
	return s.ItemsToSwap
}

func (s *SwapPortalConfigRequestBody) GetSourcePortalID() string {
	if s == nil {
		return ""
	}
	return s.SourcePortalID
}

func (s *SwapPortalConfigRequestBody) GetTargetPortalID() string {
	if s == nil {
		return ""
	}
	return s.TargetPortalID
}

// SwapPortalConfigResponseBody - Domain and users swapped successfully.
type SwapPortalConfigResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (s *SwapPortalConfigResponseBody) GetMessage() *string {
	if s == nil {
		return nil
	}
	return s.Message
}

type SwapPortalConfigResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The request could not be validated
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Domain and users swapped successfully.
	Object *SwapPortalConfigResponseBody
}

func (s *SwapPortalConfigResponse) GetContentType() string {
	if s == nil {
		return ""
	}
	return s.ContentType
}

func (s *SwapPortalConfigResponse) GetErrorResp() *shared.ErrorResp {
	if s == nil {
		return nil
	}
	return s.ErrorResp
}

func (s *SwapPortalConfigResponse) GetStatusCode() int {
	if s == nil {
		return 0
	}
	return s.StatusCode
}

func (s *SwapPortalConfigResponse) GetRawResponse() *http.Response {
	if s == nil {
		return nil
	}
	return s.RawResponse
}

func (s *SwapPortalConfigResponse) GetObject() *SwapPortalConfigResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
