// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/shared"
	"net/http"
)

type UpdateContactECPResponseBodyType string

const (
	UpdateContactECPResponseBodyTypeErrorResp           UpdateContactECPResponseBodyType = "ErrorResp"
	UpdateContactECPResponseBodyTypeFailedRuleErrorResp UpdateContactECPResponseBodyType = "FailedRuleErrorResp"
)

// UpdateContactECPResponseBody - The user is not allowed to access this resource
type UpdateContactECPResponseBody struct {
	ErrorResp           *shared.ErrorResp           `queryParam:"inline" union:"member"`
	FailedRuleErrorResp *shared.FailedRuleErrorResp `queryParam:"inline" union:"member"`

	Type UpdateContactECPResponseBodyType
}

func CreateUpdateContactECPResponseBodyErrorResp(errorResp shared.ErrorResp) UpdateContactECPResponseBody {
	typ := UpdateContactECPResponseBodyTypeErrorResp

	return UpdateContactECPResponseBody{
		ErrorResp: &errorResp,
		Type:      typ,
	}
}

func CreateUpdateContactECPResponseBodyFailedRuleErrorResp(failedRuleErrorResp shared.FailedRuleErrorResp) UpdateContactECPResponseBody {
	typ := UpdateContactECPResponseBodyTypeFailedRuleErrorResp

	return UpdateContactECPResponseBody{
		FailedRuleErrorResp: &failedRuleErrorResp,
		Type:                typ,
	}
}

func (u *UpdateContactECPResponseBody) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var errorResp shared.ErrorResp = shared.ErrorResp{}
	if err := utils.UnmarshalJSON(data, &errorResp, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  UpdateContactECPResponseBodyTypeErrorResp,
			Value: &errorResp,
		})
	}

	var failedRuleErrorResp shared.FailedRuleErrorResp = shared.FailedRuleErrorResp{}
	if err := utils.UnmarshalJSON(data, &failedRuleErrorResp, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  UpdateContactECPResponseBodyTypeFailedRuleErrorResp,
			Value: &failedRuleErrorResp,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for UpdateContactECPResponseBody", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for UpdateContactECPResponseBody", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(UpdateContactECPResponseBodyType)
	switch best.Type {
	case UpdateContactECPResponseBodyTypeErrorResp:
		u.ErrorResp = best.Value.(*shared.ErrorResp)
		return nil
	case UpdateContactECPResponseBodyTypeFailedRuleErrorResp:
		u.FailedRuleErrorResp = best.Value.(*shared.FailedRuleErrorResp)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for UpdateContactECPResponseBody", string(data))
}

func (u UpdateContactECPResponseBody) MarshalJSON() ([]byte, error) {
	if u.ErrorResp != nil {
		return utils.MarshalJSON(u.ErrorResp, "", true)
	}

	if u.FailedRuleErrorResp != nil {
		return utils.MarshalJSON(u.FailedRuleErrorResp, "", true)
	}

	return nil, errors.New("could not marshal union type UpdateContactECPResponseBody: all fields are null")
}

// UpdateContactResponseBody - Updated the contact details successfully.
type UpdateContactResponseBody struct {
	// The mapped contact of the portal user
	Data *shared.Contact `json:"data,omitempty"`
}

func (u *UpdateContactResponseBody) GetData() *shared.Contact {
	if u == nil {
		return nil
	}
	return u.Data
}

type UpdateContactResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Could not authenticate the user
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Updated the contact details successfully.
	Object *UpdateContactResponseBody
	// The user is not allowed to access this resource
	OneOf *UpdateContactECPResponseBody
}

func (u *UpdateContactResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateContactResponse) GetErrorResp() *shared.ErrorResp {
	if u == nil {
		return nil
	}
	return u.ErrorResp
}

func (u *UpdateContactResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateContactResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateContactResponse) GetObject() *UpdateContactResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}

func (u *UpdateContactResponse) GetOneOf() *UpdateContactECPResponseBody {
	if u == nil {
		return nil
	}
	return u.OneOf
}
