// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/shared"
	"net/http"
)

type UpdatePortalPageRequest struct {
	// The portal page to update
	PageRequest shared.PageRequest `request:"mediaType=application/json"`
	ID          string             `pathParam:"style=simple,explode=false,name=id"`
}

func (u *UpdatePortalPageRequest) GetPageRequest() shared.PageRequest {
	if u == nil {
		return shared.PageRequest{}
	}
	return u.PageRequest
}

func (u *UpdatePortalPageRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

type UpdatePortalPageResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Could not authenticate the user
	ErrorResp *shared.ErrorResp
	// The portal page has been fetched successfully.
	Page *shared.Page
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (u *UpdatePortalPageResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdatePortalPageResponse) GetErrorResp() *shared.ErrorResp {
	if u == nil {
		return nil
	}
	return u.ErrorResp
}

func (u *UpdatePortalPageResponse) GetPage() *shared.Page {
	if u == nil {
		return nil
	}
	return u.Page
}

func (u *UpdatePortalPageResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdatePortalPageResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}
