// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/shared"
	"net/http"
)

type UpdateOpportunityRequest struct {
	// Requested opportunity body to update
	RequestBody map[string]any `request:"mediaType=application/json"`
	// The ID of opportunity
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (u *UpdateOpportunityRequest) GetRequestBody() map[string]any {
	if u == nil {
		return map[string]any{}
	}
	return u.RequestBody
}

func (u *UpdateOpportunityRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

// UpdateOpportunityResponseBody - Updated the opportunity successfully.
type UpdateOpportunityResponseBody struct {
	// The opportunity entity
	Data *shared.Opportunity `json:"data,omitempty"`
}

func (u *UpdateOpportunityResponseBody) GetData() *shared.Opportunity {
	if u == nil {
		return nil
	}
	return u.Data
}

type UpdateOpportunityResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Could not authenticate the user
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Updated the opportunity successfully.
	Object *UpdateOpportunityResponseBody
}

func (u *UpdateOpportunityResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateOpportunityResponse) GetErrorResp() *shared.ErrorResp {
	if u == nil {
		return nil
	}
	return u.ErrorResp
}

func (u *UpdateOpportunityResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateOpportunityResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateOpportunityResponse) GetObject() *UpdateOpportunityResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}
