// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/shared"
	"net/http"
)

type UpsertPortalRequest struct {
	// Portal payload
	UpsertPortalConfig shared.UpsertPortalConfig `request:"mediaType=application/json"`
	// Origin of the portal
	Origin string `queryParam:"style=form,explode=true,name=origin"`
	// Portal ID
	PortalID *string `queryParam:"style=form,explode=true,name=portal_id"`
}

func (u *UpsertPortalRequest) GetUpsertPortalConfig() shared.UpsertPortalConfig {
	if u == nil {
		return shared.UpsertPortalConfig{}
	}
	return u.UpsertPortalConfig
}

func (u *UpsertPortalRequest) GetOrigin() string {
	if u == nil {
		return ""
	}
	return u.Origin
}

func (u *UpsertPortalRequest) GetPortalID() *string {
	if u == nil {
		return nil
	}
	return u.PortalID
}

type UpsertPortalResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The request could not be validated
	ErrorResp *shared.ErrorResp
	// Portal updated successfully.
	PortalConfig *shared.PortalConfig
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (u *UpsertPortalResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpsertPortalResponse) GetErrorResp() *shared.ErrorResp {
	if u == nil {
		return nil
	}
	return u.ErrorResp
}

func (u *UpsertPortalResponse) GetPortalConfig() *shared.PortalConfig {
	if u == nil {
		return nil
	}
	return u.PortalConfig
}

func (u *UpsertPortalResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpsertPortalResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}
