// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/shared"
	"net/http"
)

type ValidateTokenResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Could not authenticate the user
	ErrorResp *shared.ErrorResp
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (v *ValidateTokenResponse) GetContentType() string {
	if v == nil {
		return ""
	}
	return v.ContentType
}

func (v *ValidateTokenResponse) GetErrorResp() *shared.ErrorResp {
	if v == nil {
		return nil
	}
	return v.ErrorResp
}

func (v *ValidateTokenResponse) GetStatusCode() int {
	if v == nil {
		return 0
	}
	return v.StatusCode
}

func (v *ValidateTokenResponse) GetRawResponse() *http.Response {
	if v == nil {
		return nil
	}
	return v.RawResponse
}
