// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// AllowedFileExtensions - Allowed file extensions for upload
type AllowedFileExtensions struct {
	Archive      []string `json:"archive,omitempty"`
	AudioVideo   []string `json:"audioVideo,omitempty"`
	Cad          []string `json:"cad,omitempty"`
	Calendar     []string `json:"calendar,omitempty"`
	Document     []string `json:"document,omitempty"`
	Email        []string `json:"email,omitempty"`
	Image        []string `json:"image,omitempty"`
	Other        []string `json:"other,omitempty"`
	Presentation []string `json:"presentation,omitempty"`
	Spreadsheet  []string `json:"spreadsheet,omitempty"`
}

func (a *AllowedFileExtensions) GetArchive() []string {
	if a == nil {
		return nil
	}
	return a.Archive
}

func (a *AllowedFileExtensions) GetAudioVideo() []string {
	if a == nil {
		return nil
	}
	return a.AudioVideo
}

func (a *AllowedFileExtensions) GetCad() []string {
	if a == nil {
		return nil
	}
	return a.Cad
}

func (a *AllowedFileExtensions) GetCalendar() []string {
	if a == nil {
		return nil
	}
	return a.Calendar
}

func (a *AllowedFileExtensions) GetDocument() []string {
	if a == nil {
		return nil
	}
	return a.Document
}

func (a *AllowedFileExtensions) GetEmail() []string {
	if a == nil {
		return nil
	}
	return a.Email
}

func (a *AllowedFileExtensions) GetImage() []string {
	if a == nil {
		return nil
	}
	return a.Image
}

func (a *AllowedFileExtensions) GetOther() []string {
	if a == nil {
		return nil
	}
	return a.Other
}

func (a *AllowedFileExtensions) GetPresentation() []string {
	if a == nil {
		return nil
	}
	return a.Presentation
}

func (a *AllowedFileExtensions) GetSpreadsheet() []string {
	if a == nil {
		return nil
	}
	return a.Spreadsheet
}
