// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Balance struct {
	// Current balance of the customer in cents. (precision 2)
	Balance *int64 `json:"balance,omitempty"`
	// Currency code in ISO 4217 format
	BalanceCurrency *string `json:"balance_currency,omitempty"`
	// Current balance of the customer in decimal string representation.
	BalanceDecimal *float64 `json:"balance_decimal,omitempty"`
}

func (b *Balance) GetBalance() *int64 {
	if b == nil {
		return nil
	}
	return b.Balance
}

func (b *Balance) GetBalanceCurrency() *string {
	if b == nil {
		return nil
	}
	return b.BalanceCurrency
}

func (b *Balance) GetBalanceDecimal() *float64 {
	if b == nil {
		return nil
	}
	return b.BalanceDecimal
}
