// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/internal/utils"
	"time"
)

type DollarRelationRef struct {
	// ID of the related billing address.
	ID *string `json:"_id,omitempty"`
	// Entity ID for the related billing address.
	EntityID *string `json:"entity_id,omitempty"`
	// Path to the related billing address.
	Path *string `json:"path,omitempty"`
}

func (d *DollarRelationRef) GetID() *string {
	if d == nil {
		return nil
	}
	return d.ID
}

func (d *DollarRelationRef) GetEntityID() *string {
	if d == nil {
		return nil
	}
	return d.EntityID
}

func (d *DollarRelationRef) GetPath() *string {
	if d == nil {
		return nil
	}
	return d.Path
}

type BillingAddress struct {
	DollarRelationRef []DollarRelationRef `json:"$relation_ref,omitempty"`
}

func (b *BillingAddress) GetDollarRelationRef() []DollarRelationRef {
	if b == nil {
		return nil
	}
	return b.DollarRelationRef
}

type BillingAccountDollarRelation struct {
	// Entity ID for the related billing contact.
	EntityID *string `json:"entity_id,omitempty"`
}

func (b *BillingAccountDollarRelation) GetEntityID() *string {
	if b == nil {
		return nil
	}
	return b.EntityID
}

type BillingContact struct {
	DollarRelation []BillingAccountDollarRelation `json:"$relation,omitempty"`
}

func (b *BillingContact) GetDollarRelation() []BillingAccountDollarRelation {
	if b == nil {
		return nil
	}
	return b.DollarRelation
}

// BillingAccount - A billing account
type BillingAccount struct {
	AdditionalProperties any `additionalProperties:"true" json:"-"`
	// Creation timestamp of the entity
	CreatedAt time.Time `json:"_created_at"`
	// Entity ID
	ID string `json:"_id"`
	// Organization ID the entity belongs to
	Org string `json:"_org"`
	// Array of entity tags
	Tags []string `json:"_tags,omitempty"`
	// Title of the entity
	Title string `json:"_title"`
	// Last update timestamp of the entity
	UpdatedAt time.Time `json:"_updated_at"`
	// Balance of the billing account
	Balance *float64 `json:"balance,omitempty"`
	// Currency code in ISO 4217 format
	BalanceCurrency *string `json:"balance_currency,omitempty"`
	// Balance of the billing account in decimal string representation
	BalanceDecimal *string `json:"balance_decimal,omitempty"`
	// Billing account number
	BillingAccountNumber *string         `json:"billing_account_number,omitempty"`
	BillingAddress       *BillingAddress `json:"billing_address,omitempty"`
	BillingContact       *BillingContact `json:"billing_contact,omitempty"`
}

func (b BillingAccount) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BillingAccount) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BillingAccount) GetAdditionalProperties() any {
	if b == nil {
		return nil
	}
	return b.AdditionalProperties
}

func (b *BillingAccount) GetCreatedAt() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.CreatedAt
}

func (b *BillingAccount) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

func (b *BillingAccount) GetOrg() string {
	if b == nil {
		return ""
	}
	return b.Org
}

func (b *BillingAccount) GetTags() []string {
	if b == nil {
		return nil
	}
	return b.Tags
}

func (b *BillingAccount) GetTitle() string {
	if b == nil {
		return ""
	}
	return b.Title
}

func (b *BillingAccount) GetUpdatedAt() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.UpdatedAt
}

func (b *BillingAccount) GetBalance() *float64 {
	if b == nil {
		return nil
	}
	return b.Balance
}

func (b *BillingAccount) GetBalanceCurrency() *string {
	if b == nil {
		return nil
	}
	return b.BalanceCurrency
}

func (b *BillingAccount) GetBalanceDecimal() *string {
	if b == nil {
		return nil
	}
	return b.BalanceDecimal
}

func (b *BillingAccount) GetBillingAccountNumber() *string {
	if b == nil {
		return nil
	}
	return b.BillingAccountNumber
}

func (b *BillingAccount) GetBillingAddress() *BillingAddress {
	if b == nil {
		return nil
	}
	return b.BillingAddress
}

func (b *BillingAccount) GetBillingContact() *BillingContact {
	if b == nil {
		return nil
	}
	return b.BillingContact
}
