// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/internal/utils"
)

type BlockProps struct {
	AdditionalProperties any `additionalProperties:"true" json:"-"`
	// The content of the block
	Content map[string]any `json:"content,omitempty"`
	// The design of the block
	Design map[string]any `json:"design,omitempty"`
	// The conditions that need to be met for the block to be shown
	Visibility map[string]any `json:"visibility,omitempty"`
}

func (b BlockProps) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BlockProps) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BlockProps) GetAdditionalProperties() any {
	if b == nil {
		return nil
	}
	return b.AdditionalProperties
}

func (b *BlockProps) GetContent() map[string]any {
	if b == nil {
		return nil
	}
	return b.Content
}

func (b *BlockProps) GetDesign() map[string]any {
	if b == nil {
		return nil
	}
	return b.Design
}

func (b *BlockProps) GetVisibility() map[string]any {
	if b == nil {
		return nil
	}
	return b.Visibility
}
