// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type BusinessPartnerItem struct {
	// Entity ID
	ID                 *string                       `json:"_id,omitempty"`
	Title              *string                       `json:"_title,omitempty"`
	AccessStatus       *bool                         `json:"access_status,omitempty"`
	Email              *string                       `json:"email,omitempty"`
	FirstName          *string                       `json:"first_name,omitempty"`
	HasPortalUser      *bool                         `json:"has_portal_user,omitempty"`
	LastName           *string                       `json:"last_name,omitempty"`
	RegistrationStatus *PortalUserRegistrationStatus `json:"registration_status,omitempty"`
}

func (b *BusinessPartnerItem) GetID() *string {
	if b == nil {
		return nil
	}
	return b.ID
}

func (b *BusinessPartnerItem) GetTitle() *string {
	if b == nil {
		return nil
	}
	return b.Title
}

func (b *BusinessPartnerItem) GetAccessStatus() *bool {
	if b == nil {
		return nil
	}
	return b.AccessStatus
}

func (b *BusinessPartnerItem) GetEmail() *string {
	if b == nil {
		return nil
	}
	return b.Email
}

func (b *BusinessPartnerItem) GetFirstName() *string {
	if b == nil {
		return nil
	}
	return b.FirstName
}

func (b *BusinessPartnerItem) GetHasPortalUser() *bool {
	if b == nil {
		return nil
	}
	return b.HasPortalUser
}

func (b *BusinessPartnerItem) GetLastName() *string {
	if b == nil {
		return nil
	}
	return b.LastName
}

func (b *BusinessPartnerItem) GetRegistrationStatus() *PortalUserRegistrationStatus {
	if b == nil {
		return nil
	}
	return b.RegistrationStatus
}
