// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ContractIdentifier struct {
	// Name of the identifier/attribute
	Name *string `json:"name,omitempty"`
	// URL-friendly identifier for the entity schema
	Schema *string `json:"schema,omitempty"`
}

func (c *ContractIdentifier) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *ContractIdentifier) GetSchema() *string {
	if c == nil {
		return nil
	}
	return c.Schema
}
