// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/internal/utils"
)

type ContentWidgetHeadline struct {
	De *string `json:"de,omitempty"`
	En *string `json:"en,omitempty"`
}

func (c ContentWidgetHeadline) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ContentWidgetHeadline) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ContentWidgetHeadline) GetDe() *string {
	if c == nil {
		return nil
	}
	return c.De
}

func (c *ContentWidgetHeadline) GetEn() *string {
	if c == nil {
		return nil
	}
	return c.En
}

type ContentWidgetSubHeadline struct {
	De *string `json:"de,omitempty"`
	En *string `json:"en,omitempty"`
}

func (c ContentWidgetSubHeadline) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ContentWidgetSubHeadline) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ContentWidgetSubHeadline) GetDe() *string {
	if c == nil {
		return nil
	}
	return c.De
}

func (c *ContentWidgetSubHeadline) GetEn() *string {
	if c == nil {
		return nil
	}
	return c.En
}

type ContentWidgetType string

const (
	ContentWidgetTypeActionWidget       ContentWidgetType = "ACTION_WIDGET"
	ContentWidgetTypeContentWidget      ContentWidgetType = "CONTENT_WIDGET"
	ContentWidgetTypeEntityWidget       ContentWidgetType = "ENTITY_WIDGET"
	ContentWidgetTypeTeaserWidget       ContentWidgetType = "TEASER_WIDGET"
	ContentWidgetTypeDocumentWidget     ContentWidgetType = "DOCUMENT_WIDGET"
	ContentWidgetTypePaymentWidget      ContentWidgetType = "PAYMENT_WIDGET"
	ContentWidgetTypeMeterReadingWidget ContentWidgetType = "METER_READING_WIDGET"
	ContentWidgetTypeMeterChartWidget   ContentWidgetType = "METER_CHART_WIDGET"
	ContentWidgetTypeCampaignWidget     ContentWidgetType = "CAMPAIGN_WIDGET"
)

func (e ContentWidgetType) ToPointer() *ContentWidgetType {
	return &e
}
func (e *ContentWidgetType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ACTION_WIDGET":
		fallthrough
	case "CONTENT_WIDGET":
		fallthrough
	case "ENTITY_WIDGET":
		fallthrough
	case "TEASER_WIDGET":
		fallthrough
	case "DOCUMENT_WIDGET":
		fallthrough
	case "PAYMENT_WIDGET":
		fallthrough
	case "METER_READING_WIDGET":
		fallthrough
	case "METER_CHART_WIDGET":
		fallthrough
	case "CAMPAIGN_WIDGET":
		*e = ContentWidgetType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ContentWidgetType: %v", v)
	}
}

type ContentWidget struct {
	Content  *string                `json:"content,omitempty"`
	Headline *ContentWidgetHeadline `json:"headline,omitempty"`
	ID       string                 `json:"id"`
	// Index of the widget in the list, used for ordering (left or right)
	ListIndex   int64                     `json:"listIndex"`
	SubHeadline *ContentWidgetSubHeadline `json:"subHeadline,omitempty"`
	Type        ContentWidgetType         `json:"type"`
}

func (c ContentWidget) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ContentWidget) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ContentWidget) GetContent() *string {
	if c == nil {
		return nil
	}
	return c.Content
}

func (c *ContentWidget) GetHeadline() *ContentWidgetHeadline {
	if c == nil {
		return nil
	}
	return c.Headline
}

func (c *ContentWidget) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *ContentWidget) GetListIndex() int64 {
	if c == nil {
		return 0
	}
	return c.ListIndex
}

func (c *ContentWidget) GetSubHeadline() *ContentWidgetSubHeadline {
	if c == nil {
		return nil
	}
	return c.SubHeadline
}

func (c *ContentWidget) GetType() ContentWidgetType {
	if c == nil {
		return ContentWidgetType("")
	}
	return c.Type
}
