// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ContextEntity - An entity reference for context-aware operations
type ContextEntity struct {
	// Entity id
	EntityID string `queryParam:"name=entity_id"`
	// Entity schema
	EntitySchema string `queryParam:"name=entity_schema"`
}

func (c *ContextEntity) GetEntityID() string {
	if c == nil {
		return ""
	}
	return c.EntityID
}

func (c *ContextEntity) GetEntitySchema() string {
	if c == nil {
		return ""
	}
	return c.EntitySchema
}
