// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateUserRequest struct {
	// Entity ID
	ContactID *string `json:"contactId,omitempty"`
	// Deprecated. Use registration_identifiers instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	ContactIdentifiers map[string]string `json:"contactIdentifiers,omitempty"`
	// User's email address
	Email string `json:"email"`
	// First Name of the portal user
	FirstName *string `json:"first_name,omitempty"`
	// Last Name of the portal user
	LastName *string `json:"last_name,omitempty"`
	// ID of the organization
	OrgID string `json:"orgId"`
	// User's password
	Password string `json:"password"`
	// Identifier-value pairs per schema to identify a contact of a portal user during the resgistration
	RegistrationIdentifiers map[string]map[string]string `json:"registration_identifiers,omitempty"`
}

func (c *CreateUserRequest) GetContactID() *string {
	if c == nil {
		return nil
	}
	return c.ContactID
}

func (c *CreateUserRequest) GetContactIdentifiers() map[string]string {
	if c == nil {
		return nil
	}
	return c.ContactIdentifiers
}

func (c *CreateUserRequest) GetEmail() string {
	if c == nil {
		return ""
	}
	return c.Email
}

func (c *CreateUserRequest) GetFirstName() *string {
	if c == nil {
		return nil
	}
	return c.FirstName
}

func (c *CreateUserRequest) GetLastName() *string {
	if c == nil {
		return nil
	}
	return c.LastName
}

func (c *CreateUserRequest) GetOrgID() string {
	if c == nil {
		return ""
	}
	return c.OrgID
}

func (c *CreateUserRequest) GetPassword() string {
	if c == nil {
		return ""
	}
	return c.Password
}

func (c *CreateUserRequest) GetRegistrationIdentifiers() map[string]map[string]string {
	if c == nil {
		return nil
	}
	return c.RegistrationIdentifiers
}
