// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DeleteEntityFile struct {
	// Entity ID
	EntityID string `json:"entity_id"`
	// Entity type
	EntityType string `json:"entity_type"`
	// Array of file entity IDs
	FileEntityIds []string `json:"file_entity_ids"`
}

func (d *DeleteEntityFile) GetEntityID() string {
	if d == nil {
		return ""
	}
	return d.EntityID
}

func (d *DeleteEntityFile) GetEntityType() string {
	if d == nil {
		return ""
	}
	return d.EntityType
}

func (d *DeleteEntityFile) GetFileEntityIds() []string {
	if d == nil {
		return []string{}
	}
	return d.FileEntityIds
}
