// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/internal/utils"
)

// EntitySlugConfig - Per-slug search configuration with scoped targets and templates
type EntitySlugConfig struct {
	// URL-friendly identifier for the entity schema
	Slug      string            `json:"slug"`
	Targets   []string          `json:"targets,omitempty"`
	Templates map[string]string `json:"templates,omitempty"`
}

func (e EntitySlugConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EntitySlugConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EntitySlugConfig) GetSlug() string {
	if e == nil {
		return ""
	}
	return e.Slug
}

func (e *EntitySlugConfig) GetTargets() []string {
	if e == nil {
		return nil
	}
	return e.Targets
}

func (e *EntitySlugConfig) GetTemplates() map[string]string {
	if e == nil {
		return nil
	}
	return e.Templates
}
