// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/internal/utils"
)

// Filters - Elasticsearch filter object
type Filters struct {
}

type FiltersSchema string

const (
	FiltersSchemaContact    FiltersSchema = "contact"
	FiltersSchemaContract   FiltersSchema = "contract"
	FiltersSchemaPortalUser FiltersSchema = "portal_user"
)

func (e FiltersSchema) ToPointer() *FiltersSchema {
	return &e
}
func (e *FiltersSchema) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "contact":
		fallthrough
	case "contract":
		fallthrough
	case "portal_user":
		*e = FiltersSchema(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FiltersSchema: %v", v)
	}
}

type GroupAfterKeyType string

const (
	GroupAfterKeyTypeStr    GroupAfterKeyType = "str"
	GroupAfterKeyTypeNumber GroupAfterKeyType = "number"
)

type GroupAfterKey struct {
	Str    *string  `queryParam:"inline" union:"member"`
	Number *float64 `queryParam:"inline" union:"member"`

	Type GroupAfterKeyType
}

func CreateGroupAfterKeyStr(str string) GroupAfterKey {
	typ := GroupAfterKeyTypeStr

	return GroupAfterKey{
		Str:  &str,
		Type: typ,
	}
}

func CreateGroupAfterKeyNumber(number float64) GroupAfterKey {
	typ := GroupAfterKeyTypeNumber

	return GroupAfterKey{
		Number: &number,
		Type:   typ,
	}
}

func (u *GroupAfterKey) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  GroupAfterKeyTypeStr,
			Value: &str,
		})
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  GroupAfterKeyTypeNumber,
			Value: &number,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for GroupAfterKey", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for GroupAfterKey", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(GroupAfterKeyType)
	switch best.Type {
	case GroupAfterKeyTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case GroupAfterKeyTypeNumber:
		u.Number = best.Value.(*float64)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GroupAfterKey", string(data))
}

func (u GroupAfterKey) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	return nil, errors.New("could not marshal union type GroupAfterKey: all fields are null")
}

// GroupSort - Sort order for groups
type GroupSort string

const (
	GroupSortAsc  GroupSort = "asc"
	GroupSortDesc GroupSort = "desc"
)

func (e GroupSort) ToPointer() *GroupSort {
	return &e
}
func (e *GroupSort) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = GroupSort(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GroupSort: %v", v)
	}
}

type SlugType string

const (
	SlugTypeEntitySlug        SlugType = "EntitySlug"
	SlugTypeArrayOfEntitySlug SlugType = "arrayOfEntitySlug"
)

// Slug - Single entity schema slug or array of slugs
type Slug struct {
	EntitySlug        *EntitySlug  `queryParam:"inline" union:"member"`
	ArrayOfEntitySlug []EntitySlug `queryParam:"inline" union:"member"`

	Type SlugType
}

func CreateSlugEntitySlug(entitySlug EntitySlug) Slug {
	typ := SlugTypeEntitySlug

	return Slug{
		EntitySlug: &entitySlug,
		Type:       typ,
	}
}

func CreateSlugArrayOfEntitySlug(arrayOfEntitySlug []EntitySlug) Slug {
	typ := SlugTypeArrayOfEntitySlug

	return Slug{
		ArrayOfEntitySlug: arrayOfEntitySlug,
		Type:              typ,
	}
}

func (u *Slug) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var entitySlug EntitySlug = EntitySlug("")
	if err := utils.UnmarshalJSON(data, &entitySlug, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  SlugTypeEntitySlug,
			Value: &entitySlug,
		})
	}

	var arrayOfEntitySlug []EntitySlug = []EntitySlug{}
	if err := utils.UnmarshalJSON(data, &arrayOfEntitySlug, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  SlugTypeArrayOfEntitySlug,
			Value: arrayOfEntitySlug,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Slug", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Slug", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(SlugType)
	switch best.Type {
	case SlugTypeEntitySlug:
		u.EntitySlug = best.Value.(*EntitySlug)
		return nil
	case SlugTypeArrayOfEntitySlug:
		u.ArrayOfEntitySlug = best.Value.([]EntitySlug)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Slug", string(data))
}

func (u Slug) MarshalJSON() ([]byte, error) {
	if u.EntitySlug != nil {
		return utils.MarshalJSON(u.EntitySlug, "", true)
	}

	if u.ArrayOfEntitySlug != nil {
		return utils.MarshalJSON(u.ArrayOfEntitySlug, "", true)
	}

	return nil, errors.New("could not marshal union type Slug: all fields are null")
}

type EntitySearchParams struct {
	// List of contract IDs to filter by
	Contracts []string `json:"contracts,omitempty"`
	// List of entity fields to include in search results
	Fields []string `json:"fields,omitempty"`
	// Additional filters to apply to the search query
	Filters []Filters `json:"filters,omitempty"`
	// Schema-based filters for entity relations.
	FiltersSchema []FiltersSchema `json:"filters_schema,omitempty"`
	From          *int64          `default:"0" json:"from"`
	// Field to group results by
	Group *string `json:"group,omitempty"`
	// Composite aggregation key for group pagination
	GroupAfterKey map[string]GroupAfterKey `json:"group_after_key,omitempty"`
	// Number of groups to return
	GroupSize *int64 `default:"100" json:"group_size"`
	// Sort order for groups
	GroupSort *GroupSort `default:"asc" json:"group_sort"`
	// When true, enables entity hydration to resolve nested $relation & $relation_ref references in-place.
	Hydrate *bool `default:"false" json:"hydrate"`
	// Keyword search query
	Q *string `json:"q,omitempty"`
	// List of fields that can be searched
	QFields []string `json:"q_fields,omitempty"`
	// Max search size is 1000 with higher values defaulting to 1000
	Size *int64 `default:"100" json:"size"`
	// Single entity schema slug or array of slugs
	Slug Slug    `json:"slug"`
	Sort *string `json:"sort,omitempty"`
	// Filters from these targets will be applied to the search query.
	Targets []string `json:"targets,omitempty"`
}

func (e EntitySearchParams) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EntitySearchParams) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EntitySearchParams) GetContracts() []string {
	if e == nil {
		return nil
	}
	return e.Contracts
}

func (e *EntitySearchParams) GetFields() []string {
	if e == nil {
		return nil
	}
	return e.Fields
}

func (e *EntitySearchParams) GetFilters() []Filters {
	if e == nil {
		return nil
	}
	return e.Filters
}

func (e *EntitySearchParams) GetFiltersSchema() []FiltersSchema {
	if e == nil {
		return nil
	}
	return e.FiltersSchema
}

func (e *EntitySearchParams) GetFrom() *int64 {
	if e == nil {
		return nil
	}
	return e.From
}

func (e *EntitySearchParams) GetGroup() *string {
	if e == nil {
		return nil
	}
	return e.Group
}

func (e *EntitySearchParams) GetGroupAfterKey() map[string]GroupAfterKey {
	if e == nil {
		return nil
	}
	return e.GroupAfterKey
}

func (e *EntitySearchParams) GetGroupSize() *int64 {
	if e == nil {
		return nil
	}
	return e.GroupSize
}

func (e *EntitySearchParams) GetGroupSort() *GroupSort {
	if e == nil {
		return nil
	}
	return e.GroupSort
}

func (e *EntitySearchParams) GetHydrate() *bool {
	if e == nil {
		return nil
	}
	return e.Hydrate
}

func (e *EntitySearchParams) GetQ() *string {
	if e == nil {
		return nil
	}
	return e.Q
}

func (e *EntitySearchParams) GetQFields() []string {
	if e == nil {
		return nil
	}
	return e.QFields
}

func (e *EntitySearchParams) GetSize() *int64 {
	if e == nil {
		return nil
	}
	return e.Size
}

func (e *EntitySearchParams) GetSlug() Slug {
	if e == nil {
		return Slug{}
	}
	return e.Slug
}

func (e *EntitySearchParams) GetSort() *string {
	if e == nil {
		return nil
	}
	return e.Sort
}

func (e *EntitySearchParams) GetTargets() []string {
	if e == nil {
		return nil
	}
	return e.Targets
}
