// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type EntityEditRule struct {
	AllowedDecrement              *string  `json:"allowed_decrement,omitempty"`
	AllowedIncrement              *string  `json:"allowed_increment,omitempty"`
	Attribute                     *string  `json:"attribute,omitempty"`
	CadencePeriod                 *float64 `json:"cadence_period,omitempty"`
	CadencePeriodType             *string  `json:"cadence_period_type,omitempty"`
	ChangesAllowed                *float64 `json:"changes_allowed,omitempty"`
	GracePeriod                   *float64 `json:"grace_period,omitempty"`
	NumberOfDaysBeforeRestriction *float64 `json:"number_of_days_before_restriction,omitempty"`
	RuleType                      *string  `json:"rule_type,omitempty"`
	// URL-friendly identifier for the entity schema
	Slug *EntitySlug `json:"slug,omitempty"`
}

func (e *EntityEditRule) GetAllowedDecrement() *string {
	if e == nil {
		return nil
	}
	return e.AllowedDecrement
}

func (e *EntityEditRule) GetAllowedIncrement() *string {
	if e == nil {
		return nil
	}
	return e.AllowedIncrement
}

func (e *EntityEditRule) GetAttribute() *string {
	if e == nil {
		return nil
	}
	return e.Attribute
}

func (e *EntityEditRule) GetCadencePeriod() *float64 {
	if e == nil {
		return nil
	}
	return e.CadencePeriod
}

func (e *EntityEditRule) GetCadencePeriodType() *string {
	if e == nil {
		return nil
	}
	return e.CadencePeriodType
}

func (e *EntityEditRule) GetChangesAllowed() *float64 {
	if e == nil {
		return nil
	}
	return e.ChangesAllowed
}

func (e *EntityEditRule) GetGracePeriod() *float64 {
	if e == nil {
		return nil
	}
	return e.GracePeriod
}

func (e *EntityEditRule) GetNumberOfDaysBeforeRestriction() *float64 {
	if e == nil {
		return nil
	}
	return e.NumberOfDaysBeforeRestriction
}

func (e *EntityEditRule) GetRuleType() *string {
	if e == nil {
		return nil
	}
	return e.RuleType
}

func (e *EntityEditRule) GetSlug() *EntitySlug {
	if e == nil {
		return nil
	}
	return e.Slug
}
