// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ErrorResp - Could not authenticate the user
type ErrorResp struct {
	// Error message
	Message *string `json:"message,omitempty"`
}

func (o *ErrorResp) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}
