// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/internal/utils"
)

type Cache struct {
	// Key to use to identify the auth response. Supports interpolation.
	Key string `json:"key"`
	// Time to live in seconds for the cache. Supports interpolation.
	TTL string `json:"ttl"`
}

func (c *Cache) GetKey() string {
	if c == nil {
		return ""
	}
	return c.Key
}

func (c *Cache) GetTTL() string {
	if c == nil {
		return ""
	}
	return c.TTL
}

type ExtensionAuthBlock struct {
	// JSON body to use for authentication. Supports variable interpolation. Content format is determined by Content-Type header.
	Body  map[string]string `json:"body,omitempty"`
	Cache *Cache            `json:"cache,omitempty"`
	// Headers to use for authentication. Supports variable interpolation.
	Headers map[string]string `json:"headers,omitempty"`
	// HTTP method to use for authentication
	Method *string `default:"GET" json:"method"`
	// Parameters to append to the URL. Supports variable interpolation.
	Params map[string]string `json:"params,omitempty"`
	// URL to use for authentication. Supports variable interpolation.
	URL string `json:"url"`
}

func (e ExtensionAuthBlock) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExtensionAuthBlock) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ExtensionAuthBlock) GetBody() map[string]string {
	if e == nil {
		return nil
	}
	return e.Body
}

func (e *ExtensionAuthBlock) GetCache() *Cache {
	if e == nil {
		return nil
	}
	return e.Cache
}

func (e *ExtensionAuthBlock) GetHeaders() map[string]string {
	if e == nil {
		return nil
	}
	return e.Headers
}

func (e *ExtensionAuthBlock) GetMethod() *string {
	if e == nil {
		return nil
	}
	return e.Method
}

func (e *ExtensionAuthBlock) GetParams() map[string]string {
	if e == nil {
		return nil
	}
	return e.Params
}

func (e *ExtensionAuthBlock) GetURL() string {
	if e == nil {
		return ""
	}
	return e.URL
}
