// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/internal/utils"
)

// Description - Name of the extension.
type Description struct {
	AdditionalProperties map[string]string `additionalProperties:"true" json:"-"`
	// Name of the extension in English.
	En string `json:"en"`
}

func (d Description) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *Description) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *Description) GetAdditionalProperties() map[string]string {
	if d == nil {
		return nil
	}
	return d.AdditionalProperties
}

func (d *Description) GetEn() string {
	if d == nil {
		return ""
	}
	return d.En
}

type SchemasExtensionHookMeterReadingPlausibilityCheckCall struct {
	// JSON body to use for the call. Supports variable interpolation.
	Body map[string]string `json:"body"`
	// Headers to use. Supports variable interpolation.
	Headers map[string]string `json:"headers"`
	// URL to call. Supports variable interpolation.
	URL string `json:"url"`
}

func (s SchemasExtensionHookMeterReadingPlausibilityCheckCall) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemasExtensionHookMeterReadingPlausibilityCheckCall) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SchemasExtensionHookMeterReadingPlausibilityCheckCall) GetBody() map[string]string {
	if s == nil {
		return map[string]string{}
	}
	return s.Body
}

func (s *SchemasExtensionHookMeterReadingPlausibilityCheckCall) GetHeaders() map[string]string {
	if s == nil {
		return map[string]string{}
	}
	return s.Headers
}

func (s *SchemasExtensionHookMeterReadingPlausibilityCheckCall) GetURL() string {
	if s == nil {
		return ""
	}
	return s.URL
}

// SchemasExtensionHookMeterReadingPlausibilityCheckResolved - Response to the call
type SchemasExtensionHookMeterReadingPlausibilityCheckResolved struct {
	// Lower allowed limit of the meter reading
	LowerLimit *string `json:"lower_limit,omitempty"`
	// Upper allowed limit of the meter reading
	UpperLimit *string `json:"upper_limit,omitempty"`
	// Indicate whether the meter reading is plausible
	Valid *string `json:"valid,omitempty"`
}

func (s SchemasExtensionHookMeterReadingPlausibilityCheckResolved) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemasExtensionHookMeterReadingPlausibilityCheckResolved) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SchemasExtensionHookMeterReadingPlausibilityCheckResolved) GetLowerLimit() *string {
	if s == nil {
		return nil
	}
	return s.LowerLimit
}

func (s *SchemasExtensionHookMeterReadingPlausibilityCheckResolved) GetUpperLimit() *string {
	if s == nil {
		return nil
	}
	return s.UpperLimit
}

func (s *SchemasExtensionHookMeterReadingPlausibilityCheckResolved) GetValid() *string {
	if s == nil {
		return nil
	}
	return s.Valid
}

type SchemasExtensionHookMeterReadingPlausibilityCheckType string

const (
	SchemasExtensionHookMeterReadingPlausibilityCheckTypeMeterReadingPlausibilityCheck SchemasExtensionHookMeterReadingPlausibilityCheckType = "meterReadingPlausibilityCheck"
)

func (e SchemasExtensionHookMeterReadingPlausibilityCheckType) ToPointer() *SchemasExtensionHookMeterReadingPlausibilityCheckType {
	return &e
}
func (e *SchemasExtensionHookMeterReadingPlausibilityCheckType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "meterReadingPlausibilityCheck":
		*e = SchemasExtensionHookMeterReadingPlausibilityCheckType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SchemasExtensionHookMeterReadingPlausibilityCheckType: %v", v)
	}
}

// ExtensionHookMeterReadingPlausibilityCheckSchemas - Hook that checks the plausibility of meter readings before they are saved. This hook makes a POST call whenever a user is trying to save a meter reading. The expected response to the call is:
//   - 200:
//     If meter reading is plausible, the response should contain:
//   - valid: true
//     If meter reading is not plausible, the response should contain:
//   - valid: false
type ExtensionHookMeterReadingPlausibilityCheckSchemas struct {
	Auth *ExtensionAuthBlock                                   `json:"auth,omitempty"`
	Call SchemasExtensionHookMeterReadingPlausibilityCheckCall `json:"call"`
	// Identifier of the hook. Should not change between updates.
	ID *string `json:"id,omitempty"`
	// Response to the call
	Resolved SchemasExtensionHookMeterReadingPlausibilityCheckResolved `json:"resolved"`
	Type     SchemasExtensionHookMeterReadingPlausibilityCheckType     `json:"type"`
	// If true, requests are made from a set of static IP addresses and only allow connections to a set of allowed IP addresses. Get in touch with us to add your IP addresses.
	UseStaticIps *bool `default:"false" json:"use_static_ips"`
}

func (e ExtensionHookMeterReadingPlausibilityCheckSchemas) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExtensionHookMeterReadingPlausibilityCheckSchemas) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ExtensionHookMeterReadingPlausibilityCheckSchemas) GetAuth() *ExtensionAuthBlock {
	if e == nil {
		return nil
	}
	return e.Auth
}

func (e *ExtensionHookMeterReadingPlausibilityCheckSchemas) GetCall() SchemasExtensionHookMeterReadingPlausibilityCheckCall {
	if e == nil {
		return SchemasExtensionHookMeterReadingPlausibilityCheckCall{}
	}
	return e.Call
}

func (e *ExtensionHookMeterReadingPlausibilityCheckSchemas) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *ExtensionHookMeterReadingPlausibilityCheckSchemas) GetResolved() SchemasExtensionHookMeterReadingPlausibilityCheckResolved {
	if e == nil {
		return SchemasExtensionHookMeterReadingPlausibilityCheckResolved{}
	}
	return e.Resolved
}

func (e *ExtensionHookMeterReadingPlausibilityCheckSchemas) GetType() SchemasExtensionHookMeterReadingPlausibilityCheckType {
	if e == nil {
		return SchemasExtensionHookMeterReadingPlausibilityCheckType("")
	}
	return e.Type
}

func (e *ExtensionHookMeterReadingPlausibilityCheckSchemas) GetUseStaticIps() *bool {
	if e == nil {
		return nil
	}
	return e.UseStaticIps
}

type SchemasExtensionHookCostDataRetrievalCall struct {
	// Request body to send. Supports variable interpolation. Content format is determined by Content-Type header.
	Body map[string]string `json:"body,omitempty"`
	// Headers to use. Supports variable interpolation.
	Headers map[string]string `json:"headers,omitempty"`
	// HTTP method to use for the call
	Method *string `default:"GET" json:"method"`
	// Parameters to append to the URL. Supports variable interpolation.
	Params map[string]string `json:"params,omitempty"`
	// URL to call. Supports variable interpolation.
	URL string `json:"url"`
}

func (s SchemasExtensionHookCostDataRetrievalCall) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemasExtensionHookCostDataRetrievalCall) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SchemasExtensionHookCostDataRetrievalCall) GetBody() map[string]string {
	if s == nil {
		return nil
	}
	return s.Body
}

func (s *SchemasExtensionHookCostDataRetrievalCall) GetHeaders() map[string]string {
	if s == nil {
		return nil
	}
	return s.Headers
}

func (s *SchemasExtensionHookCostDataRetrievalCall) GetMethod() *string {
	if s == nil {
		return nil
	}
	return s.Method
}

func (s *SchemasExtensionHookCostDataRetrievalCall) GetParams() map[string]string {
	if s == nil {
		return nil
	}
	return s.Params
}

func (s *SchemasExtensionHookCostDataRetrievalCall) GetURL() string {
	if s == nil {
		return ""
	}
	return s.URL
}

type SchemasResolved struct {
	// Optional path to the data (array) in the response. If omitted, the data is assumed to be on the top level.
	DataPath *string `json:"dataPath,omitempty"`
}

func (s SchemasResolved) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemasResolved) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SchemasResolved) GetDataPath() *string {
	if s == nil {
		return nil
	}
	return s.DataPath
}

type SchemasExtensionHookCostDataRetrievalType string

const (
	SchemasExtensionHookCostDataRetrievalTypeCostDataRetrieval SchemasExtensionHookCostDataRetrievalType = "costDataRetrieval"
)

func (e SchemasExtensionHookCostDataRetrievalType) ToPointer() *SchemasExtensionHookCostDataRetrievalType {
	return &e
}
func (e *SchemasExtensionHookCostDataRetrievalType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "costDataRetrieval":
		*e = SchemasExtensionHookCostDataRetrievalType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SchemasExtensionHookCostDataRetrievalType: %v", v)
	}
}

// ExtensionHookCostDataRetrievalSchemas - Hook that will allow using the specified source as data for consumption visualizations. This hook is triggered to fetch the data. Format of the request and response has to follow the following specification: TBD. The expected response to the call is:
//
//   - 200 with the time series data
type ExtensionHookCostDataRetrievalSchemas struct {
	Auth *ExtensionAuthBlock                       `json:"auth,omitempty"`
	Call SchemasExtensionHookCostDataRetrievalCall `json:"call"`
	// Identifier of the hook. Should not change between updates.
	ID       *string                                   `json:"id,omitempty"`
	Resolved *SchemasResolved                          `json:"resolved,omitempty"`
	Type     SchemasExtensionHookCostDataRetrievalType `json:"type"`
	// If true, requests are made from a set of static IP addresses and only allow connections to a set of allowed IP addresses. Get in touch with us to add your IP addresses.
	UseStaticIps *bool `default:"false" json:"use_static_ips"`
}

func (e ExtensionHookCostDataRetrievalSchemas) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExtensionHookCostDataRetrievalSchemas) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ExtensionHookCostDataRetrievalSchemas) GetAuth() *ExtensionAuthBlock {
	if e == nil {
		return nil
	}
	return e.Auth
}

func (e *ExtensionHookCostDataRetrievalSchemas) GetCall() SchemasExtensionHookCostDataRetrievalCall {
	if e == nil {
		return SchemasExtensionHookCostDataRetrievalCall{}
	}
	return e.Call
}

func (e *ExtensionHookCostDataRetrievalSchemas) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *ExtensionHookCostDataRetrievalSchemas) GetResolved() *SchemasResolved {
	if e == nil {
		return nil
	}
	return e.Resolved
}

func (e *ExtensionHookCostDataRetrievalSchemas) GetType() SchemasExtensionHookCostDataRetrievalType {
	if e == nil {
		return SchemasExtensionHookCostDataRetrievalType("")
	}
	return e.Type
}

func (e *ExtensionHookCostDataRetrievalSchemas) GetUseStaticIps() *bool {
	if e == nil {
		return nil
	}
	return e.UseStaticIps
}

type Call struct {
	// Request body to send. Supports variable interpolation. Content format is determined by Content-Type header.
	Body map[string]string `json:"body,omitempty"`
	// Headers to use. Supports variable interpolation.
	Headers map[string]string `json:"headers,omitempty"`
	// HTTP method to use for the call
	Method *string `default:"GET" json:"method"`
	// Parameters to append to the URL. Supports variable interpolation.
	Params map[string]string `json:"params,omitempty"`
	// URL to call. Supports variable interpolation.
	URL string `json:"url"`
}

func (c Call) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Call) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *Call) GetBody() map[string]string {
	if c == nil {
		return nil
	}
	return c.Body
}

func (c *Call) GetHeaders() map[string]string {
	if c == nil {
		return nil
	}
	return c.Headers
}

func (c *Call) GetMethod() *string {
	if c == nil {
		return nil
	}
	return c.Method
}

func (c *Call) GetParams() map[string]string {
	if c == nil {
		return nil
	}
	return c.Params
}

func (c *Call) GetURL() string {
	if c == nil {
		return ""
	}
	return c.URL
}

type Resolved struct {
	// Optional path to the data (array) in the response. If omitted, the data is assumed to be on the top level.
	DataPath *string `json:"dataPath,omitempty"`
}

func (r Resolved) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *Resolved) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *Resolved) GetDataPath() *string {
	if r == nil {
		return nil
	}
	return r.DataPath
}

type Type string

const (
	TypeConsumptionDataRetrieval Type = "consumptionDataRetrieval"
)

func (e Type) ToPointer() *Type {
	return &e
}
func (e *Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "consumptionDataRetrieval":
		*e = Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Type: %v", v)
	}
}

// Schemas - Hook that will allow using the specified source as data for consumption visualizations. This hook is triggered to fetch the data. Format of the request and response has to follow the following specification: TBD. The expected response to the call is:
//
//   - 200 with the time series data
type Schemas struct {
	Auth *ExtensionAuthBlock `json:"auth,omitempty"`
	Call Call                `json:"call"`
	// Identifier of the hook. Should not change between updates.
	ID       *string   `json:"id,omitempty"`
	Resolved *Resolved `json:"resolved,omitempty"`
	Type     Type      `json:"type"`
	// If true, requests are made from a set of static IP addresses and only allow connections to a set of allowed IP addresses. Get in touch with us to add your IP addresses.
	UseStaticIps *bool `default:"false" json:"use_static_ips"`
}

func (s Schemas) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *Schemas) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *Schemas) GetAuth() *ExtensionAuthBlock {
	if s == nil {
		return nil
	}
	return s.Auth
}

func (s *Schemas) GetCall() Call {
	if s == nil {
		return Call{}
	}
	return s.Call
}

func (s *Schemas) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *Schemas) GetResolved() *Resolved {
	if s == nil {
		return nil
	}
	return s.Resolved
}

func (s *Schemas) GetType() Type {
	if s == nil {
		return Type("")
	}
	return s.Type
}

func (s *Schemas) GetUseStaticIps() *bool {
	if s == nil {
		return nil
	}
	return s.UseStaticIps
}

type SchemasExtensionHookPriceDataRetrievalCall struct {
	// Request body to send. Supports variable interpolation. Content format is determined by Content-Type header.
	Body map[string]string `json:"body,omitempty"`
	// Headers to use. Supports variable interpolation.
	Headers map[string]string `json:"headers,omitempty"`
	// HTTP method to use for the call
	Method *string `default:"GET" json:"method"`
	// Parameters to append to the URL. Supports variable interpolation.
	Params map[string]string `json:"params,omitempty"`
	// URL to call. Supports variable interpolation.
	URL string `json:"url"`
}

func (s SchemasExtensionHookPriceDataRetrievalCall) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemasExtensionHookPriceDataRetrievalCall) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SchemasExtensionHookPriceDataRetrievalCall) GetBody() map[string]string {
	if s == nil {
		return nil
	}
	return s.Body
}

func (s *SchemasExtensionHookPriceDataRetrievalCall) GetHeaders() map[string]string {
	if s == nil {
		return nil
	}
	return s.Headers
}

func (s *SchemasExtensionHookPriceDataRetrievalCall) GetMethod() *string {
	if s == nil {
		return nil
	}
	return s.Method
}

func (s *SchemasExtensionHookPriceDataRetrievalCall) GetParams() map[string]string {
	if s == nil {
		return nil
	}
	return s.Params
}

func (s *SchemasExtensionHookPriceDataRetrievalCall) GetURL() string {
	if s == nil {
		return ""
	}
	return s.URL
}

type SchemasExtensionHookPriceDataRetrievalResolved struct {
	// Optional path to the data (array) in the response. If omitted, the data is assumed to be on the top level.
	DataPath *string `json:"dataPath,omitempty"`
}

func (s SchemasExtensionHookPriceDataRetrievalResolved) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemasExtensionHookPriceDataRetrievalResolved) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SchemasExtensionHookPriceDataRetrievalResolved) GetDataPath() *string {
	if s == nil {
		return nil
	}
	return s.DataPath
}

type SchemasExtensionHookPriceDataRetrievalType string

const (
	SchemasExtensionHookPriceDataRetrievalTypePriceDataRetrieval SchemasExtensionHookPriceDataRetrievalType = "priceDataRetrieval"
)

func (e SchemasExtensionHookPriceDataRetrievalType) ToPointer() *SchemasExtensionHookPriceDataRetrievalType {
	return &e
}
func (e *SchemasExtensionHookPriceDataRetrievalType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "priceDataRetrieval":
		*e = SchemasExtensionHookPriceDataRetrievalType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SchemasExtensionHookPriceDataRetrievalType: %v", v)
	}
}

// ExtensionHookPriceDataRetrievalSchemas - Hook that will allow using the specified source as data for price visualizations. This hook is triggered to fetch the data. Format of the request and response has to follow the following specification: TBD. The expected response to the call is:
//
//   - 200 with the time series data
type ExtensionHookPriceDataRetrievalSchemas struct {
	Auth *ExtensionAuthBlock                        `json:"auth,omitempty"`
	Call SchemasExtensionHookPriceDataRetrievalCall `json:"call"`
	// Identifier of the hook. Should not change between updates.
	ID       *string                                         `json:"id,omitempty"`
	Resolved *SchemasExtensionHookPriceDataRetrievalResolved `json:"resolved,omitempty"`
	Type     SchemasExtensionHookPriceDataRetrievalType      `json:"type"`
	// If true, requests are made from a set of static IP addresses and only allow connections to a set of allowed IP addresses. Get in touch with us to add your IP addresses.
	UseStaticIps *bool `default:"false" json:"use_static_ips"`
}

func (e ExtensionHookPriceDataRetrievalSchemas) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExtensionHookPriceDataRetrievalSchemas) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ExtensionHookPriceDataRetrievalSchemas) GetAuth() *ExtensionAuthBlock {
	if e == nil {
		return nil
	}
	return e.Auth
}

func (e *ExtensionHookPriceDataRetrievalSchemas) GetCall() SchemasExtensionHookPriceDataRetrievalCall {
	if e == nil {
		return SchemasExtensionHookPriceDataRetrievalCall{}
	}
	return e.Call
}

func (e *ExtensionHookPriceDataRetrievalSchemas) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *ExtensionHookPriceDataRetrievalSchemas) GetResolved() *SchemasExtensionHookPriceDataRetrievalResolved {
	if e == nil {
		return nil
	}
	return e.Resolved
}

func (e *ExtensionHookPriceDataRetrievalSchemas) GetType() SchemasExtensionHookPriceDataRetrievalType {
	if e == nil {
		return SchemasExtensionHookPriceDataRetrievalType("")
	}
	return e.Type
}

func (e *ExtensionHookPriceDataRetrievalSchemas) GetUseStaticIps() *bool {
	if e == nil {
		return nil
	}
	return e.UseStaticIps
}

// AssignmentMode - Mode of contract assignment. See hook description for mode details.
type AssignmentMode string

const (
	AssignmentModeContracts           AssignmentMode = "contracts"
	AssignmentModeContactToContracts  AssignmentMode = "contact_to_contracts"
	AssignmentModeContactToPortalUser AssignmentMode = "contact_to_portal_user"
)

func (e AssignmentMode) ToPointer() *AssignmentMode {
	return &e
}
func (e *AssignmentMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "contracts":
		fallthrough
	case "contact_to_contracts":
		fallthrough
	case "contact_to_portal_user":
		*e = AssignmentMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AssignmentMode: %v", v)
	}
}

// Body - Optional JSON body to use for the call. Defaults to object with all configured identifiers grouped by entity, e.g. `{"contract": {"contract_name": "Name"}}`. Supports variable interpolation.
type Body struct {
}

func (b Body) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *Body) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

type SchemasCall struct {
	// Optional JSON body to use for the call. Defaults to object with all configured identifiers grouped by entity, e.g. `{"contract": {"contract_name": "Name"}}`. Supports variable interpolation.
	Body *Body `json:"body,omitempty"`
	// Headers to use. Supports variable interpolation.
	Headers map[string]string `json:"headers"`
	// HTTP method to use for the call
	Method *string `default:"POST" json:"method"`
	// Parameters to append to the URL. Supports variable interpolation.
	Params map[string]string `json:"params,omitempty"`
	// Contact ID usually retrieved from the response body, e.g. `{{CallResponse.data.contact_id}}`. If no result is passed and the request suceeds, we attempt to resolve the Contact ID automatically. Supports variable interpolation.
	Result *string `json:"result,omitempty"`
	// URL to call. Supports variable interpolation.
	URL string `json:"url"`
}

func (s SchemasCall) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemasCall) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SchemasCall) GetBody() *Body {
	if s == nil {
		return nil
	}
	return s.Body
}

func (s *SchemasCall) GetHeaders() map[string]string {
	if s == nil {
		return map[string]string{}
	}
	return s.Headers
}

func (s *SchemasCall) GetMethod() *string {
	if s == nil {
		return nil
	}
	return s.Method
}

func (s *SchemasCall) GetParams() map[string]string {
	if s == nil {
		return nil
	}
	return s.Params
}

func (s *SchemasCall) GetResult() *string {
	if s == nil {
		return nil
	}
	return s.Result
}

func (s *SchemasCall) GetURL() string {
	if s == nil {
		return ""
	}
	return s.URL
}

// Explanation of the hook.
type Explanation struct {
	AdditionalProperties map[string]string `additionalProperties:"true" json:"-"`
	// Explanation of the functionality shown to the end user.
	En string `json:"en"`
}

func (e Explanation) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *Explanation) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *Explanation) GetAdditionalProperties() map[string]string {
	if e == nil {
		return nil
	}
	return e.AdditionalProperties
}

func (e *Explanation) GetEn() string {
	if e == nil {
		return ""
	}
	return e.En
}

type SchemasType string

const (
	SchemasTypeContractIdentification SchemasType = "contractIdentification"
)

func (e SchemasType) ToPointer() *SchemasType {
	return &e
}
func (e *SchemasType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "contractIdentification":
		*e = SchemasType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SchemasType: %v", v)
	}
}

// ExtensionHookContractIdentificationSchemas - Hook that replaces the built-in Contract identification for self-assignment. This hook involves an HTTP request whenever a user is trying to self-assign Contract(s).
// The expected response http status code to the call is:
//   - 200 if found
//   - 404 if not found
//
// The following assignment modes are supported:
//   - `contracts`: We expect the response to contain Contract ids (customizable using `result` property).
//   - `contact_to_contracts`: We expect the response to contain a Contact id (customizable using `result` property) and we will assign the Contact as a Customer to the Contracts and (optionally) update the Contact attribute specified by `contact_relation_attribute` to add the matched Contact.
//   - `contact_to_portal_user`: We expect the response to contain a Contact id (customizable using `result` property) and we will assign the Contact to the Portal User. Portal User will be able to see all data including Contracts transitively.
//
// Defaults to `contact_to_contracts` for backwards compatibility. We recommend using `contact_to_portal_user` as it does not influence the data model of business entities.
type ExtensionHookContractIdentificationSchemas struct {
	// Mode of contract assignment. See hook description for mode details.
	AssignmentMode *AssignmentMode     `default:"contact_to_contracts" json:"assignment_mode"`
	Auth           *ExtensionAuthBlock `json:"auth,omitempty"`
	Call           SchemasCall         `json:"call"`
	// Name of the Contact attribute to update with the matched Contact ID when using `contact_to_contracts` mode. Must be a Contact relation attribute supporting multiple entities.
	ContactRelationAttribute *string `json:"contact_relation_attribute,omitempty"`
	// Explanation of the hook.
	Explanation *Explanation `json:"explanation,omitempty"`
	// Identifier of the hook. Should not change between updates.
	ID   *string     `json:"id,omitempty"`
	Type SchemasType `json:"type"`
	// If true, requests are made from a set of static IP addresses and only allow connections to a set of allowed IP addresses. Get in touch with us to add your IP addresses.
	UseStaticIps *bool `default:"false" json:"use_static_ips"`
}

func (e ExtensionHookContractIdentificationSchemas) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExtensionHookContractIdentificationSchemas) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ExtensionHookContractIdentificationSchemas) GetAssignmentMode() *AssignmentMode {
	if e == nil {
		return nil
	}
	return e.AssignmentMode
}

func (e *ExtensionHookContractIdentificationSchemas) GetAuth() *ExtensionAuthBlock {
	if e == nil {
		return nil
	}
	return e.Auth
}

func (e *ExtensionHookContractIdentificationSchemas) GetCall() SchemasCall {
	if e == nil {
		return SchemasCall{}
	}
	return e.Call
}

func (e *ExtensionHookContractIdentificationSchemas) GetContactRelationAttribute() *string {
	if e == nil {
		return nil
	}
	return e.ContactRelationAttribute
}

func (e *ExtensionHookContractIdentificationSchemas) GetExplanation() *Explanation {
	if e == nil {
		return nil
	}
	return e.Explanation
}

func (e *ExtensionHookContractIdentificationSchemas) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *ExtensionHookContractIdentificationSchemas) GetType() SchemasType {
	if e == nil {
		return SchemasType("")
	}
	return e.Type
}

func (e *ExtensionHookContractIdentificationSchemas) GetUseStaticIps() *bool {
	if e == nil {
		return nil
	}
	return e.UseStaticIps
}

// SchemasBody - Optional JSON body to use for the call. Defaults to object with all configured identifiers grouped by entity, e.g. `{"contract": {"contract_name": "Name"}}`. Supports variable interpolation.
type SchemasBody struct {
}

func (s SchemasBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemasBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

type SchemasExtensionHookRegistrationIdentifiersCheckCall struct {
	// Optional JSON body to use for the call. Defaults to object with all configured identifiers grouped by entity, e.g. `{"contract": {"contract_name": "Name"}}`. Supports variable interpolation.
	Body *SchemasBody `json:"body,omitempty"`
	// Headers to use. Supports variable interpolation.
	Headers map[string]string `json:"headers"`
	// HTTP method to use for the call
	Method *string `default:"POST" json:"method"`
	// Parameters to append to the URL. Supports variable interpolation.
	Params map[string]string `json:"params,omitempty"`
	// Contact ID usually retrieved from the response body, e.g. `{{CallResponse.data.contact_id}}`. If no result is passed and the request suceeds, we attempt to resolve the Contact ID automatically. Supports variable interpolation.
	Result *string `json:"result,omitempty"`
	// URL to call. Supports variable interpolation.
	URL string `json:"url"`
}

func (s SchemasExtensionHookRegistrationIdentifiersCheckCall) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemasExtensionHookRegistrationIdentifiersCheckCall) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SchemasExtensionHookRegistrationIdentifiersCheckCall) GetBody() *SchemasBody {
	if s == nil {
		return nil
	}
	return s.Body
}

func (s *SchemasExtensionHookRegistrationIdentifiersCheckCall) GetHeaders() map[string]string {
	if s == nil {
		return map[string]string{}
	}
	return s.Headers
}

func (s *SchemasExtensionHookRegistrationIdentifiersCheckCall) GetMethod() *string {
	if s == nil {
		return nil
	}
	return s.Method
}

func (s *SchemasExtensionHookRegistrationIdentifiersCheckCall) GetParams() map[string]string {
	if s == nil {
		return nil
	}
	return s.Params
}

func (s *SchemasExtensionHookRegistrationIdentifiersCheckCall) GetResult() *string {
	if s == nil {
		return nil
	}
	return s.Result
}

func (s *SchemasExtensionHookRegistrationIdentifiersCheckCall) GetURL() string {
	if s == nil {
		return ""
	}
	return s.URL
}

type SchemasExtensionHookRegistrationIdentifiersCheckType string

const (
	SchemasExtensionHookRegistrationIdentifiersCheckTypeRegistrationIdentifiersCheck SchemasExtensionHookRegistrationIdentifiersCheckType = "registrationIdentifiersCheck"
)

func (e SchemasExtensionHookRegistrationIdentifiersCheckType) ToPointer() *SchemasExtensionHookRegistrationIdentifiersCheckType {
	return &e
}
func (e *SchemasExtensionHookRegistrationIdentifiersCheckType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "registrationIdentifiersCheck":
		*e = SchemasExtensionHookRegistrationIdentifiersCheckType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SchemasExtensionHookRegistrationIdentifiersCheckType: %v", v)
	}
}

// ExtensionHookRegistrationIdentifiersCheckSchemas - Hook that replaces the built-in registration identifiers check. This hook makes a POST call whenever a user is trying to register to find the corresponding contact. The expected response to the call is:
//   - 200 with contact id if exactly one contact is found
//   - 404 if no contact is found or more than contact is found
type ExtensionHookRegistrationIdentifiersCheckSchemas struct {
	Auth *ExtensionAuthBlock                                  `json:"auth,omitempty"`
	Call SchemasExtensionHookRegistrationIdentifiersCheckCall `json:"call"`
	// Identifier of the hook. Should not change between updates.
	ID   *string                                              `json:"id,omitempty"`
	Type SchemasExtensionHookRegistrationIdentifiersCheckType `json:"type"`
	// If true, requests are made from a set of static IP addresses and only allow connections to a set of allowed IP addresses. Get in touch with us to add your IP addresses.
	UseStaticIps *bool `default:"false" json:"use_static_ips"`
}

func (e ExtensionHookRegistrationIdentifiersCheckSchemas) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExtensionHookRegistrationIdentifiersCheckSchemas) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ExtensionHookRegistrationIdentifiersCheckSchemas) GetAuth() *ExtensionAuthBlock {
	if e == nil {
		return nil
	}
	return e.Auth
}

func (e *ExtensionHookRegistrationIdentifiersCheckSchemas) GetCall() SchemasExtensionHookRegistrationIdentifiersCheckCall {
	if e == nil {
		return SchemasExtensionHookRegistrationIdentifiersCheckCall{}
	}
	return e.Call
}

func (e *ExtensionHookRegistrationIdentifiersCheckSchemas) GetID() *string {
	if e == nil {
		return nil
	}
	return e.ID
}

func (e *ExtensionHookRegistrationIdentifiersCheckSchemas) GetType() SchemasExtensionHookRegistrationIdentifiersCheckType {
	if e == nil {
		return SchemasExtensionHookRegistrationIdentifiersCheckType("")
	}
	return e.Type
}

func (e *ExtensionHookRegistrationIdentifiersCheckSchemas) GetUseStaticIps() *bool {
	if e == nil {
		return nil
	}
	return e.UseStaticIps
}

type HooksType string

const (
	HooksTypeExtensionHookRegistrationIdentifiersCheckSchemas  HooksType = "ExtensionHookRegistrationIdentifiersCheck_Schemas"
	HooksTypeExtensionHookContractIdentificationSchemas        HooksType = "ExtensionHookContractIdentification_Schemas"
	HooksTypeExtensionHookPriceDataRetrievalSchemas            HooksType = "ExtensionHookPriceDataRetrieval_Schemas"
	HooksTypeSchemas                                           HooksType = "Schemas"
	HooksTypeExtensionHookCostDataRetrievalSchemas             HooksType = "ExtensionHookCostDataRetrieval_Schemas"
	HooksTypeExtensionHookMeterReadingPlausibilityCheckSchemas HooksType = "ExtensionHookMeterReadingPlausibilityCheck_Schemas"
)

type Hooks struct {
	ExtensionHookRegistrationIdentifiersCheckSchemas  *ExtensionHookRegistrationIdentifiersCheckSchemas  `queryParam:"inline" union:"member"`
	ExtensionHookContractIdentificationSchemas        *ExtensionHookContractIdentificationSchemas        `queryParam:"inline" union:"member"`
	ExtensionHookPriceDataRetrievalSchemas            *ExtensionHookPriceDataRetrievalSchemas            `queryParam:"inline" union:"member"`
	Schemas                                           *Schemas                                           `queryParam:"inline" union:"member"`
	ExtensionHookCostDataRetrievalSchemas             *ExtensionHookCostDataRetrievalSchemas             `queryParam:"inline" union:"member"`
	ExtensionHookMeterReadingPlausibilityCheckSchemas *ExtensionHookMeterReadingPlausibilityCheckSchemas `queryParam:"inline" union:"member"`

	Type HooksType
}

func CreateHooksExtensionHookRegistrationIdentifiersCheckSchemas(extensionHookRegistrationIdentifiersCheckSchemas ExtensionHookRegistrationIdentifiersCheckSchemas) Hooks {
	typ := HooksTypeExtensionHookRegistrationIdentifiersCheckSchemas

	return Hooks{
		ExtensionHookRegistrationIdentifiersCheckSchemas: &extensionHookRegistrationIdentifiersCheckSchemas,
		Type: typ,
	}
}

func CreateHooksExtensionHookContractIdentificationSchemas(extensionHookContractIdentificationSchemas ExtensionHookContractIdentificationSchemas) Hooks {
	typ := HooksTypeExtensionHookContractIdentificationSchemas

	return Hooks{
		ExtensionHookContractIdentificationSchemas: &extensionHookContractIdentificationSchemas,
		Type: typ,
	}
}

func CreateHooksExtensionHookPriceDataRetrievalSchemas(extensionHookPriceDataRetrievalSchemas ExtensionHookPriceDataRetrievalSchemas) Hooks {
	typ := HooksTypeExtensionHookPriceDataRetrievalSchemas

	return Hooks{
		ExtensionHookPriceDataRetrievalSchemas: &extensionHookPriceDataRetrievalSchemas,
		Type:                                   typ,
	}
}

func CreateHooksSchemas(schemas Schemas) Hooks {
	typ := HooksTypeSchemas

	return Hooks{
		Schemas: &schemas,
		Type:    typ,
	}
}

func CreateHooksExtensionHookCostDataRetrievalSchemas(extensionHookCostDataRetrievalSchemas ExtensionHookCostDataRetrievalSchemas) Hooks {
	typ := HooksTypeExtensionHookCostDataRetrievalSchemas

	return Hooks{
		ExtensionHookCostDataRetrievalSchemas: &extensionHookCostDataRetrievalSchemas,
		Type:                                  typ,
	}
}

func CreateHooksExtensionHookMeterReadingPlausibilityCheckSchemas(extensionHookMeterReadingPlausibilityCheckSchemas ExtensionHookMeterReadingPlausibilityCheckSchemas) Hooks {
	typ := HooksTypeExtensionHookMeterReadingPlausibilityCheckSchemas

	return Hooks{
		ExtensionHookMeterReadingPlausibilityCheckSchemas: &extensionHookMeterReadingPlausibilityCheckSchemas,
		Type: typ,
	}
}

func (u *Hooks) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var extensionHookRegistrationIdentifiersCheckSchemas ExtensionHookRegistrationIdentifiersCheckSchemas = ExtensionHookRegistrationIdentifiersCheckSchemas{}
	if err := utils.UnmarshalJSON(data, &extensionHookRegistrationIdentifiersCheckSchemas, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  HooksTypeExtensionHookRegistrationIdentifiersCheckSchemas,
			Value: &extensionHookRegistrationIdentifiersCheckSchemas,
		})
	}

	var extensionHookContractIdentificationSchemas ExtensionHookContractIdentificationSchemas = ExtensionHookContractIdentificationSchemas{}
	if err := utils.UnmarshalJSON(data, &extensionHookContractIdentificationSchemas, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  HooksTypeExtensionHookContractIdentificationSchemas,
			Value: &extensionHookContractIdentificationSchemas,
		})
	}

	var extensionHookPriceDataRetrievalSchemas ExtensionHookPriceDataRetrievalSchemas = ExtensionHookPriceDataRetrievalSchemas{}
	if err := utils.UnmarshalJSON(data, &extensionHookPriceDataRetrievalSchemas, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  HooksTypeExtensionHookPriceDataRetrievalSchemas,
			Value: &extensionHookPriceDataRetrievalSchemas,
		})
	}

	var schemas Schemas = Schemas{}
	if err := utils.UnmarshalJSON(data, &schemas, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  HooksTypeSchemas,
			Value: &schemas,
		})
	}

	var extensionHookCostDataRetrievalSchemas ExtensionHookCostDataRetrievalSchemas = ExtensionHookCostDataRetrievalSchemas{}
	if err := utils.UnmarshalJSON(data, &extensionHookCostDataRetrievalSchemas, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  HooksTypeExtensionHookCostDataRetrievalSchemas,
			Value: &extensionHookCostDataRetrievalSchemas,
		})
	}

	var extensionHookMeterReadingPlausibilityCheckSchemas ExtensionHookMeterReadingPlausibilityCheckSchemas = ExtensionHookMeterReadingPlausibilityCheckSchemas{}
	if err := utils.UnmarshalJSON(data, &extensionHookMeterReadingPlausibilityCheckSchemas, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  HooksTypeExtensionHookMeterReadingPlausibilityCheckSchemas,
			Value: &extensionHookMeterReadingPlausibilityCheckSchemas,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Hooks", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Hooks", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(HooksType)
	switch best.Type {
	case HooksTypeExtensionHookRegistrationIdentifiersCheckSchemas:
		u.ExtensionHookRegistrationIdentifiersCheckSchemas = best.Value.(*ExtensionHookRegistrationIdentifiersCheckSchemas)
		return nil
	case HooksTypeExtensionHookContractIdentificationSchemas:
		u.ExtensionHookContractIdentificationSchemas = best.Value.(*ExtensionHookContractIdentificationSchemas)
		return nil
	case HooksTypeExtensionHookPriceDataRetrievalSchemas:
		u.ExtensionHookPriceDataRetrievalSchemas = best.Value.(*ExtensionHookPriceDataRetrievalSchemas)
		return nil
	case HooksTypeSchemas:
		u.Schemas = best.Value.(*Schemas)
		return nil
	case HooksTypeExtensionHookCostDataRetrievalSchemas:
		u.ExtensionHookCostDataRetrievalSchemas = best.Value.(*ExtensionHookCostDataRetrievalSchemas)
		return nil
	case HooksTypeExtensionHookMeterReadingPlausibilityCheckSchemas:
		u.ExtensionHookMeterReadingPlausibilityCheckSchemas = best.Value.(*ExtensionHookMeterReadingPlausibilityCheckSchemas)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Hooks", string(data))
}

func (u Hooks) MarshalJSON() ([]byte, error) {
	if u.ExtensionHookRegistrationIdentifiersCheckSchemas != nil {
		return utils.MarshalJSON(u.ExtensionHookRegistrationIdentifiersCheckSchemas, "", true)
	}

	if u.ExtensionHookContractIdentificationSchemas != nil {
		return utils.MarshalJSON(u.ExtensionHookContractIdentificationSchemas, "", true)
	}

	if u.ExtensionHookPriceDataRetrievalSchemas != nil {
		return utils.MarshalJSON(u.ExtensionHookPriceDataRetrievalSchemas, "", true)
	}

	if u.Schemas != nil {
		return utils.MarshalJSON(u.Schemas, "", true)
	}

	if u.ExtensionHookCostDataRetrievalSchemas != nil {
		return utils.MarshalJSON(u.ExtensionHookCostDataRetrievalSchemas, "", true)
	}

	if u.ExtensionHookMeterReadingPlausibilityCheckSchemas != nil {
		return utils.MarshalJSON(u.ExtensionHookMeterReadingPlausibilityCheckSchemas, "", true)
	}

	return nil, errors.New("could not marshal union type Hooks: all fields are null")
}

// Name of the extension.
type Name struct {
	AdditionalProperties map[string]string `additionalProperties:"true" json:"-"`
	// Name of the extension in English.
	En string `json:"en"`
}

func (n Name) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *Name) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (n *Name) GetAdditionalProperties() map[string]string {
	if n == nil {
		return nil
	}
	return n.AdditionalProperties
}

func (n *Name) GetEn() string {
	if n == nil {
		return ""
	}
	return n.En
}

// ExtensionDescription - Description of the option.
type ExtensionDescription struct {
	AdditionalProperties map[string]string `additionalProperties:"true" json:"-"`
	// Description of the option in English.
	En string `json:"en"`
}

func (e ExtensionDescription) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExtensionDescription) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ExtensionDescription) GetAdditionalProperties() map[string]string {
	if e == nil {
		return nil
	}
	return e.AdditionalProperties
}

func (e *ExtensionDescription) GetEn() string {
	if e == nil {
		return ""
	}
	return e.En
}

// ExtensionName - Name of the option.
type ExtensionName struct {
	AdditionalProperties map[string]string `additionalProperties:"true" json:"-"`
	// Name of the option in English.
	En string `json:"en"`
}

func (e ExtensionName) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExtensionName) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ExtensionName) GetAdditionalProperties() map[string]string {
	if e == nil {
		return nil
	}
	return e.AdditionalProperties
}

func (e *ExtensionName) GetEn() string {
	if e == nil {
		return ""
	}
	return e.En
}

// ExtensionType - Type of the option.
type ExtensionType string

const (
	ExtensionTypeText   ExtensionType = "text"
	ExtensionTypeSecret ExtensionType = "secret"
)

func (e ExtensionType) ToPointer() *ExtensionType {
	return &e
}
func (e *ExtensionType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "text":
		fallthrough
	case "secret":
		*e = ExtensionType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ExtensionType: %v", v)
	}
}

type OptionsObj struct {
	// Default value of the option.
	Default *string `json:"default,omitempty"`
	// Description of the option.
	Description *ExtensionDescription `json:"description,omitempty"`
	// Identifier of the option. Should not change between updates.
	ID string `json:"id"`
	// Name of the option.
	Name ExtensionName `json:"name"`
	// Indicate whether the option is required.
	Required *bool `default:"false" json:"required"`
	// Type of the option.
	Type ExtensionType `json:"type"`
}

func (o OptionsObj) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OptionsObj) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OptionsObj) GetDefault() *string {
	if o == nil {
		return nil
	}
	return o.Default
}

func (o *OptionsObj) GetDescription() *ExtensionDescription {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *OptionsObj) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *OptionsObj) GetName() ExtensionName {
	if o == nil {
		return ExtensionName{}
	}
	return o.Name
}

func (o *OptionsObj) GetRequired() *bool {
	if o == nil {
		return nil
	}
	return o.Required
}

func (o *OptionsObj) GetType() ExtensionType {
	if o == nil {
		return ExtensionType("")
	}
	return o.Type
}

type Extension struct {
	// Identifier of the app from which the extension was installed. Should not change between updates.
	AppID *string `json:"app_id,omitempty"`
	// Name of the app from which the extension was installed. Should not change between updates.
	AppName *string `json:"app_name,omitempty"`
	// Name of the extension.
	Description *Description `json:"description,omitempty"`
	// Hooks that influence the behavior of Portal.
	Hooks []Hooks `json:"hooks,omitempty"`
	// Identifier of the extension. Should not change between updates.
	ID string `json:"id"`
	// External links added to the portal.
	Links []ExtensionSeamlessLink `json:"links,omitempty"`
	// Name of the extension.
	Name Name `json:"name"`
	// Options available to the extension configurable by the portal administrator.
	Options []OptionsObj `json:"options,omitempty"`
	// Version of the extension.
	Version *string `json:"version,omitempty"`
}

func (e *Extension) GetAppID() *string {
	if e == nil {
		return nil
	}
	return e.AppID
}

func (e *Extension) GetAppName() *string {
	if e == nil {
		return nil
	}
	return e.AppName
}

func (e *Extension) GetDescription() *Description {
	if e == nil {
		return nil
	}
	return e.Description
}

func (e *Extension) GetHooks() []Hooks {
	if e == nil {
		return nil
	}
	return e.Hooks
}

func (e *Extension) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *Extension) GetLinks() []ExtensionSeamlessLink {
	if e == nil {
		return nil
	}
	return e.Links
}

func (e *Extension) GetName() Name {
	if e == nil {
		return Name{}
	}
	return e.Name
}

func (e *Extension) GetOptions() []OptionsObj {
	if e == nil {
		return nil
	}
	return e.Options
}

func (e *Extension) GetVersion() *string {
	if e == nil {
		return nil
	}
	return e.Version
}
