// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type OIDCProviderMetadata struct {
	// URL of the authorization endpoint
	AuthorizationEndpoint *string `json:"authorization_endpoint,omitempty"`
	// URL of the mobile redirect URI
	MobileRedirectURI *string `json:"mobile_redirect_uri,omitempty"`
	// URL of the token endpoint
	TokenEndpoint *string `json:"token_endpoint,omitempty"`
	// URL of the userinfo endpoint
	UserinfoEndpoint *string `json:"userinfo_endpoint,omitempty"`
}

func (o *OIDCProviderMetadata) GetAuthorizationEndpoint() *string {
	if o == nil {
		return nil
	}
	return o.AuthorizationEndpoint
}

func (o *OIDCProviderMetadata) GetMobileRedirectURI() *string {
	if o == nil {
		return nil
	}
	return o.MobileRedirectURI
}

func (o *OIDCProviderMetadata) GetTokenEndpoint() *string {
	if o == nil {
		return nil
	}
	return o.TokenEndpoint
}

func (o *OIDCProviderMetadata) GetUserinfoEndpoint() *string {
	if o == nil {
		return nil
	}
	return o.UserinfoEndpoint
}
