// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type AutomationEntityMapping struct {
	// Enable/Disable automation entity mapping
	Enabled *bool `json:"enabled,omitempty"`
}

func (a *AutomationEntityMapping) GetEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.Enabled
}

type AutomationPreview struct {
	// Enable/Disable automation preview
	Enabled *bool `json:"enabled,omitempty"`
}

func (a *AutomationPreview) GetEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.Enabled
}

type CentralInboxPreviewSetting struct {
	// Enable/Disable central inbox preview setting
	Enabled *bool `json:"enabled,omitempty"`
}

func (c *CentralInboxPreviewSetting) GetEnabled() *bool {
	if c == nil {
		return nil
	}
	return c.Enabled
}

type ContractsPreviewSetting struct {
	// Enable/Disable contracts preview setting
	Enabled *bool `json:"enabled,omitempty"`
}

func (c *ContractsPreviewSetting) GetEnabled() *bool {
	if c == nil {
		return nil
	}
	return c.Enabled
}

type DisableIvy struct {
	// Enable/Disable Ivy
	Enabled *bool `json:"enabled,omitempty"`
}

func (d *DisableIvy) GetEnabled() *bool {
	if d == nil {
		return nil
	}
	return d.Enabled
}

type DoubleOptIn struct {
	// Enable/Disable double opt-in
	Enabled *bool `json:"enabled,omitempty"`
}

func (d *DoubleOptIn) GetEnabled() *bool {
	if d == nil {
		return nil
	}
	return d.Enabled
}

type EcommerceCatalogPreview struct {
	// Enable/Disable ecommerce catalog preview
	Enabled *bool `json:"enabled,omitempty"`
}

func (e *EcommerceCatalogPreview) GetEnabled() *bool {
	if e == nil {
		return nil
	}
	return e.Enabled
}

type EcommerceOpportunitiesPreview struct {
	// Enable/Disable ecommerce opportunities preview
	Enabled *bool `json:"enabled,omitempty"`
}

func (e *EcommerceOpportunitiesPreview) GetEnabled() *bool {
	if e == nil {
		return nil
	}
	return e.Enabled
}

type EcommercePreview struct {
	// Enable/Disable ecommerce preview
	Enabled *bool `json:"enabled,omitempty"`
}

func (e *EcommercePreview) GetEnabled() *bool {
	if e == nil {
		return nil
	}
	return e.Enabled
}

type EndCustomerPortal struct {
	// Enable/Disable end customer portal
	Enabled *bool `json:"enabled,omitempty"`
}

func (e *EndCustomerPortal) GetEnabled() *bool {
	if e == nil {
		return nil
	}
	return e.Enabled
}

type EntitySchemaBuilder struct {
	// Enable/Disable entity schema builder
	Enabled *bool `json:"enabled,omitempty"`
}

func (e *EntitySchemaBuilder) GetEnabled() *bool {
	if e == nil {
		return nil
	}
	return e.Enabled
}

type InstallerPortal struct {
	// Enable/Disable installer portal
	Enabled *bool `json:"enabled,omitempty"`
}

func (i *InstallerPortal) GetEnabled() *bool {
	if i == nil {
		return nil
	}
	return i.Enabled
}

type LogicEditorPreview struct {
	// Enable/Disable logic editor preview
	Enabled *bool `json:"enabled,omitempty"`
}

func (l *LogicEditorPreview) GetEnabled() *bool {
	if l == nil {
		return nil
	}
	return l.Enabled
}

type NewNavigation struct {
	// Enable/Disable new navigation
	Enabled *bool `json:"enabled,omitempty"`
}

func (n *NewNavigation) GetEnabled() *bool {
	if n == nil {
		return nil
	}
	return n.Enabled
}

type Partnering struct {
	// Enable/Disable partnering
	Enabled *bool `json:"enabled,omitempty"`
}

func (p *Partnering) GetEnabled() *bool {
	if p == nil {
		return nil
	}
	return p.Enabled
}

type ProductAvailability struct {
	// Enable/Disable product availability
	Enabled *bool `json:"enabled,omitempty"`
}

func (p *ProductAvailability) GetEnabled() *bool {
	if p == nil {
		return nil
	}
	return p.Enabled
}

type Sso struct {
	// Enable/Disable single sign-on (SSO)
	Enabled *bool `json:"enabled,omitempty"`
}

func (s *Sso) GetEnabled() *bool {
	if s == nil {
		return nil
	}
	return s.Enabled
}

type SubmissionPreview struct {
	// Enable/Disable submission preview
	Enabled *bool `json:"enabled,omitempty"`
}

func (s *SubmissionPreview) GetEnabled() *bool {
	if s == nil {
		return nil
	}
	return s.Enabled
}

type UserRolesPreview struct {
	// Enable/Disable user roles preview
	Enabled *bool `json:"enabled,omitempty"`
}

func (u *UserRolesPreview) GetEnabled() *bool {
	if u == nil {
		return nil
	}
	return u.Enabled
}

type OrganizationSettings struct {
	AutomationEntityMapping       *AutomationEntityMapping       `json:"automation_entity_mapping,omitempty"`
	AutomationPreview             *AutomationPreview             `json:"automation_preview,omitempty"`
	CentralInboxPreviewSetting    *CentralInboxPreviewSetting    `json:"central_inbox_preview_setting,omitempty"`
	ContractsPreviewSetting       *ContractsPreviewSetting       `json:"contracts_preview_setting,omitempty"`
	DisableIvy                    *DisableIvy                    `json:"disable_ivy,omitempty"`
	DoubleOptIn                   *DoubleOptIn                   `json:"double_opt_in,omitempty"`
	EcommerceCatalogPreview       *EcommerceCatalogPreview       `json:"ecommerce_catalog_preview,omitempty"`
	EcommerceOpportunitiesPreview *EcommerceOpportunitiesPreview `json:"ecommerce_opportunities_preview,omitempty"`
	EcommercePreview              *EcommercePreview              `json:"ecommerce_preview,omitempty"`
	EndCustomerPortal             *EndCustomerPortal             `json:"end_customer_portal,omitempty"`
	EntitySchemaBuilder           *EntitySchemaBuilder           `json:"entity_schema_builder,omitempty"`
	InstallerPortal               *InstallerPortal               `json:"installer_portal,omitempty"`
	LogicEditorPreview            *LogicEditorPreview            `json:"logic_editor_preview,omitempty"`
	NewNavigation                 *NewNavigation                 `json:"new_navigation,omitempty"`
	Partnering                    *Partnering                    `json:"partnering,omitempty"`
	ProductAvailability           *ProductAvailability           `json:"product-availability,omitempty"`
	Sso                           *Sso                           `json:"sso,omitempty"`
	SubmissionPreview             *SubmissionPreview             `json:"submission_preview,omitempty"`
	UserRolesPreview              *UserRolesPreview              `json:"user_roles_preview,omitempty"`
}

func (o *OrganizationSettings) GetAutomationEntityMapping() *AutomationEntityMapping {
	if o == nil {
		return nil
	}
	return o.AutomationEntityMapping
}

func (o *OrganizationSettings) GetAutomationPreview() *AutomationPreview {
	if o == nil {
		return nil
	}
	return o.AutomationPreview
}

func (o *OrganizationSettings) GetCentralInboxPreviewSetting() *CentralInboxPreviewSetting {
	if o == nil {
		return nil
	}
	return o.CentralInboxPreviewSetting
}

func (o *OrganizationSettings) GetContractsPreviewSetting() *ContractsPreviewSetting {
	if o == nil {
		return nil
	}
	return o.ContractsPreviewSetting
}

func (o *OrganizationSettings) GetDisableIvy() *DisableIvy {
	if o == nil {
		return nil
	}
	return o.DisableIvy
}

func (o *OrganizationSettings) GetDoubleOptIn() *DoubleOptIn {
	if o == nil {
		return nil
	}
	return o.DoubleOptIn
}

func (o *OrganizationSettings) GetEcommerceCatalogPreview() *EcommerceCatalogPreview {
	if o == nil {
		return nil
	}
	return o.EcommerceCatalogPreview
}

func (o *OrganizationSettings) GetEcommerceOpportunitiesPreview() *EcommerceOpportunitiesPreview {
	if o == nil {
		return nil
	}
	return o.EcommerceOpportunitiesPreview
}

func (o *OrganizationSettings) GetEcommercePreview() *EcommercePreview {
	if o == nil {
		return nil
	}
	return o.EcommercePreview
}

func (o *OrganizationSettings) GetEndCustomerPortal() *EndCustomerPortal {
	if o == nil {
		return nil
	}
	return o.EndCustomerPortal
}

func (o *OrganizationSettings) GetEntitySchemaBuilder() *EntitySchemaBuilder {
	if o == nil {
		return nil
	}
	return o.EntitySchemaBuilder
}

func (o *OrganizationSettings) GetInstallerPortal() *InstallerPortal {
	if o == nil {
		return nil
	}
	return o.InstallerPortal
}

func (o *OrganizationSettings) GetLogicEditorPreview() *LogicEditorPreview {
	if o == nil {
		return nil
	}
	return o.LogicEditorPreview
}

func (o *OrganizationSettings) GetNewNavigation() *NewNavigation {
	if o == nil {
		return nil
	}
	return o.NewNavigation
}

func (o *OrganizationSettings) GetPartnering() *Partnering {
	if o == nil {
		return nil
	}
	return o.Partnering
}

func (o *OrganizationSettings) GetProductAvailability() *ProductAvailability {
	if o == nil {
		return nil
	}
	return o.ProductAvailability
}

func (o *OrganizationSettings) GetSso() *Sso {
	if o == nil {
		return nil
	}
	return o.Sso
}

func (o *OrganizationSettings) GetSubmissionPreview() *SubmissionPreview {
	if o == nil {
		return nil
	}
	return o.SubmissionPreview
}

func (o *OrganizationSettings) GetUserRolesPreview() *UserRolesPreview {
	if o == nil {
		return nil
	}
	return o.UserRolesPreview
}
