// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type PortalConfigV3AdvancedMfa struct {
	// Advanced MFA feature flag
	Enabled *bool `json:"enabled,omitempty"`
}

func (p *PortalConfigV3AdvancedMfa) GetEnabled() *bool {
	if p == nil {
		return nil
	}
	return p.Enabled
}

type PortalConfigV3EntryPoint string

const (
	PortalConfigV3EntryPointPassword PortalConfigV3EntryPoint = "PASSWORD"
	PortalConfigV3EntryPointSso      PortalConfigV3EntryPoint = "SSO"
)

func (e PortalConfigV3EntryPoint) ToPointer() *PortalConfigV3EntryPoint {
	return &e
}
func (e *PortalConfigV3EntryPoint) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PASSWORD":
		fallthrough
	case "SSO":
		*e = PortalConfigV3EntryPoint(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PortalConfigV3EntryPoint: %v", v)
	}
}

type PortalConfigV3PasswordlessLogin struct {
	// Passwordless login feature flag
	Enabled *bool `json:"enabled,omitempty"`
}

func (p *PortalConfigV3PasswordlessLogin) GetEnabled() *bool {
	if p == nil {
		return nil
	}
	return p.Enabled
}

// PortalConfigV3AuthSettings - Authentication settings for the portal
type PortalConfigV3AuthSettings struct {
	// Decide whether to automatically redirect to the provider page during login, which would completely bypass showing the portal authentication page.
	AutoRedirectToSso     *bool                            `json:"auto_redirect_to_sso,omitempty"`
	EntryPoint            *PortalConfigV3EntryPoint        `json:"entry_point,omitempty"`
	PasswordlessLogin     *PortalConfigV3PasswordlessLogin `json:"passwordless_login,omitempty"`
	PreferredSsoProviders []string                         `json:"preferred_sso_providers,omitempty"`
}

func (p *PortalConfigV3AuthSettings) GetAutoRedirectToSso() *bool {
	if p == nil {
		return nil
	}
	return p.AutoRedirectToSso
}

func (p *PortalConfigV3AuthSettings) GetEntryPoint() *PortalConfigV3EntryPoint {
	if p == nil {
		return nil
	}
	return p.EntryPoint
}

func (p *PortalConfigV3AuthSettings) GetPasswordlessLogin() *PortalConfigV3PasswordlessLogin {
	if p == nil {
		return nil
	}
	return p.PasswordlessLogin
}

func (p *PortalConfigV3AuthSettings) GetPreferredSsoProviders() []string {
	if p == nil {
		return nil
	}
	return p.PreferredSsoProviders
}

// PortalConfigV3PasswordPolicy - Password policy for the portal
type PortalConfigV3PasswordPolicy struct {
	// Maximum password length
	MaximumLength *int64 `json:"maximum_length,omitempty"`
	// Minimum password length
	MinimumLength *int64 `json:"minimum_length,omitempty"`
	// Require lowercase characters
	RequireLowercase *bool `json:"require_lowercase,omitempty"`
	// Require numbers
	RequireNumbers *bool `json:"require_numbers,omitempty"`
	// Require symbols
	RequireSymbols *bool `json:"require_symbols,omitempty"`
	// Require uppercase characters
	RequireUppercase *bool `json:"require_uppercase,omitempty"`
}

func (p *PortalConfigV3PasswordPolicy) GetMaximumLength() *int64 {
	if p == nil {
		return nil
	}
	return p.MaximumLength
}

func (p *PortalConfigV3PasswordPolicy) GetMinimumLength() *int64 {
	if p == nil {
		return nil
	}
	return p.MinimumLength
}

func (p *PortalConfigV3PasswordPolicy) GetRequireLowercase() *bool {
	if p == nil {
		return nil
	}
	return p.RequireLowercase
}

func (p *PortalConfigV3PasswordPolicy) GetRequireNumbers() *bool {
	if p == nil {
		return nil
	}
	return p.RequireNumbers
}

func (p *PortalConfigV3PasswordPolicy) GetRequireSymbols() *bool {
	if p == nil {
		return nil
	}
	return p.RequireSymbols
}

func (p *PortalConfigV3PasswordPolicy) GetRequireUppercase() *bool {
	if p == nil {
		return nil
	}
	return p.RequireUppercase
}

// PortalConfigV3CognitoDetails - AWS Cognito Pool details for the portal
type PortalConfigV3CognitoDetails struct {
	// Cognito user pool ARN
	CognitoUserPoolArn *string `json:"cognito_user_pool_arn,omitempty"`
	// Cognito user pool client ID
	CognitoUserPoolClientID *string `json:"cognito_user_pool_client_id,omitempty"`
	// Cognito user pool ID
	CognitoUserPoolID *string `json:"cognito_user_pool_id,omitempty"`
	// Password policy for the portal
	PasswordPolicy *PortalConfigV3PasswordPolicy `json:"password_policy,omitempty"`
}

func (p *PortalConfigV3CognitoDetails) GetCognitoUserPoolArn() *string {
	if p == nil {
		return nil
	}
	return p.CognitoUserPoolArn
}

func (p *PortalConfigV3CognitoDetails) GetCognitoUserPoolClientID() *string {
	if p == nil {
		return nil
	}
	return p.CognitoUserPoolClientID
}

func (p *PortalConfigV3CognitoDetails) GetCognitoUserPoolID() *string {
	if p == nil {
		return nil
	}
	return p.CognitoUserPoolID
}

func (p *PortalConfigV3CognitoDetails) GetPasswordPolicy() *PortalConfigV3PasswordPolicy {
	if p == nil {
		return nil
	}
	return p.PasswordPolicy
}

// PortalConfigV3ContractSelectorConfig - Configuration for contract selector in the portal
type PortalConfigV3ContractSelectorConfig struct {
	// Whether to show inactive contracts in the selector
	ShowInactive *bool `json:"show_inactive,omitempty"`
	// Path to the property to use as the contract title
	TitlePath *string `json:"title_path,omitempty"`
}

func (p *PortalConfigV3ContractSelectorConfig) GetShowInactive() *bool {
	if p == nil {
		return nil
	}
	return p.ShowInactive
}

func (p *PortalConfigV3ContractSelectorConfig) GetTitlePath() *string {
	if p == nil {
		return nil
	}
	return p.TitlePath
}

// DefaultUserToNotify - Default 360 user to notify upon an internal notification
type DefaultUserToNotify struct {
	// Default admin users for pending user notification to notify
	OnPendingUser []AdminUser `json:"onPendingUser,omitempty"`
}

func (d *DefaultUserToNotify) GetOnPendingUser() []AdminUser {
	if d == nil {
		return nil
	}
	return d.OnPendingUser
}

type PortalConfigV3ActionLabel struct {
	De *string `json:"de,omitempty"`
	En *string `json:"en,omitempty"`
}

func (p *PortalConfigV3ActionLabel) GetDe() *string {
	if p == nil {
		return nil
	}
	return p.De
}

func (p *PortalConfigV3ActionLabel) GetEn() *string {
	if p == nil {
		return nil
	}
	return p.En
}

type EntityActions struct {
	ActionLabel *PortalConfigV3ActionLabel `json:"action_Label,omitempty"`
	// Entity ID
	JourneyID *string `json:"journey_id,omitempty"`
	// URL-friendly identifier for the entity schema
	Slug *string `json:"slug,omitempty"`
}

func (e *EntityActions) GetActionLabel() *PortalConfigV3ActionLabel {
	if e == nil {
		return nil
	}
	return e.ActionLabel
}

func (e *EntityActions) GetJourneyID() *string {
	if e == nil {
		return nil
	}
	return e.JourneyID
}

func (e *EntityActions) GetSlug() *string {
	if e == nil {
		return nil
	}
	return e.Slug
}

type PortalConfigV3Type struct {
	// Attributes used to identify an entity
	Attributes []string `json:"attributes,omitempty"`
	// Enable/Disable the entity identifier
	IsEnabled *bool `json:"isEnabled,omitempty"`
}

func (p *PortalConfigV3Type) GetAttributes() []string {
	if p == nil {
		return nil
	}
	return p.Attributes
}

func (p *PortalConfigV3Type) GetIsEnabled() *bool {
	if p == nil {
		return nil
	}
	return p.IsEnabled
}

// PortalConfigV3EntityIdentifiers - Identifiers used to identify an entity by a portal user. Deprecated. Use contract_identifiers instead.
//
// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
type PortalConfigV3EntityIdentifiers struct {
	Type *PortalConfigV3Type `json:"type,omitempty"`
}

func (p *PortalConfigV3EntityIdentifiers) GetType() *PortalConfigV3Type {
	if p == nil {
		return nil
	}
	return p.Type
}

// PortalConfigV3FeatureSettings - Feature settings for the portal
type PortalConfigV3FeatureSettings struct {
	// Billing feature flag
	Billing *bool `json:"billing,omitempty"`
	// Change due date feature flag
	ChangeDueDate *bool `json:"change_due_date,omitempty"`
	// Enable or disable the new design for the portal
	NewDesign *bool `json:"new_design,omitempty"`
	// Start page feature flag
	StartPage *bool `json:"start_page,omitempty"`
}

func (p *PortalConfigV3FeatureSettings) GetBilling() *bool {
	if p == nil {
		return nil
	}
	return p.Billing
}

func (p *PortalConfigV3FeatureSettings) GetChangeDueDate() *bool {
	if p == nil {
		return nil
	}
	return p.ChangeDueDate
}

func (p *PortalConfigV3FeatureSettings) GetNewDesign() *bool {
	if p == nil {
		return nil
	}
	return p.NewDesign
}

func (p *PortalConfigV3FeatureSettings) GetStartPage() *bool {
	if p == nil {
		return nil
	}
	return p.StartPage
}

// PortalConfigV3Images - Teaser & Banner Image web links
type PortalConfigV3Images struct {
	// URL of the order left teaser image
	OrderLeftTeaser *string `json:"orderLeftTeaser,omitempty"`
	// URL of the order right teaser image
	OrderRightTeaser *string `json:"orderRightTeaser,omitempty"`
	// URL of the welcome banner image
	WelcomeBanner *string `json:"welcomeBanner,omitempty"`
}

func (p *PortalConfigV3Images) GetOrderLeftTeaser() *string {
	if p == nil {
		return nil
	}
	return p.OrderLeftTeaser
}

func (p *PortalConfigV3Images) GetOrderRightTeaser() *string {
	if p == nil {
		return nil
	}
	return p.OrderRightTeaser
}

func (p *PortalConfigV3Images) GetWelcomeBanner() *string {
	if p == nil {
		return nil
	}
	return p.WelcomeBanner
}

// PortalConfigV3Canary - Canary feature flag
type PortalConfigV3Canary struct {
	// Enable/Disable the canary feature
	Enabled *bool `json:"enabled,omitempty"`
}

func (p *PortalConfigV3Canary) GetEnabled() *bool {
	if p == nil {
		return nil
	}
	return p.Enabled
}

// PortalConfigV3Notracking - Disable Advanced Usage Metrics
type PortalConfigV3Notracking struct {
	// Disable browser-side scripts that track advanced usage metrics
	Enabled *bool `json:"enabled,omitempty"`
}

func (p *PortalConfigV3Notracking) GetEnabled() *bool {
	if p == nil {
		return nil
	}
	return p.Enabled
}

// PortalConfigV3OrgSettings - Organization settings
type PortalConfigV3OrgSettings struct {
	// Canary feature flag
	Canary *PortalConfigV3Canary `json:"canary,omitempty"`
	// Disable Advanced Usage Metrics
	Notracking *PortalConfigV3Notracking `json:"notracking,omitempty"`
}

func (p *PortalConfigV3OrgSettings) GetCanary() *PortalConfigV3Canary {
	if p == nil {
		return nil
	}
	return p.Canary
}

func (p *PortalConfigV3OrgSettings) GetNotracking() *PortalConfigV3Notracking {
	if p == nil {
		return nil
	}
	return p.Notracking
}

type PortalConfigV3SelfRegistrationSetting string

const (
	PortalConfigV3SelfRegistrationSettingAllowWithContactCreation    PortalConfigV3SelfRegistrationSetting = "ALLOW_WITH_CONTACT_CREATION"
	PortalConfigV3SelfRegistrationSettingAllowWithoutContactCreation PortalConfigV3SelfRegistrationSetting = "ALLOW_WITHOUT_CONTACT_CREATION"
	PortalConfigV3SelfRegistrationSettingDeny                        PortalConfigV3SelfRegistrationSetting = "DENY"
	PortalConfigV3SelfRegistrationSettingAlwaysCreateContact         PortalConfigV3SelfRegistrationSetting = "ALWAYS_CREATE_CONTACT"
	PortalConfigV3SelfRegistrationSettingDisallowCompletely          PortalConfigV3SelfRegistrationSetting = "DISALLOW_COMPLETELY"
	PortalConfigV3SelfRegistrationSettingBlockIfPortalUserExists     PortalConfigV3SelfRegistrationSetting = "BLOCK_IF_PORTAL_USER_EXISTS"
)

func (e PortalConfigV3SelfRegistrationSetting) ToPointer() *PortalConfigV3SelfRegistrationSetting {
	return &e
}
func (e *PortalConfigV3SelfRegistrationSetting) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ALLOW_WITH_CONTACT_CREATION":
		fallthrough
	case "ALLOW_WITHOUT_CONTACT_CREATION":
		fallthrough
	case "DENY":
		fallthrough
	case "ALWAYS_CREATE_CONTACT":
		fallthrough
	case "DISALLOW_COMPLETELY":
		fallthrough
	case "BLOCK_IF_PORTAL_USER_EXISTS":
		*e = PortalConfigV3SelfRegistrationSetting(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PortalConfigV3SelfRegistrationSetting: %v", v)
	}
}

type PortalConfigV3TriggerName string

const (
	PortalConfigV3TriggerNameFirstLogin   PortalConfigV3TriggerName = "FIRST_LOGIN"
	PortalConfigV3TriggerNameAcceptOrder  PortalConfigV3TriggerName = "ACCEPT_ORDER"
	PortalConfigV3TriggerNameDeclineOrder PortalConfigV3TriggerName = "DECLINE_ORDER"
)

func (e PortalConfigV3TriggerName) ToPointer() *PortalConfigV3TriggerName {
	return &e
}
func (e *PortalConfigV3TriggerName) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "FIRST_LOGIN":
		fallthrough
	case "ACCEPT_ORDER":
		fallthrough
	case "DECLINE_ORDER":
		*e = PortalConfigV3TriggerName(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PortalConfigV3TriggerName: %v", v)
	}
}

type PortalConfigV3TriggeredJourneys struct {
	// Entity ID
	JourneyID   *string                    `json:"journey_id,omitempty"`
	TriggerName *PortalConfigV3TriggerName `json:"trigger_name,omitempty"`
}

func (p *PortalConfigV3TriggeredJourneys) GetJourneyID() *string {
	if p == nil {
		return nil
	}
	return p.JourneyID
}

func (p *PortalConfigV3TriggeredJourneys) GetTriggerName() *PortalConfigV3TriggerName {
	if p == nil {
		return nil
	}
	return p.TriggerName
}

type PortalConfigV3 struct {
	// Access token for the portal
	AccessToken *string                    `json:"accessToken,omitempty"`
	AdvancedMfa *PortalConfigV3AdvancedMfa `json:"advanced_mfa,omitempty"`
	// Allowed file extensions for upload
	AllowedFileExtensions   *AllowedFileExtensions `json:"allowed_file_extensions,omitempty"`
	ApprovalStateAttributes any                    `json:"approval_state_attributes,omitempty"`
	// Authentication settings for the portal
	AuthSettings *PortalConfigV3AuthSettings `json:"auth_settings,omitempty"`
	// AWS Cognito Pool details for the portal
	CognitoDetails *PortalConfigV3CognitoDetails `json:"cognito_details,omitempty"`
	// Stringified object with configuration details
	Config *string `json:"config,omitempty"`
	// Deprecated. Use registration_identifiers instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	ContactIdentifiers []string `json:"contact_identifiers,omitempty"`
	// Identifiers to identify a contract by a portal user.
	ContractIdentifiers any `json:"contract_identifiers,omitempty"`
	// Configuration for contract selector in the portal
	ContractSelectorConfig *PortalConfigV3ContractSelectorConfig `json:"contract_selector_config,omitempty"`
	// Default 360 user to notify upon an internal notification
	DefaultUserToNotify *DefaultUserToNotify `json:"default_user_to_notify,omitempty"`
	// Entity ID
	DesignID *string `json:"design_id,omitempty"`
	// The URL on which the portal is accessible
	Domain *string `json:"domain,omitempty"`
	// Email templates used for authentication and internal processes
	EmailTemplates *EmailTemplates `json:"email_templates,omitempty"`
	// Enable/Disable the portal access
	Enabled *bool `json:"enabled,omitempty"`
	// Journey actions allowed on an entity by a portal user
	EntityActions []EntityActions `json:"entity_actions,omitempty"`
	// Rules for editing an entity by a portal user
	EntityEditRules any `json:"entity_edit_rules,omitempty"`
	// Identifiers used to identify an entity by a portal user. Deprecated. Use contract_identifiers instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	EntityIdentifiers *PortalConfigV3EntityIdentifiers `json:"entity_identifiers,omitempty"`
	// Configured Portal extensions hooks
	ExtensionHooks map[string]*ExtensionHookSelection `json:"extension_hooks,omitempty"`
	// Configured Portal extensions
	Extensions []ExtensionConfig `json:"extensions,omitempty"`
	// Feature flags for the portal
	FeatureFlags any `json:"feature_flags,omitempty"`
	// Feature settings for the portal
	FeatureSettings *PortalConfigV3FeatureSettings `json:"feature_settings,omitempty"`
	// Permissions granted to a portal user while accessing entities
	Grants            any `json:"grants,omitempty"`
	IdentityProviders any `json:"identity_providers,omitempty"`
	// Teaser & Banner Image web links
	Images *PortalConfigV3Images `json:"images,omitempty"`
	// Number of years to look back for showing inactive contracts in the portal
	InactiveContractCutoffYears *float64 `json:"inactive_contract_cutoff_years,omitempty"`
	// Whether this is a dummy/test portal configuration
	IsDummy *bool `json:"is_dummy,omitempty"`
	// Mark true if the domain is an Epilot domain
	IsEpilotDomain *bool `json:"is_epilot_domain,omitempty"`
	// Whether this is a v3 portal configuration
	IsV3Item *bool `json:"is_v3_item,omitempty"`
	// Grace period in days for meter readings
	MeterReadingGracePeriod *float64 `json:"meter_reading_grace_period,omitempty"`
	// A short name to identify your portal
	Name *string `json:"name,omitempty"`
	// Organization settings
	OrgSettings *PortalConfigV3OrgSettings `json:"org_settings,omitempty"`
	// ID of the organization
	OrganizationID *string `json:"organization_id,omitempty"`
	// Origin of the portal
	Origin *string `json:"origin,omitempty"`
	Pages  any     `json:"pages,omitempty"`
	// ID of the portal
	PortalID *string `json:"portal_id,omitempty"`
	// Key of the portal config
	PortalSkV3 *string `json:"portal_sk_v3,omitempty"`
	// Prevent indexing by search engines
	PreventSearchEngineIndexing *bool `json:"prevent_search_engine_indexing,omitempty"`
	// Identifiers to identify a contact of a portal user during the registration.
	RegistrationIdentifiers any                                    `json:"registration_identifiers,omitempty"`
	SelfRegistrationSetting *PortalConfigV3SelfRegistrationSetting `json:"self_registration_setting,omitempty"`
	// Journeys automatically opened on a portal user action
	TriggeredJourneys []PortalConfigV3TriggeredJourneys `json:"triggered_journeys,omitempty"`
	// Enable or disable user account self management
	UserAccountSelfManagement *bool `json:"user_account_self_management,omitempty"`
}

func (p *PortalConfigV3) GetAccessToken() *string {
	if p == nil {
		return nil
	}
	return p.AccessToken
}

func (p *PortalConfigV3) GetAdvancedMfa() *PortalConfigV3AdvancedMfa {
	if p == nil {
		return nil
	}
	return p.AdvancedMfa
}

func (p *PortalConfigV3) GetAllowedFileExtensions() *AllowedFileExtensions {
	if p == nil {
		return nil
	}
	return p.AllowedFileExtensions
}

func (p *PortalConfigV3) GetApprovalStateAttributes() any {
	if p == nil {
		return nil
	}
	return p.ApprovalStateAttributes
}

func (p *PortalConfigV3) GetAuthSettings() *PortalConfigV3AuthSettings {
	if p == nil {
		return nil
	}
	return p.AuthSettings
}

func (p *PortalConfigV3) GetCognitoDetails() *PortalConfigV3CognitoDetails {
	if p == nil {
		return nil
	}
	return p.CognitoDetails
}

func (p *PortalConfigV3) GetConfig() *string {
	if p == nil {
		return nil
	}
	return p.Config
}

func (p *PortalConfigV3) GetContactIdentifiers() []string {
	if p == nil {
		return nil
	}
	return p.ContactIdentifiers
}

func (p *PortalConfigV3) GetContractIdentifiers() any {
	if p == nil {
		return nil
	}
	return p.ContractIdentifiers
}

func (p *PortalConfigV3) GetContractSelectorConfig() *PortalConfigV3ContractSelectorConfig {
	if p == nil {
		return nil
	}
	return p.ContractSelectorConfig
}

func (p *PortalConfigV3) GetDefaultUserToNotify() *DefaultUserToNotify {
	if p == nil {
		return nil
	}
	return p.DefaultUserToNotify
}

func (p *PortalConfigV3) GetDesignID() *string {
	if p == nil {
		return nil
	}
	return p.DesignID
}

func (p *PortalConfigV3) GetDomain() *string {
	if p == nil {
		return nil
	}
	return p.Domain
}

func (p *PortalConfigV3) GetEmailTemplates() *EmailTemplates {
	if p == nil {
		return nil
	}
	return p.EmailTemplates
}

func (p *PortalConfigV3) GetEnabled() *bool {
	if p == nil {
		return nil
	}
	return p.Enabled
}

func (p *PortalConfigV3) GetEntityActions() []EntityActions {
	if p == nil {
		return nil
	}
	return p.EntityActions
}

func (p *PortalConfigV3) GetEntityEditRules() any {
	if p == nil {
		return nil
	}
	return p.EntityEditRules
}

func (p *PortalConfigV3) GetEntityIdentifiers() *PortalConfigV3EntityIdentifiers {
	if p == nil {
		return nil
	}
	return p.EntityIdentifiers
}

func (p *PortalConfigV3) GetExtensionHooks() map[string]*ExtensionHookSelection {
	if p == nil {
		return nil
	}
	return p.ExtensionHooks
}

func (p *PortalConfigV3) GetExtensions() []ExtensionConfig {
	if p == nil {
		return nil
	}
	return p.Extensions
}

func (p *PortalConfigV3) GetFeatureFlags() any {
	if p == nil {
		return nil
	}
	return p.FeatureFlags
}

func (p *PortalConfigV3) GetFeatureSettings() *PortalConfigV3FeatureSettings {
	if p == nil {
		return nil
	}
	return p.FeatureSettings
}

func (p *PortalConfigV3) GetGrants() any {
	if p == nil {
		return nil
	}
	return p.Grants
}

func (p *PortalConfigV3) GetIdentityProviders() any {
	if p == nil {
		return nil
	}
	return p.IdentityProviders
}

func (p *PortalConfigV3) GetImages() *PortalConfigV3Images {
	if p == nil {
		return nil
	}
	return p.Images
}

func (p *PortalConfigV3) GetInactiveContractCutoffYears() *float64 {
	if p == nil {
		return nil
	}
	return p.InactiveContractCutoffYears
}

func (p *PortalConfigV3) GetIsDummy() *bool {
	if p == nil {
		return nil
	}
	return p.IsDummy
}

func (p *PortalConfigV3) GetIsEpilotDomain() *bool {
	if p == nil {
		return nil
	}
	return p.IsEpilotDomain
}

func (p *PortalConfigV3) GetIsV3Item() *bool {
	if p == nil {
		return nil
	}
	return p.IsV3Item
}

func (p *PortalConfigV3) GetMeterReadingGracePeriod() *float64 {
	if p == nil {
		return nil
	}
	return p.MeterReadingGracePeriod
}

func (p *PortalConfigV3) GetName() *string {
	if p == nil {
		return nil
	}
	return p.Name
}

func (p *PortalConfigV3) GetOrgSettings() *PortalConfigV3OrgSettings {
	if p == nil {
		return nil
	}
	return p.OrgSettings
}

func (p *PortalConfigV3) GetOrganizationID() *string {
	if p == nil {
		return nil
	}
	return p.OrganizationID
}

func (p *PortalConfigV3) GetOrigin() *string {
	if p == nil {
		return nil
	}
	return p.Origin
}

func (p *PortalConfigV3) GetPages() any {
	if p == nil {
		return nil
	}
	return p.Pages
}

func (p *PortalConfigV3) GetPortalID() *string {
	if p == nil {
		return nil
	}
	return p.PortalID
}

func (p *PortalConfigV3) GetPortalSkV3() *string {
	if p == nil {
		return nil
	}
	return p.PortalSkV3
}

func (p *PortalConfigV3) GetPreventSearchEngineIndexing() *bool {
	if p == nil {
		return nil
	}
	return p.PreventSearchEngineIndexing
}

func (p *PortalConfigV3) GetRegistrationIdentifiers() any {
	if p == nil {
		return nil
	}
	return p.RegistrationIdentifiers
}

func (p *PortalConfigV3) GetSelfRegistrationSetting() *PortalConfigV3SelfRegistrationSetting {
	if p == nil {
		return nil
	}
	return p.SelfRegistrationSetting
}

func (p *PortalConfigV3) GetTriggeredJourneys() []PortalConfigV3TriggeredJourneys {
	if p == nil {
		return nil
	}
	return p.TriggeredJourneys
}

func (p *PortalConfigV3) GetUserAccountSelfManagement() *bool {
	if p == nil {
		return nil
	}
	return p.UserAccountSelfManagement
}
