// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/internal/utils"
)

type RoleType string

const (
	RoleTypeUserRole    RoleType = "UserRole"
	RoleTypeOrgRole     RoleType = "OrgRole"
	RoleTypeShareRole   RoleType = "ShareRole"
	RoleTypePartnerRole RoleType = "PartnerRole"
	RoleTypePortalRole  RoleType = "PortalRole"
)

type Role struct {
	UserRole    *UserRole    `queryParam:"inline" union:"member"`
	OrgRole     *OrgRole     `queryParam:"inline" union:"member"`
	ShareRole   *ShareRole   `queryParam:"inline" union:"member"`
	PartnerRole *PartnerRole `queryParam:"inline" union:"member"`
	PortalRole  *PortalRole  `queryParam:"inline" union:"member"`

	Type RoleType
}

func CreateRoleUserRole(userRole UserRole) Role {
	typ := RoleTypeUserRole

	return Role{
		UserRole: &userRole,
		Type:     typ,
	}
}

func CreateRoleOrgRole(orgRole OrgRole) Role {
	typ := RoleTypeOrgRole

	return Role{
		OrgRole: &orgRole,
		Type:    typ,
	}
}

func CreateRoleShareRole(shareRole ShareRole) Role {
	typ := RoleTypeShareRole

	return Role{
		ShareRole: &shareRole,
		Type:      typ,
	}
}

func CreateRolePartnerRole(partnerRole PartnerRole) Role {
	typ := RoleTypePartnerRole

	return Role{
		PartnerRole: &partnerRole,
		Type:        typ,
	}
}

func CreateRolePortalRole(portalRole PortalRole) Role {
	typ := RoleTypePortalRole

	return Role{
		PortalRole: &portalRole,
		Type:       typ,
	}
}

func (u *Role) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var userRole UserRole = UserRole{}
	if err := utils.UnmarshalJSON(data, &userRole, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  RoleTypeUserRole,
			Value: &userRole,
		})
	}

	var orgRole OrgRole = OrgRole{}
	if err := utils.UnmarshalJSON(data, &orgRole, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  RoleTypeOrgRole,
			Value: &orgRole,
		})
	}

	var shareRole ShareRole = ShareRole{}
	if err := utils.UnmarshalJSON(data, &shareRole, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  RoleTypeShareRole,
			Value: &shareRole,
		})
	}

	var partnerRole PartnerRole = PartnerRole{}
	if err := utils.UnmarshalJSON(data, &partnerRole, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  RoleTypePartnerRole,
			Value: &partnerRole,
		})
	}

	var portalRole PortalRole = PortalRole{}
	if err := utils.UnmarshalJSON(data, &portalRole, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  RoleTypePortalRole,
			Value: &portalRole,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Role", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Role", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(RoleType)
	switch best.Type {
	case RoleTypeUserRole:
		u.UserRole = best.Value.(*UserRole)
		return nil
	case RoleTypeOrgRole:
		u.OrgRole = best.Value.(*OrgRole)
		return nil
	case RoleTypeShareRole:
		u.ShareRole = best.Value.(*ShareRole)
		return nil
	case RoleTypePartnerRole:
		u.PartnerRole = best.Value.(*PartnerRole)
		return nil
	case RoleTypePortalRole:
		u.PortalRole = best.Value.(*PortalRole)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Role", string(data))
}

func (u Role) MarshalJSON() ([]byte, error) {
	if u.UserRole != nil {
		return utils.MarshalJSON(u.UserRole, "", true)
	}

	if u.OrgRole != nil {
		return utils.MarshalJSON(u.OrgRole, "", true)
	}

	if u.ShareRole != nil {
		return utils.MarshalJSON(u.ShareRole, "", true)
	}

	if u.PartnerRole != nil {
		return utils.MarshalJSON(u.PartnerRole, "", true)
	}

	if u.PortalRole != nil {
		return utils.MarshalJSON(u.PortalRole, "", true)
	}

	return nil, errors.New("could not marshal union type Role: all fields are null")
}
