// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SavePortalFileS3ref struct {
	// S3 bucket name
	Bucket string `json:"bucket"`
	// S3 key
	Key string `json:"key"`
}

func (s *SavePortalFileS3ref) GetBucket() string {
	if s == nil {
		return ""
	}
	return s.Bucket
}

func (s *SavePortalFileS3ref) GetKey() string {
	if s == nil {
		return ""
	}
	return s.Key
}

type SavePortalFileFiles struct {
	// Array of file tags
	Tags []string `json:"_tags,omitempty"`
	// File type
	FileType string `json:"file_type"`
	// File name
	Filename *string              `json:"filename,omitempty"`
	S3ref    *SavePortalFileS3ref `json:"s3ref,omitempty"`
}

func (s *SavePortalFileFiles) GetTags() []string {
	if s == nil {
		return nil
	}
	return s.Tags
}

func (s *SavePortalFileFiles) GetFileType() string {
	if s == nil {
		return ""
	}
	return s.FileType
}

func (s *SavePortalFileFiles) GetFilename() *string {
	if s == nil {
		return nil
	}
	return s.Filename
}

func (s *SavePortalFileFiles) GetS3ref() *SavePortalFileS3ref {
	if s == nil {
		return nil
	}
	return s.S3ref
}

type SavePortalFile struct {
	Files []SavePortalFileFiles `json:"files"`
	// Origin of the portal
	Origin string `json:"origin"`
}

func (s *SavePortalFile) GetFiles() []SavePortalFileFiles {
	if s == nil {
		return []SavePortalFileFiles{}
	}
	return s.Files
}

func (s *SavePortalFile) GetOrigin() string {
	if s == nil {
		return ""
	}
	return s.Origin
}
