// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/internal/utils"
	"time"
)

type ShareRoleType string

const (
	ShareRoleTypeShareRole ShareRoleType = "share_role"
)

func (e ShareRoleType) ToPointer() *ShareRoleType {
	return &e
}
func (e *ShareRoleType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "share_role":
		*e = ShareRoleType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ShareRoleType: %v", v)
	}
}

// ShareRole - A role that can be assigned to users in other organizations for sharing purposes.
type ShareRole struct {
	// date and time then the role will expire
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// List of grants (permissions) applied to the role
	Grants []Grant `json:"grants"`
	// Format: <organization_id>:<slug>
	ID string `json:"id"`
	// Human-friendly name for the role
	Name string `json:"name"`
	// Id of an organization
	OrganizationID string `json:"organization_id"`
	// URL-friendly name for the role
	Slug string        `json:"slug"`
	Type ShareRoleType `json:"type"`
}

func (s ShareRole) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *ShareRole) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, []string{"grants", "id", "name", "organization_id", "slug", "type"}); err != nil {
		return err
	}
	return nil
}

func (s *ShareRole) GetExpiresAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.ExpiresAt
}

func (s *ShareRole) GetGrants() []Grant {
	if s == nil {
		return []Grant{}
	}
	return s.Grants
}

func (s *ShareRole) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *ShareRole) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *ShareRole) GetOrganizationID() string {
	if s == nil {
		return ""
	}
	return s.OrganizationID
}

func (s *ShareRole) GetSlug() string {
	if s == nil {
		return ""
	}
	return s.Slug
}

func (s *ShareRole) GetType() ShareRoleType {
	if s == nil {
		return ShareRoleType("")
	}
	return s.Type
}
