// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SSOCallbackRequest struct {
	// The client id
	ClientID string `json:"client_id"`
	// The client secret
	ClientSecret *string `json:"client_secret,omitempty"`
	// The code received from the external SSO provider
	Code string `json:"code"`
	// The code verifier
	CodeVerifier string `json:"code_verifier"`
	// The grant type
	GrantType string `json:"grant_type"`
	// The redirect uri
	RedirectURI string `json:"redirect_uri"`
	// URL of the authorization endpoint
	TokenEndpoint string `json:"token_endpoint"`
}

func (o *SSOCallbackRequest) GetClientID() string {
	if o == nil {
		return ""
	}
	return o.ClientID
}

func (o *SSOCallbackRequest) GetClientSecret() *string {
	if o == nil {
		return nil
	}
	return o.ClientSecret
}

func (o *SSOCallbackRequest) GetCode() string {
	if o == nil {
		return ""
	}
	return o.Code
}

func (o *SSOCallbackRequest) GetCodeVerifier() string {
	if o == nil {
		return ""
	}
	return o.CodeVerifier
}

func (o *SSOCallbackRequest) GetGrantType() string {
	if o == nil {
		return ""
	}
	return o.GrantType
}

func (o *SSOCallbackRequest) GetRedirectURI() string {
	if o == nil {
		return ""
	}
	return o.RedirectURI
}

func (o *SSOCallbackRequest) GetTokenEndpoint() string {
	if o == nil {
		return ""
	}
	return o.TokenEndpoint
}
