// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type UpsertPortalConfigV3AdvancedMfa struct {
	// Advanced MFA feature flag
	Enabled *bool `json:"enabled,omitempty"`
}

func (u *UpsertPortalConfigV3AdvancedMfa) GetEnabled() *bool {
	if u == nil {
		return nil
	}
	return u.Enabled
}

// UpsertPortalConfigV3PasswordPolicy - Password policy for the portal
type UpsertPortalConfigV3PasswordPolicy struct {
	// Maximum password length
	MaximumLength *int64 `json:"maximum_length,omitempty"`
	// Minimum password length
	MinimumLength *int64 `json:"minimum_length,omitempty"`
	// Require lowercase characters
	RequireLowercase *bool `json:"require_lowercase,omitempty"`
	// Require numbers
	RequireNumbers *bool `json:"require_numbers,omitempty"`
	// Require symbols
	RequireSymbols *bool `json:"require_symbols,omitempty"`
	// Require uppercase characters
	RequireUppercase *bool `json:"require_uppercase,omitempty"`
}

func (u *UpsertPortalConfigV3PasswordPolicy) GetMaximumLength() *int64 {
	if u == nil {
		return nil
	}
	return u.MaximumLength
}

func (u *UpsertPortalConfigV3PasswordPolicy) GetMinimumLength() *int64 {
	if u == nil {
		return nil
	}
	return u.MinimumLength
}

func (u *UpsertPortalConfigV3PasswordPolicy) GetRequireLowercase() *bool {
	if u == nil {
		return nil
	}
	return u.RequireLowercase
}

func (u *UpsertPortalConfigV3PasswordPolicy) GetRequireNumbers() *bool {
	if u == nil {
		return nil
	}
	return u.RequireNumbers
}

func (u *UpsertPortalConfigV3PasswordPolicy) GetRequireSymbols() *bool {
	if u == nil {
		return nil
	}
	return u.RequireSymbols
}

func (u *UpsertPortalConfigV3PasswordPolicy) GetRequireUppercase() *bool {
	if u == nil {
		return nil
	}
	return u.RequireUppercase
}

// UpsertPortalConfigV3CognitoDetails - AWS Cognito Pool details for the portal
type UpsertPortalConfigV3CognitoDetails struct {
	// Cognito user pool ARN
	CognitoUserPoolArn *string `json:"cognito_user_pool_arn,omitempty"`
	// Cognito user pool client ID
	CognitoUserPoolClientID *string `json:"cognito_user_pool_client_id,omitempty"`
	// Cognito user pool ID
	CognitoUserPoolID *string `json:"cognito_user_pool_id,omitempty"`
	// Password policy for the portal
	PasswordPolicy *UpsertPortalConfigV3PasswordPolicy `json:"password_policy,omitempty"`
}

func (u *UpsertPortalConfigV3CognitoDetails) GetCognitoUserPoolArn() *string {
	if u == nil {
		return nil
	}
	return u.CognitoUserPoolArn
}

func (u *UpsertPortalConfigV3CognitoDetails) GetCognitoUserPoolClientID() *string {
	if u == nil {
		return nil
	}
	return u.CognitoUserPoolClientID
}

func (u *UpsertPortalConfigV3CognitoDetails) GetCognitoUserPoolID() *string {
	if u == nil {
		return nil
	}
	return u.CognitoUserPoolID
}

func (u *UpsertPortalConfigV3CognitoDetails) GetPasswordPolicy() *UpsertPortalConfigV3PasswordPolicy {
	if u == nil {
		return nil
	}
	return u.PasswordPolicy
}

// UpsertPortalConfigV3ContractSelectorConfig - Configuration for contract selector in the portal
type UpsertPortalConfigV3ContractSelectorConfig struct {
	// Whether to show inactive contracts in the selector
	ShowInactive *bool `json:"show_inactive,omitempty"`
	// Path to the property to use as the contract title
	TitlePath *string `json:"title_path,omitempty"`
}

func (u *UpsertPortalConfigV3ContractSelectorConfig) GetShowInactive() *bool {
	if u == nil {
		return nil
	}
	return u.ShowInactive
}

func (u *UpsertPortalConfigV3ContractSelectorConfig) GetTitlePath() *string {
	if u == nil {
		return nil
	}
	return u.TitlePath
}

// UpsertPortalConfigV3DefaultUserToNotify - Default 360 user to notify upon an internal notification
type UpsertPortalConfigV3DefaultUserToNotify struct {
	// Default admin users for pending user notification to notify
	OnPendingUser []AdminUser `json:"onPendingUser,omitempty"`
}

func (u *UpsertPortalConfigV3DefaultUserToNotify) GetOnPendingUser() []AdminUser {
	if u == nil {
		return nil
	}
	return u.OnPendingUser
}

type UpsertPortalConfigV3ActionLabel struct {
	De *string `json:"de,omitempty"`
	En *string `json:"en,omitempty"`
}

func (u *UpsertPortalConfigV3ActionLabel) GetDe() *string {
	if u == nil {
		return nil
	}
	return u.De
}

func (u *UpsertPortalConfigV3ActionLabel) GetEn() *string {
	if u == nil {
		return nil
	}
	return u.En
}

type UpsertPortalConfigV3EntityActions struct {
	ActionLabel *UpsertPortalConfigV3ActionLabel `json:"action_Label,omitempty"`
	// Entity ID
	JourneyID *string `json:"journey_id,omitempty"`
	// URL-friendly identifier for the entity schema
	Slug *string `json:"slug,omitempty"`
}

func (u *UpsertPortalConfigV3EntityActions) GetActionLabel() *UpsertPortalConfigV3ActionLabel {
	if u == nil {
		return nil
	}
	return u.ActionLabel
}

func (u *UpsertPortalConfigV3EntityActions) GetJourneyID() *string {
	if u == nil {
		return nil
	}
	return u.JourneyID
}

func (u *UpsertPortalConfigV3EntityActions) GetSlug() *string {
	if u == nil {
		return nil
	}
	return u.Slug
}

type UpsertPortalConfigV3Type struct {
	// Attributes used to identify an entity
	Attributes []string `json:"attributes,omitempty"`
	// Enable/Disable the entity identifier
	IsEnabled *bool `json:"isEnabled,omitempty"`
}

func (u *UpsertPortalConfigV3Type) GetAttributes() []string {
	if u == nil {
		return nil
	}
	return u.Attributes
}

func (u *UpsertPortalConfigV3Type) GetIsEnabled() *bool {
	if u == nil {
		return nil
	}
	return u.IsEnabled
}

// UpsertPortalConfigV3EntityIdentifiers - Identifiers used to identify an entity by a portal user. Deprecated. Use contract_identifiers instead.
//
// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
type UpsertPortalConfigV3EntityIdentifiers struct {
	Type *UpsertPortalConfigV3Type `json:"type,omitempty"`
}

func (u *UpsertPortalConfigV3EntityIdentifiers) GetType() *UpsertPortalConfigV3Type {
	if u == nil {
		return nil
	}
	return u.Type
}

// UpsertPortalConfigV3Images - Teaser & Banner Image web links
type UpsertPortalConfigV3Images struct {
	// URL of the order left teaser image
	OrderLeftTeaser *string `json:"orderLeftTeaser,omitempty"`
	// URL of the order right teaser image
	OrderRightTeaser *string `json:"orderRightTeaser,omitempty"`
	// URL of the welcome banner image
	WelcomeBanner *string `json:"welcomeBanner,omitempty"`
}

func (u *UpsertPortalConfigV3Images) GetOrderLeftTeaser() *string {
	if u == nil {
		return nil
	}
	return u.OrderLeftTeaser
}

func (u *UpsertPortalConfigV3Images) GetOrderRightTeaser() *string {
	if u == nil {
		return nil
	}
	return u.OrderRightTeaser
}

func (u *UpsertPortalConfigV3Images) GetWelcomeBanner() *string {
	if u == nil {
		return nil
	}
	return u.WelcomeBanner
}

type UpsertPortalConfigV3SelfRegistrationSetting string

const (
	UpsertPortalConfigV3SelfRegistrationSettingAllowWithContactCreation    UpsertPortalConfigV3SelfRegistrationSetting = "ALLOW_WITH_CONTACT_CREATION"
	UpsertPortalConfigV3SelfRegistrationSettingAllowWithoutContactCreation UpsertPortalConfigV3SelfRegistrationSetting = "ALLOW_WITHOUT_CONTACT_CREATION"
	UpsertPortalConfigV3SelfRegistrationSettingDeny                        UpsertPortalConfigV3SelfRegistrationSetting = "DENY"
	UpsertPortalConfigV3SelfRegistrationSettingAlwaysCreateContact         UpsertPortalConfigV3SelfRegistrationSetting = "ALWAYS_CREATE_CONTACT"
	UpsertPortalConfigV3SelfRegistrationSettingDisallowCompletely          UpsertPortalConfigV3SelfRegistrationSetting = "DISALLOW_COMPLETELY"
	UpsertPortalConfigV3SelfRegistrationSettingBlockIfPortalUserExists     UpsertPortalConfigV3SelfRegistrationSetting = "BLOCK_IF_PORTAL_USER_EXISTS"
)

func (e UpsertPortalConfigV3SelfRegistrationSetting) ToPointer() *UpsertPortalConfigV3SelfRegistrationSetting {
	return &e
}
func (e *UpsertPortalConfigV3SelfRegistrationSetting) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ALLOW_WITH_CONTACT_CREATION":
		fallthrough
	case "ALLOW_WITHOUT_CONTACT_CREATION":
		fallthrough
	case "DENY":
		fallthrough
	case "ALWAYS_CREATE_CONTACT":
		fallthrough
	case "DISALLOW_COMPLETELY":
		fallthrough
	case "BLOCK_IF_PORTAL_USER_EXISTS":
		*e = UpsertPortalConfigV3SelfRegistrationSetting(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpsertPortalConfigV3SelfRegistrationSetting: %v", v)
	}
}

type UpsertPortalConfigV3TriggerName string

const (
	UpsertPortalConfigV3TriggerNameFirstLogin   UpsertPortalConfigV3TriggerName = "FIRST_LOGIN"
	UpsertPortalConfigV3TriggerNameAcceptOrder  UpsertPortalConfigV3TriggerName = "ACCEPT_ORDER"
	UpsertPortalConfigV3TriggerNameDeclineOrder UpsertPortalConfigV3TriggerName = "DECLINE_ORDER"
)

func (e UpsertPortalConfigV3TriggerName) ToPointer() *UpsertPortalConfigV3TriggerName {
	return &e
}
func (e *UpsertPortalConfigV3TriggerName) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "FIRST_LOGIN":
		fallthrough
	case "ACCEPT_ORDER":
		fallthrough
	case "DECLINE_ORDER":
		*e = UpsertPortalConfigV3TriggerName(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpsertPortalConfigV3TriggerName: %v", v)
	}
}

type UpsertPortalConfigV3TriggeredJourneys struct {
	// Entity ID
	JourneyID   *string                          `json:"journey_id,omitempty"`
	TriggerName *UpsertPortalConfigV3TriggerName `json:"trigger_name,omitempty"`
}

func (u *UpsertPortalConfigV3TriggeredJourneys) GetJourneyID() *string {
	if u == nil {
		return nil
	}
	return u.JourneyID
}

func (u *UpsertPortalConfigV3TriggeredJourneys) GetTriggerName() *UpsertPortalConfigV3TriggerName {
	if u == nil {
		return nil
	}
	return u.TriggerName
}

type UpsertPortalConfigV3 struct {
	// Access token for the portal
	AccessToken *string                          `json:"accessToken,omitempty"`
	AdvancedMfa *UpsertPortalConfigV3AdvancedMfa `json:"advanced_mfa,omitempty"`
	// Allowed file extensions for upload
	AllowedFileExtensions   *AllowedFileExtensions `json:"allowed_file_extensions,omitempty"`
	ApprovalStateAttributes any                    `json:"approval_state_attributes,omitempty"`
	// Authentication settings for the portal
	AuthSettings any `json:"auth_settings,omitempty"`
	// AWS Cognito Pool details for the portal
	CognitoDetails *UpsertPortalConfigV3CognitoDetails `json:"cognito_details,omitempty"`
	// Stringified object with configuration details
	Config *string `json:"config,omitempty"`
	// Deprecated. Use registration_identifiers instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	ContactIdentifiers []string `json:"contact_identifiers,omitempty"`
	// Identifiers to identify a contract by a portal user.
	ContractIdentifiers any `json:"contract_identifiers,omitempty"`
	// Configuration for contract selector in the portal
	ContractSelectorConfig *UpsertPortalConfigV3ContractSelectorConfig `json:"contract_selector_config,omitempty"`
	// Default 360 user to notify upon an internal notification
	DefaultUserToNotify *UpsertPortalConfigV3DefaultUserToNotify `json:"default_user_to_notify,omitempty"`
	// Entity ID
	DesignID *string `json:"design_id,omitempty"`
	// The URL on which the portal is accessible
	Domain *string `json:"domain,omitempty"`
	// Email templates used for authentication and internal processes
	EmailTemplates *EmailTemplates `json:"email_templates,omitempty"`
	// Enable/Disable the portal access
	Enabled *bool `json:"enabled,omitempty"`
	// Journey actions allowed on an entity by a portal user
	EntityActions []UpsertPortalConfigV3EntityActions `json:"entity_actions,omitempty"`
	// Rules for editing an entity by a portal user
	EntityEditRules any `json:"entity_edit_rules,omitempty"`
	// Identifiers used to identify an entity by a portal user. Deprecated. Use contract_identifiers instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	EntityIdentifiers *UpsertPortalConfigV3EntityIdentifiers `json:"entity_identifiers,omitempty"`
	// Configured Portal extensions hooks
	ExtensionHooks any `json:"extension_hooks,omitempty"`
	// Configured Portal extensions
	Extensions []ExtensionConfig `json:"extensions,omitempty"`
	// Feature settings for the portal
	FeatureSettings any `json:"feature_settings,omitempty"`
	// Teaser & Banner Image web links
	Images *UpsertPortalConfigV3Images `json:"images,omitempty"`
	// Number of years to look back for showing inactive contracts in the portal
	InactiveContractCutoffYears *float64 `json:"inactive_contract_cutoff_years,omitempty"`
	// Whether this is a dummy/test portal configuration
	IsDummy *bool `json:"is_dummy,omitempty"`
	// Mark true if the domain is an Epilot domain
	IsEpilotDomain *bool `json:"is_epilot_domain,omitempty"`
	// Whether this is a v3 portal configuration
	IsV3Item *bool `json:"is_v3_item,omitempty"`
	// Grace period in days for meter readings
	MeterReadingGracePeriod *float64 `json:"meter_reading_grace_period,omitempty"`
	// A short name to identify your portal
	Name *string `json:"name,omitempty"`
	// Origin of the portal
	Origin *string `json:"origin,omitempty"`
	Pages  any     `json:"pages,omitempty"`
	// ID of the portal
	PortalID *string `json:"portal_id,omitempty"`
	// Key of the portal config
	PortalSkV3 *string `json:"portal_sk_v3,omitempty"`
	// Prevent indexing by search engines
	PreventSearchEngineIndexing *bool `json:"prevent_search_engine_indexing,omitempty"`
	// Identifiers to identify a contact of a portal user during the registration.
	RegistrationIdentifiers any                                          `json:"registration_identifiers,omitempty"`
	SelfRegistrationSetting *UpsertPortalConfigV3SelfRegistrationSetting `json:"self_registration_setting,omitempty"`
	// Journeys automatically opened on a portal user action
	TriggeredJourneys []UpsertPortalConfigV3TriggeredJourneys `json:"triggered_journeys,omitempty"`
	// Enable or disable user account self management
	UserAccountSelfManagement *bool `json:"user_account_self_management,omitempty"`
}

func (u *UpsertPortalConfigV3) GetAccessToken() *string {
	if u == nil {
		return nil
	}
	return u.AccessToken
}

func (u *UpsertPortalConfigV3) GetAdvancedMfa() *UpsertPortalConfigV3AdvancedMfa {
	if u == nil {
		return nil
	}
	return u.AdvancedMfa
}

func (u *UpsertPortalConfigV3) GetAllowedFileExtensions() *AllowedFileExtensions {
	if u == nil {
		return nil
	}
	return u.AllowedFileExtensions
}

func (u *UpsertPortalConfigV3) GetApprovalStateAttributes() any {
	if u == nil {
		return nil
	}
	return u.ApprovalStateAttributes
}

func (u *UpsertPortalConfigV3) GetAuthSettings() any {
	if u == nil {
		return nil
	}
	return u.AuthSettings
}

func (u *UpsertPortalConfigV3) GetCognitoDetails() *UpsertPortalConfigV3CognitoDetails {
	if u == nil {
		return nil
	}
	return u.CognitoDetails
}

func (u *UpsertPortalConfigV3) GetConfig() *string {
	if u == nil {
		return nil
	}
	return u.Config
}

func (u *UpsertPortalConfigV3) GetContactIdentifiers() []string {
	if u == nil {
		return nil
	}
	return u.ContactIdentifiers
}

func (u *UpsertPortalConfigV3) GetContractIdentifiers() any {
	if u == nil {
		return nil
	}
	return u.ContractIdentifiers
}

func (u *UpsertPortalConfigV3) GetContractSelectorConfig() *UpsertPortalConfigV3ContractSelectorConfig {
	if u == nil {
		return nil
	}
	return u.ContractSelectorConfig
}

func (u *UpsertPortalConfigV3) GetDefaultUserToNotify() *UpsertPortalConfigV3DefaultUserToNotify {
	if u == nil {
		return nil
	}
	return u.DefaultUserToNotify
}

func (u *UpsertPortalConfigV3) GetDesignID() *string {
	if u == nil {
		return nil
	}
	return u.DesignID
}

func (u *UpsertPortalConfigV3) GetDomain() *string {
	if u == nil {
		return nil
	}
	return u.Domain
}

func (u *UpsertPortalConfigV3) GetEmailTemplates() *EmailTemplates {
	if u == nil {
		return nil
	}
	return u.EmailTemplates
}

func (u *UpsertPortalConfigV3) GetEnabled() *bool {
	if u == nil {
		return nil
	}
	return u.Enabled
}

func (u *UpsertPortalConfigV3) GetEntityActions() []UpsertPortalConfigV3EntityActions {
	if u == nil {
		return nil
	}
	return u.EntityActions
}

func (u *UpsertPortalConfigV3) GetEntityEditRules() any {
	if u == nil {
		return nil
	}
	return u.EntityEditRules
}

func (u *UpsertPortalConfigV3) GetEntityIdentifiers() *UpsertPortalConfigV3EntityIdentifiers {
	if u == nil {
		return nil
	}
	return u.EntityIdentifiers
}

func (u *UpsertPortalConfigV3) GetExtensionHooks() any {
	if u == nil {
		return nil
	}
	return u.ExtensionHooks
}

func (u *UpsertPortalConfigV3) GetExtensions() []ExtensionConfig {
	if u == nil {
		return nil
	}
	return u.Extensions
}

func (u *UpsertPortalConfigV3) GetFeatureSettings() any {
	if u == nil {
		return nil
	}
	return u.FeatureSettings
}

func (u *UpsertPortalConfigV3) GetImages() *UpsertPortalConfigV3Images {
	if u == nil {
		return nil
	}
	return u.Images
}

func (u *UpsertPortalConfigV3) GetInactiveContractCutoffYears() *float64 {
	if u == nil {
		return nil
	}
	return u.InactiveContractCutoffYears
}

func (u *UpsertPortalConfigV3) GetIsDummy() *bool {
	if u == nil {
		return nil
	}
	return u.IsDummy
}

func (u *UpsertPortalConfigV3) GetIsEpilotDomain() *bool {
	if u == nil {
		return nil
	}
	return u.IsEpilotDomain
}

func (u *UpsertPortalConfigV3) GetIsV3Item() *bool {
	if u == nil {
		return nil
	}
	return u.IsV3Item
}

func (u *UpsertPortalConfigV3) GetMeterReadingGracePeriod() *float64 {
	if u == nil {
		return nil
	}
	return u.MeterReadingGracePeriod
}

func (u *UpsertPortalConfigV3) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpsertPortalConfigV3) GetOrigin() *string {
	if u == nil {
		return nil
	}
	return u.Origin
}

func (u *UpsertPortalConfigV3) GetPages() any {
	if u == nil {
		return nil
	}
	return u.Pages
}

func (u *UpsertPortalConfigV3) GetPortalID() *string {
	if u == nil {
		return nil
	}
	return u.PortalID
}

func (u *UpsertPortalConfigV3) GetPortalSkV3() *string {
	if u == nil {
		return nil
	}
	return u.PortalSkV3
}

func (u *UpsertPortalConfigV3) GetPreventSearchEngineIndexing() *bool {
	if u == nil {
		return nil
	}
	return u.PreventSearchEngineIndexing
}

func (u *UpsertPortalConfigV3) GetRegistrationIdentifiers() any {
	if u == nil {
		return nil
	}
	return u.RegistrationIdentifiers
}

func (u *UpsertPortalConfigV3) GetSelfRegistrationSetting() *UpsertPortalConfigV3SelfRegistrationSetting {
	if u == nil {
		return nil
	}
	return u.SelfRegistrationSetting
}

func (u *UpsertPortalConfigV3) GetTriggeredJourneys() []UpsertPortalConfigV3TriggeredJourneys {
	if u == nil {
		return nil
	}
	return u.TriggeredJourneys
}

func (u *UpsertPortalConfigV3) GetUserAccountSelfManagement() *bool {
	if u == nil {
		return nil
	}
	return u.UserAccountSelfManagement
}
