// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type UpsertPortalConfigAdvancedMfa struct {
	// Advanced MFA feature flag
	Enabled *bool `json:"enabled,omitempty"`
}

func (u *UpsertPortalConfigAdvancedMfa) GetEnabled() *bool {
	if u == nil {
		return nil
	}
	return u.Enabled
}

type UpsertPortalConfigEntryPoint string

const (
	UpsertPortalConfigEntryPointPassword UpsertPortalConfigEntryPoint = "PASSWORD"
	UpsertPortalConfigEntryPointSso      UpsertPortalConfigEntryPoint = "SSO"
)

func (e UpsertPortalConfigEntryPoint) ToPointer() *UpsertPortalConfigEntryPoint {
	return &e
}
func (e *UpsertPortalConfigEntryPoint) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PASSWORD":
		fallthrough
	case "SSO":
		*e = UpsertPortalConfigEntryPoint(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpsertPortalConfigEntryPoint: %v", v)
	}
}

type UpsertPortalConfigPasswordlessLogin struct {
	// Passwordless login feature flag
	Enabled *bool `json:"enabled,omitempty"`
}

func (u *UpsertPortalConfigPasswordlessLogin) GetEnabled() *bool {
	if u == nil {
		return nil
	}
	return u.Enabled
}

// UpsertPortalConfigAuthSettings - Authentication settings for the portal
type UpsertPortalConfigAuthSettings struct {
	// Decide whether to automatically redirect to the provider page during login, which would completely bypass showing the portal authentication page.
	AutoRedirectToSso     *bool                                `json:"auto_redirect_to_sso,omitempty"`
	EntryPoint            *UpsertPortalConfigEntryPoint        `json:"entry_point,omitempty"`
	PasswordlessLogin     *UpsertPortalConfigPasswordlessLogin `json:"passwordless_login,omitempty"`
	PreferredSsoProviders []string                             `json:"preferred_sso_providers,omitempty"`
}

func (u *UpsertPortalConfigAuthSettings) GetAutoRedirectToSso() *bool {
	if u == nil {
		return nil
	}
	return u.AutoRedirectToSso
}

func (u *UpsertPortalConfigAuthSettings) GetEntryPoint() *UpsertPortalConfigEntryPoint {
	if u == nil {
		return nil
	}
	return u.EntryPoint
}

func (u *UpsertPortalConfigAuthSettings) GetPasswordlessLogin() *UpsertPortalConfigPasswordlessLogin {
	if u == nil {
		return nil
	}
	return u.PasswordlessLogin
}

func (u *UpsertPortalConfigAuthSettings) GetPreferredSsoProviders() []string {
	if u == nil {
		return nil
	}
	return u.PreferredSsoProviders
}

// UpsertPortalConfigPasswordPolicy - Password policy for the portal
type UpsertPortalConfigPasswordPolicy struct {
	// Minimum password length
	MinimumLength *int64 `json:"minimum_length,omitempty"`
	// Require lowercase characters
	RequireLowercase *bool `json:"require_lowercase,omitempty"`
	// Require numbers
	RequireNumbers *bool `json:"require_numbers,omitempty"`
	// Require symbols
	RequireSymbols *bool `json:"require_symbols,omitempty"`
	// Require uppercase characters
	RequireUppercase *bool `json:"require_uppercase,omitempty"`
}

func (u *UpsertPortalConfigPasswordPolicy) GetMinimumLength() *int64 {
	if u == nil {
		return nil
	}
	return u.MinimumLength
}

func (u *UpsertPortalConfigPasswordPolicy) GetRequireLowercase() *bool {
	if u == nil {
		return nil
	}
	return u.RequireLowercase
}

func (u *UpsertPortalConfigPasswordPolicy) GetRequireNumbers() *bool {
	if u == nil {
		return nil
	}
	return u.RequireNumbers
}

func (u *UpsertPortalConfigPasswordPolicy) GetRequireSymbols() *bool {
	if u == nil {
		return nil
	}
	return u.RequireSymbols
}

func (u *UpsertPortalConfigPasswordPolicy) GetRequireUppercase() *bool {
	if u == nil {
		return nil
	}
	return u.RequireUppercase
}

// UpsertPortalConfigCognitoDetails - AWS Cognito Pool details for the portal
type UpsertPortalConfigCognitoDetails struct {
	// Cognito user pool ARN
	CognitoUserPoolArn *string `json:"cognito_user_pool_arn,omitempty"`
	// Cognito user pool client ID
	CognitoUserPoolClientID *string `json:"cognito_user_pool_client_id,omitempty"`
	// Cognito user pool ID
	CognitoUserPoolID *string `json:"cognito_user_pool_id,omitempty"`
	// Password policy for the portal
	PasswordPolicy *UpsertPortalConfigPasswordPolicy `json:"password_policy,omitempty"`
}

func (u *UpsertPortalConfigCognitoDetails) GetCognitoUserPoolArn() *string {
	if u == nil {
		return nil
	}
	return u.CognitoUserPoolArn
}

func (u *UpsertPortalConfigCognitoDetails) GetCognitoUserPoolClientID() *string {
	if u == nil {
		return nil
	}
	return u.CognitoUserPoolClientID
}

func (u *UpsertPortalConfigCognitoDetails) GetCognitoUserPoolID() *string {
	if u == nil {
		return nil
	}
	return u.CognitoUserPoolID
}

func (u *UpsertPortalConfigCognitoDetails) GetPasswordPolicy() *UpsertPortalConfigPasswordPolicy {
	if u == nil {
		return nil
	}
	return u.PasswordPolicy
}

// UpsertPortalConfigContractSelectorConfig - Configuration for contract selector in the portal
type UpsertPortalConfigContractSelectorConfig struct {
	// Whether to show inactive contracts in the selector
	ShowInactive *bool `json:"show_inactive,omitempty"`
	// Path to the property to use as the contract title
	TitlePath *string `json:"title_path,omitempty"`
}

func (u *UpsertPortalConfigContractSelectorConfig) GetShowInactive() *bool {
	if u == nil {
		return nil
	}
	return u.ShowInactive
}

func (u *UpsertPortalConfigContractSelectorConfig) GetTitlePath() *string {
	if u == nil {
		return nil
	}
	return u.TitlePath
}

// UpsertPortalConfigDefaultUserToNotify - Default 360 user to notify upon an internal notification
type UpsertPortalConfigDefaultUserToNotify struct {
	// Default admin users for pending user notification to notify
	OnPendingUser []AdminUser `json:"onPendingUser,omitempty"`
}

func (u *UpsertPortalConfigDefaultUserToNotify) GetOnPendingUser() []AdminUser {
	if u == nil {
		return nil
	}
	return u.OnPendingUser
}

type UpsertPortalConfigActionLabel struct {
	De *string `json:"de,omitempty"`
	En *string `json:"en,omitempty"`
}

func (u *UpsertPortalConfigActionLabel) GetDe() *string {
	if u == nil {
		return nil
	}
	return u.De
}

func (u *UpsertPortalConfigActionLabel) GetEn() *string {
	if u == nil {
		return nil
	}
	return u.En
}

type UpsertPortalConfigEntityActions struct {
	ActionLabel *UpsertPortalConfigActionLabel `json:"action_Label,omitempty"`
	// Entity ID
	JourneyID *string `json:"journey_id,omitempty"`
	// URL-friendly identifier for the entity schema
	Slug *EntitySlug `json:"slug,omitempty"`
}

func (u *UpsertPortalConfigEntityActions) GetActionLabel() *UpsertPortalConfigActionLabel {
	if u == nil {
		return nil
	}
	return u.ActionLabel
}

func (u *UpsertPortalConfigEntityActions) GetJourneyID() *string {
	if u == nil {
		return nil
	}
	return u.JourneyID
}

func (u *UpsertPortalConfigEntityActions) GetSlug() *EntitySlug {
	if u == nil {
		return nil
	}
	return u.Slug
}

type UpsertPortalConfigCadencePeriodType string

const (
	UpsertPortalConfigCadencePeriodTypeDays   UpsertPortalConfigCadencePeriodType = "days"
	UpsertPortalConfigCadencePeriodTypeWeeks  UpsertPortalConfigCadencePeriodType = "weeks"
	UpsertPortalConfigCadencePeriodTypeMonths UpsertPortalConfigCadencePeriodType = "months"
)

func (e UpsertPortalConfigCadencePeriodType) ToPointer() *UpsertPortalConfigCadencePeriodType {
	return &e
}
func (e *UpsertPortalConfigCadencePeriodType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "days":
		fallthrough
	case "weeks":
		fallthrough
	case "months":
		*e = UpsertPortalConfigCadencePeriodType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpsertPortalConfigCadencePeriodType: %v", v)
	}
}

type UpsertPortalConfigRuleType string

const (
	UpsertPortalConfigRuleTypeCadence                UpsertPortalConfigRuleType = "cadence"
	UpsertPortalConfigRuleTypeRelativeToCurrentValue UpsertPortalConfigRuleType = "relative_to_current_value"
	UpsertPortalConfigRuleTypeDaysBeforeDate         UpsertPortalConfigRuleType = "days_before_date"
	UpsertPortalConfigRuleTypeOverduePayments        UpsertPortalConfigRuleType = "overdue_payments"
)

func (e UpsertPortalConfigRuleType) ToPointer() *UpsertPortalConfigRuleType {
	return &e
}
func (e *UpsertPortalConfigRuleType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "cadence":
		fallthrough
	case "relative_to_current_value":
		fallthrough
	case "days_before_date":
		fallthrough
	case "overdue_payments":
		*e = UpsertPortalConfigRuleType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpsertPortalConfigRuleType: %v", v)
	}
}

type UpsertPortalConfigEntityEditRules struct {
	AllowedDecrement              *string                              `json:"allowed_decrement,omitempty"`
	AllowedIncrement              *string                              `json:"allowed_increment,omitempty"`
	Attribute                     *string                              `json:"attribute,omitempty"`
	CadencePeriod                 *float64                             `json:"cadence_period,omitempty"`
	CadencePeriodType             *UpsertPortalConfigCadencePeriodType `json:"cadence_period_type,omitempty"`
	ChangesAllowed                *int64                               `json:"changes_allowed,omitempty"`
	GracePeriod                   *int64                               `json:"grace_period,omitempty"`
	NumberOfDaysBeforeRestriction *int64                               `json:"number_of_days_before_restriction,omitempty"`
	RuleType                      *UpsertPortalConfigRuleType          `json:"rule_type,omitempty"`
	// URL-friendly identifier for the entity schema
	Slug *EntitySlug `json:"slug,omitempty"`
}

func (u *UpsertPortalConfigEntityEditRules) GetAllowedDecrement() *string {
	if u == nil {
		return nil
	}
	return u.AllowedDecrement
}

func (u *UpsertPortalConfigEntityEditRules) GetAllowedIncrement() *string {
	if u == nil {
		return nil
	}
	return u.AllowedIncrement
}

func (u *UpsertPortalConfigEntityEditRules) GetAttribute() *string {
	if u == nil {
		return nil
	}
	return u.Attribute
}

func (u *UpsertPortalConfigEntityEditRules) GetCadencePeriod() *float64 {
	if u == nil {
		return nil
	}
	return u.CadencePeriod
}

func (u *UpsertPortalConfigEntityEditRules) GetCadencePeriodType() *UpsertPortalConfigCadencePeriodType {
	if u == nil {
		return nil
	}
	return u.CadencePeriodType
}

func (u *UpsertPortalConfigEntityEditRules) GetChangesAllowed() *int64 {
	if u == nil {
		return nil
	}
	return u.ChangesAllowed
}

func (u *UpsertPortalConfigEntityEditRules) GetGracePeriod() *int64 {
	if u == nil {
		return nil
	}
	return u.GracePeriod
}

func (u *UpsertPortalConfigEntityEditRules) GetNumberOfDaysBeforeRestriction() *int64 {
	if u == nil {
		return nil
	}
	return u.NumberOfDaysBeforeRestriction
}

func (u *UpsertPortalConfigEntityEditRules) GetRuleType() *UpsertPortalConfigRuleType {
	if u == nil {
		return nil
	}
	return u.RuleType
}

func (u *UpsertPortalConfigEntityEditRules) GetSlug() *EntitySlug {
	if u == nil {
		return nil
	}
	return u.Slug
}

type UpsertPortalConfigType struct {
	// Attributes used to identify an entity
	Attributes []string `json:"attributes,omitempty"`
	// Enable/Disable the entity identifier
	IsEnabled *bool `json:"isEnabled,omitempty"`
}

func (u *UpsertPortalConfigType) GetAttributes() []string {
	if u == nil {
		return nil
	}
	return u.Attributes
}

func (u *UpsertPortalConfigType) GetIsEnabled() *bool {
	if u == nil {
		return nil
	}
	return u.IsEnabled
}

// UpsertPortalConfigEntityIdentifiers - Identifiers used to identify an entity by a portal user. Deprecated. Use contract_identifiers instead.
//
// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
type UpsertPortalConfigEntityIdentifiers struct {
	Type *UpsertPortalConfigType `json:"type,omitempty"`
}

func (u *UpsertPortalConfigEntityIdentifiers) GetType() *UpsertPortalConfigType {
	if u == nil {
		return nil
	}
	return u.Type
}

// UpsertPortalConfigFeatureSettings - Feature settings for the portal
type UpsertPortalConfigFeatureSettings struct {
	// Billing feature flag
	Billing *bool `json:"billing,omitempty"`
	// Change due date feature flag
	ChangeDueDate *bool `json:"change_due_date,omitempty"`
	// Enable or disable the new design for the portal
	NewDesign *bool `json:"new_design,omitempty"`
	// Start page feature flag
	StartPage *bool `json:"start_page,omitempty"`
}

func (u *UpsertPortalConfigFeatureSettings) GetBilling() *bool {
	if u == nil {
		return nil
	}
	return u.Billing
}

func (u *UpsertPortalConfigFeatureSettings) GetChangeDueDate() *bool {
	if u == nil {
		return nil
	}
	return u.ChangeDueDate
}

func (u *UpsertPortalConfigFeatureSettings) GetNewDesign() *bool {
	if u == nil {
		return nil
	}
	return u.NewDesign
}

func (u *UpsertPortalConfigFeatureSettings) GetStartPage() *bool {
	if u == nil {
		return nil
	}
	return u.StartPage
}

// UpsertPortalConfigImages - Teaser & Banner Image web links
type UpsertPortalConfigImages struct {
	// URL of the order left teaser image
	OrderLeftTeaser *string `json:"orderLeftTeaser,omitempty"`
	// URL of the order right teaser image
	OrderRightTeaser *string `json:"orderRightTeaser,omitempty"`
	// URL of the welcome banner image
	WelcomeBanner *string `json:"welcomeBanner,omitempty"`
}

func (u *UpsertPortalConfigImages) GetOrderLeftTeaser() *string {
	if u == nil {
		return nil
	}
	return u.OrderLeftTeaser
}

func (u *UpsertPortalConfigImages) GetOrderRightTeaser() *string {
	if u == nil {
		return nil
	}
	return u.OrderRightTeaser
}

func (u *UpsertPortalConfigImages) GetWelcomeBanner() *string {
	if u == nil {
		return nil
	}
	return u.WelcomeBanner
}

type UpsertPortalConfigSelfRegistrationSetting string

const (
	UpsertPortalConfigSelfRegistrationSettingAllowWithContactCreation    UpsertPortalConfigSelfRegistrationSetting = "ALLOW_WITH_CONTACT_CREATION"
	UpsertPortalConfigSelfRegistrationSettingAllowWithoutContactCreation UpsertPortalConfigSelfRegistrationSetting = "ALLOW_WITHOUT_CONTACT_CREATION"
	UpsertPortalConfigSelfRegistrationSettingDeny                        UpsertPortalConfigSelfRegistrationSetting = "DENY"
)

func (e UpsertPortalConfigSelfRegistrationSetting) ToPointer() *UpsertPortalConfigSelfRegistrationSetting {
	return &e
}
func (e *UpsertPortalConfigSelfRegistrationSetting) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ALLOW_WITH_CONTACT_CREATION":
		fallthrough
	case "ALLOW_WITHOUT_CONTACT_CREATION":
		fallthrough
	case "DENY":
		*e = UpsertPortalConfigSelfRegistrationSetting(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpsertPortalConfigSelfRegistrationSetting: %v", v)
	}
}

type UpsertPortalConfigTriggerName string

const (
	UpsertPortalConfigTriggerNameFirstLogin   UpsertPortalConfigTriggerName = "FIRST_LOGIN"
	UpsertPortalConfigTriggerNameAcceptOrder  UpsertPortalConfigTriggerName = "ACCEPT_ORDER"
	UpsertPortalConfigTriggerNameDeclineOrder UpsertPortalConfigTriggerName = "DECLINE_ORDER"
)

func (e UpsertPortalConfigTriggerName) ToPointer() *UpsertPortalConfigTriggerName {
	return &e
}
func (e *UpsertPortalConfigTriggerName) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "FIRST_LOGIN":
		fallthrough
	case "ACCEPT_ORDER":
		fallthrough
	case "DECLINE_ORDER":
		*e = UpsertPortalConfigTriggerName(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpsertPortalConfigTriggerName: %v", v)
	}
}

type UpsertPortalConfigTriggeredJourneys struct {
	// Entity ID
	JourneyID   *string                        `json:"journey_id,omitempty"`
	TriggerName *UpsertPortalConfigTriggerName `json:"trigger_name,omitempty"`
}

func (u *UpsertPortalConfigTriggeredJourneys) GetJourneyID() *string {
	if u == nil {
		return nil
	}
	return u.JourneyID
}

func (u *UpsertPortalConfigTriggeredJourneys) GetTriggerName() *UpsertPortalConfigTriggerName {
	if u == nil {
		return nil
	}
	return u.TriggerName
}

type UpsertPortalConfig struct {
	// Access token for the portal
	AccessToken *string                        `json:"accessToken,omitempty"`
	AdvancedMfa *UpsertPortalConfigAdvancedMfa `json:"advanced_mfa,omitempty"`
	// Allowed file extensions for upload
	AllowedFileExtensions   *AllowedFileExtensions `json:"allowed_file_extensions,omitempty"`
	ApprovalStateAttributes map[string][]string    `json:"approval_state_attributes,omitempty"`
	// Authentication settings for the portal
	AuthSettings *UpsertPortalConfigAuthSettings `json:"auth_settings,omitempty"`
	// AWS Cognito Pool details for the portal
	CognitoDetails *UpsertPortalConfigCognitoDetails `json:"cognito_details,omitempty"`
	// Stringified object with configuration details
	Config *string `json:"config,omitempty"`
	// Deprecated. Use registration_identifiers instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	ContactIdentifiers []string `json:"contact_identifiers,omitempty"`
	// Identifiers to identify a contract by a portal user.
	ContractIdentifiers []ContractIdentifier `json:"contract_identifiers,omitempty"`
	// Configuration for contract selector in the portal
	ContractSelectorConfig *UpsertPortalConfigContractSelectorConfig `json:"contract_selector_config,omitempty"`
	// Default 360 user to notify upon an internal notification
	DefaultUserToNotify *UpsertPortalConfigDefaultUserToNotify `json:"default_user_to_notify,omitempty"`
	// Entity ID
	DesignID *string `json:"design_id,omitempty"`
	// The URL on which the portal is accessible
	Domain string `json:"domain"`
	// Email templates used for authentication and internal processes
	EmailTemplates *EmailTemplates `json:"email_templates,omitempty"`
	// Enable/Disable the portal access
	Enabled *bool `json:"enabled,omitempty"`
	// Journey actions allowed on an entity by a portal user
	EntityActions []UpsertPortalConfigEntityActions `json:"entity_actions,omitempty"`
	// Rules for editing an entity by a portal user
	EntityEditRules []UpsertPortalConfigEntityEditRules `json:"entity_edit_rules,omitempty"`
	// Identifiers used to identify an entity by a portal user. Deprecated. Use contract_identifiers instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	EntityIdentifiers *UpsertPortalConfigEntityIdentifiers `json:"entity_identifiers,omitempty"`
	// Configured Portal extensions hooks
	ExtensionHooks map[string]*ExtensionHookConfig `json:"extension_hooks,omitempty"`
	// Configured Portal extensions
	Extensions []ExtensionConfig `json:"extensions,omitempty"`
	// Feature settings for the portal
	FeatureSettings *UpsertPortalConfigFeatureSettings `json:"feature_settings,omitempty"`
	// Teaser & Banner Image web links
	Images *UpsertPortalConfigImages `json:"images,omitempty"`
	// Number of years to look back for showing inactive contracts in the portal
	InactiveContractCutoffYears *float64 `json:"inactive_contract_cutoff_years,omitempty"`
	// Whether this is a dummy/test portal configuration
	IsDummy *bool `json:"is_dummy,omitempty"`
	// Mark true if the domain is an Epilot domain
	IsEpilotDomain *bool `json:"is_epilot_domain,omitempty"`
	// Whether this is a v3 portal configuration
	IsV3Item *bool `json:"is_v3_item,omitempty"`
	// Grace period in days for meter readings
	MeterReadingGracePeriod *float64 `json:"meter_reading_grace_period,omitempty"`
	// A short name to identify your portal
	Name *string `json:"name,omitempty"`
	// Origin of the portal
	Origin *string         `json:"origin,omitempty"`
	Pages  map[string]Page `json:"pages,omitempty"`
	// ID of the portal
	PortalID *string `json:"portal_id,omitempty"`
	// Key of the portal config
	PortalSkV3 *string `json:"portal_sk_v3,omitempty"`
	// Prevent indexing by search engines
	PreventSearchEngineIndexing *bool `json:"prevent_search_engine_indexing,omitempty"`
	// Identifiers to identify a contact of a portal user during the registration.
	RegistrationIdentifiers []ContractIdentifier                       `json:"registration_identifiers,omitempty"`
	SelfRegistrationSetting *UpsertPortalConfigSelfRegistrationSetting `json:"self_registration_setting,omitempty"`
	// Journeys automatically opened on a portal user action
	TriggeredJourneys []UpsertPortalConfigTriggeredJourneys `json:"triggered_journeys,omitempty"`
}

func (u *UpsertPortalConfig) GetAccessToken() *string {
	if u == nil {
		return nil
	}
	return u.AccessToken
}

func (u *UpsertPortalConfig) GetAdvancedMfa() *UpsertPortalConfigAdvancedMfa {
	if u == nil {
		return nil
	}
	return u.AdvancedMfa
}

func (u *UpsertPortalConfig) GetAllowedFileExtensions() *AllowedFileExtensions {
	if u == nil {
		return nil
	}
	return u.AllowedFileExtensions
}

func (u *UpsertPortalConfig) GetApprovalStateAttributes() map[string][]string {
	if u == nil {
		return nil
	}
	return u.ApprovalStateAttributes
}

func (u *UpsertPortalConfig) GetAuthSettings() *UpsertPortalConfigAuthSettings {
	if u == nil {
		return nil
	}
	return u.AuthSettings
}

func (u *UpsertPortalConfig) GetCognitoDetails() *UpsertPortalConfigCognitoDetails {
	if u == nil {
		return nil
	}
	return u.CognitoDetails
}

func (u *UpsertPortalConfig) GetConfig() *string {
	if u == nil {
		return nil
	}
	return u.Config
}

func (u *UpsertPortalConfig) GetContactIdentifiers() []string {
	if u == nil {
		return nil
	}
	return u.ContactIdentifiers
}

func (u *UpsertPortalConfig) GetContractIdentifiers() []ContractIdentifier {
	if u == nil {
		return nil
	}
	return u.ContractIdentifiers
}

func (u *UpsertPortalConfig) GetContractSelectorConfig() *UpsertPortalConfigContractSelectorConfig {
	if u == nil {
		return nil
	}
	return u.ContractSelectorConfig
}

func (u *UpsertPortalConfig) GetDefaultUserToNotify() *UpsertPortalConfigDefaultUserToNotify {
	if u == nil {
		return nil
	}
	return u.DefaultUserToNotify
}

func (u *UpsertPortalConfig) GetDesignID() *string {
	if u == nil {
		return nil
	}
	return u.DesignID
}

func (u *UpsertPortalConfig) GetDomain() string {
	if u == nil {
		return ""
	}
	return u.Domain
}

func (u *UpsertPortalConfig) GetEmailTemplates() *EmailTemplates {
	if u == nil {
		return nil
	}
	return u.EmailTemplates
}

func (u *UpsertPortalConfig) GetEnabled() *bool {
	if u == nil {
		return nil
	}
	return u.Enabled
}

func (u *UpsertPortalConfig) GetEntityActions() []UpsertPortalConfigEntityActions {
	if u == nil {
		return nil
	}
	return u.EntityActions
}

func (u *UpsertPortalConfig) GetEntityEditRules() []UpsertPortalConfigEntityEditRules {
	if u == nil {
		return nil
	}
	return u.EntityEditRules
}

func (u *UpsertPortalConfig) GetEntityIdentifiers() *UpsertPortalConfigEntityIdentifiers {
	if u == nil {
		return nil
	}
	return u.EntityIdentifiers
}

func (u *UpsertPortalConfig) GetExtensionHooks() map[string]*ExtensionHookConfig {
	if u == nil {
		return nil
	}
	return u.ExtensionHooks
}

func (u *UpsertPortalConfig) GetExtensions() []ExtensionConfig {
	if u == nil {
		return nil
	}
	return u.Extensions
}

func (u *UpsertPortalConfig) GetFeatureSettings() *UpsertPortalConfigFeatureSettings {
	if u == nil {
		return nil
	}
	return u.FeatureSettings
}

func (u *UpsertPortalConfig) GetImages() *UpsertPortalConfigImages {
	if u == nil {
		return nil
	}
	return u.Images
}

func (u *UpsertPortalConfig) GetInactiveContractCutoffYears() *float64 {
	if u == nil {
		return nil
	}
	return u.InactiveContractCutoffYears
}

func (u *UpsertPortalConfig) GetIsDummy() *bool {
	if u == nil {
		return nil
	}
	return u.IsDummy
}

func (u *UpsertPortalConfig) GetIsEpilotDomain() *bool {
	if u == nil {
		return nil
	}
	return u.IsEpilotDomain
}

func (u *UpsertPortalConfig) GetIsV3Item() *bool {
	if u == nil {
		return nil
	}
	return u.IsV3Item
}

func (u *UpsertPortalConfig) GetMeterReadingGracePeriod() *float64 {
	if u == nil {
		return nil
	}
	return u.MeterReadingGracePeriod
}

func (u *UpsertPortalConfig) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpsertPortalConfig) GetOrigin() *string {
	if u == nil {
		return nil
	}
	return u.Origin
}

func (u *UpsertPortalConfig) GetPages() map[string]Page {
	if u == nil {
		return nil
	}
	return u.Pages
}

func (u *UpsertPortalConfig) GetPortalID() *string {
	if u == nil {
		return nil
	}
	return u.PortalID
}

func (u *UpsertPortalConfig) GetPortalSkV3() *string {
	if u == nil {
		return nil
	}
	return u.PortalSkV3
}

func (u *UpsertPortalConfig) GetPreventSearchEngineIndexing() *bool {
	if u == nil {
		return nil
	}
	return u.PreventSearchEngineIndexing
}

func (u *UpsertPortalConfig) GetRegistrationIdentifiers() []ContractIdentifier {
	if u == nil {
		return nil
	}
	return u.RegistrationIdentifiers
}

func (u *UpsertPortalConfig) GetSelfRegistrationSetting() *UpsertPortalConfigSelfRegistrationSetting {
	if u == nil {
		return nil
	}
	return u.SelfRegistrationSetting
}

func (u *UpsertPortalConfig) GetTriggeredJourneys() []UpsertPortalConfigTriggeredJourneys {
	if u == nil {
		return nil
	}
	return u.TriggeredJourneys
}
