// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type UpsertPortalWidget struct {
	Widgets []any `json:"widgets"`
}

func (u *UpsertPortalWidget) GetWidgets() []any {
	if u == nil {
		return []any{}
	}
	return u.Widgets
}
