// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	tfTypes "github.com/epilot-dev/terraform-provider-epilot-portal/internal/provider/types"
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &PortalConfigDataSource{}
var _ datasource.DataSourceWithConfigure = &PortalConfigDataSource{}

func NewPortalConfigDataSource() datasource.DataSource {
	return &PortalConfigDataSource{}
}

// PortalConfigDataSource is the data source implementation.
type PortalConfigDataSource struct {
	// Provider configured SDK client.
	client *sdk.SDK
}

// PortalConfigDataSourceModel describes the data model.
type PortalConfigDataSourceModel struct {
	AccessToken                 types.String                                        `tfsdk:"access_token"`
	AdvancedMfa                 *tfTypes.UpsertPortalConfigV3AdvancedMfa            `tfsdk:"advanced_mfa"`
	AllowedFileExtensions       *tfTypes.AllowedFileExtensions                      `tfsdk:"allowed_file_extensions"`
	ApprovalStateAttributes     jsontypes.Normalized                                `tfsdk:"approval_state_attributes"`
	AuthSettings                *tfTypes.UpsertPortalConfigV3AuthSettings           `tfsdk:"auth_settings"`
	CognitoDetails              *tfTypes.UpsertPortalConfigV3CognitoDetails         `tfsdk:"cognito_details"`
	Config                      types.String                                        `tfsdk:"config"`
	ContactIdentifiers          []types.String                                      `tfsdk:"contact_identifiers"`
	ContractIdentifiers         jsontypes.Normalized                                `tfsdk:"contract_identifiers"`
	ContractSelectorConfig      *tfTypes.UpsertPortalConfigV3ContractSelectorConfig `tfsdk:"contract_selector_config"`
	DefaultUserToNotify         *tfTypes.UpsertPortalConfigV3DefaultUserToNotify    `tfsdk:"default_user_to_notify"`
	DesignID                    types.String                                        `tfsdk:"design_id"`
	Domain                      types.String                                        `tfsdk:"domain"`
	EmailTemplates              *tfTypes.EmailTemplates                             `tfsdk:"email_templates"`
	Enabled                     types.Bool                                          `tfsdk:"enabled"`
	EntityActions               []tfTypes.EntityActions                             `tfsdk:"entity_actions"`
	EntityEditRules             jsontypes.Normalized                                `tfsdk:"entity_edit_rules"`
	EntityIdentifiers           *tfTypes.UpsertPortalConfigV3EntityIdentifiers      `tfsdk:"entity_identifiers"`
	ExtensionHooks              map[string]tfTypes.ExtensionHookConfig              `tfsdk:"extension_hooks"`
	Extensions                  []tfTypes.ExtensionConfig                           `tfsdk:"extensions"`
	FeatureFlags                jsontypes.Normalized                                `tfsdk:"feature_flags"`
	FeatureSettings             *tfTypes.UpsertPortalConfigV3FeatureSettings        `tfsdk:"feature_settings"`
	Grants                      jsontypes.Normalized                                `tfsdk:"grants"`
	IdentityProviders           jsontypes.Normalized                                `tfsdk:"identity_providers"`
	Images                      *tfTypes.UpsertPortalConfigV3Images                 `tfsdk:"images"`
	InactiveContractCutoffYears types.Float64                                       `tfsdk:"inactive_contract_cutoff_years"`
	IsDummy                     types.Bool                                          `tfsdk:"is_dummy"`
	IsEpilotDomain              types.Bool                                          `tfsdk:"is_epilot_domain"`
	MeterReadingGracePeriod     types.Float64                                       `tfsdk:"meter_reading_grace_period"`
	Name                        types.String                                        `tfsdk:"name"`
	OrgSettings                 *tfTypes.PortalConfigV3OrgSettings                  `tfsdk:"org_settings"`
	OrganizationID              types.String                                        `tfsdk:"organization_id"`
	Origin                      types.String                                        `tfsdk:"origin"`
	Pages                       jsontypes.Normalized                                `tfsdk:"pages"`
	PortalID                    types.String                                        `tfsdk:"portal_id"`
	PortalSkV3                  types.String                                        `tfsdk:"portal_sk_v3"`
	PreventSearchEngineIndexing types.Bool                                          `tfsdk:"prevent_search_engine_indexing"`
	RegistrationIdentifiers     jsontypes.Normalized                                `tfsdk:"registration_identifiers"`
	SelfRegistrationSetting     types.String                                        `tfsdk:"self_registration_setting"`
	TriggeredJourneys           []tfTypes.PortalConfigV3TriggeredJourneys           `tfsdk:"triggered_journeys"`
}

// Metadata returns the data source type name.
func (r *PortalConfigDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_portal_config"
}

// Schema defines the schema for the data source.
func (r *PortalConfigDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "PortalConfig DataSource",

		Attributes: map[string]schema.Attribute{
			"access_token": schema.StringAttribute{
				Computed:    true,
				Description: `Access token for the portal`,
			},
			"advanced_mfa": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"enabled": schema.BoolAttribute{
						Computed:    true,
						Description: `Advanced MFA feature flag`,
					},
				},
			},
			"allowed_file_extensions": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"archive": schema.ListAttribute{
						Computed:    true,
						ElementType: types.StringType,
					},
					"audio_video": schema.ListAttribute{
						Computed:    true,
						ElementType: types.StringType,
					},
					"cad": schema.ListAttribute{
						Computed:    true,
						ElementType: types.StringType,
					},
					"calendar": schema.ListAttribute{
						Computed:    true,
						ElementType: types.StringType,
					},
					"document": schema.ListAttribute{
						Computed:    true,
						ElementType: types.StringType,
					},
					"email": schema.ListAttribute{
						Computed:    true,
						ElementType: types.StringType,
					},
					"image": schema.ListAttribute{
						Computed:    true,
						ElementType: types.StringType,
					},
					"other": schema.ListAttribute{
						Computed:    true,
						ElementType: types.StringType,
					},
					"presentation": schema.ListAttribute{
						Computed:    true,
						ElementType: types.StringType,
					},
					"spreadsheet": schema.ListAttribute{
						Computed:    true,
						ElementType: types.StringType,
					},
				},
				Description: `Allowed file extensions for upload`,
			},
			"approval_state_attributes": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: `Parsed as JSON.`,
			},
			"auth_settings": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"entry_point": schema.StringAttribute{
						Computed: true,
					},
					"passwordless_login": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"enabled": schema.BoolAttribute{
								Computed:    true,
								Description: `Passwordless login feature flag`,
							},
						},
					},
					"preferred_sso_providers": schema.ListAttribute{
						Computed:    true,
						ElementType: types.StringType,
					},
				},
				Description: `Authentication settings for the portal`,
			},
			"cognito_details": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"cognito_user_pool_arn": schema.StringAttribute{
						Computed:    true,
						Description: `Cognito user pool ARN`,
					},
					"cognito_user_pool_client_id": schema.StringAttribute{
						Computed:    true,
						Description: `Cognito user pool client ID`,
					},
					"cognito_user_pool_id": schema.StringAttribute{
						Computed:    true,
						Description: `Cognito user pool ID`,
					},
					"password_policy": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"minimum_length": schema.Int64Attribute{
								Computed:    true,
								Description: `Minimum password length`,
							},
							"require_lowercase": schema.BoolAttribute{
								Computed:    true,
								Description: `Require lowercase characters`,
							},
							"require_numbers": schema.BoolAttribute{
								Computed:    true,
								Description: `Require numbers`,
							},
							"require_symbols": schema.BoolAttribute{
								Computed:    true,
								Description: `Require symbols`,
							},
							"require_uppercase": schema.BoolAttribute{
								Computed:    true,
								Description: `Require uppercase characters`,
							},
						},
						Description: `Password policy for the portal`,
					},
				},
				Description: `AWS Cognito Pool details for the portal`,
			},
			"config": schema.StringAttribute{
				Computed:    true,
				Description: `Stringified object with configuration details`,
			},
			"contact_identifiers": schema.ListAttribute{
				Computed:           true,
				ElementType:        types.StringType,
				DeprecationMessage: `This will be removed in a future release, please migrate away from it as soon as possible`,
				Description:        `Deprecated. Use registration_identifiers instead.`,
			},
			"contract_identifiers": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: `Identifiers to identify a contract by a portal user. Parsed as JSON.`,
			},
			"contract_selector_config": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"show_inactive": schema.BoolAttribute{
						Computed:    true,
						Description: `Whether to show inactive contracts in the selector`,
					},
					"title_path": schema.StringAttribute{
						Computed:    true,
						Description: `Path to the property to use as the contract title`,
					},
				},
				Description: `Configuration for contract selector in the portal`,
			},
			"default_user_to_notify": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"on_pending_user": schema.ListNestedAttribute{
						Computed: true,
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"additional_properties": schema.StringAttribute{
									CustomType:  jsontypes.NormalizedType{},
									Computed:    true,
									Description: `Parsed as JSON.`,
								},
								"display_name": schema.StringAttribute{
									Computed: true,
								},
								"email": schema.StringAttribute{
									Computed: true,
								},
								"image_uri": schema.SingleNestedAttribute{
									Computed: true,
									Attributes: map[string]schema.Attribute{
										"key": schema.StringAttribute{
											Computed: true,
										},
										"original": schema.StringAttribute{
											Computed: true,
										},
										"thumbnail_32": schema.StringAttribute{
											Computed: true,
										},
										"thumbnail_64": schema.StringAttribute{
											Computed: true,
										},
									},
								},
								"org_id": schema.StringAttribute{
									Computed: true,
								},
								"phone": schema.StringAttribute{
									Computed: true,
								},
								"type": schema.StringAttribute{
									Computed: true,
								},
								"user_id": schema.StringAttribute{
									Computed: true,
								},
							},
						},
						Description: `Default admin users for pending user notification to notify`,
					},
				},
				Description: `Default 360 user to notify upon an internal notification`,
			},
			"design_id": schema.StringAttribute{
				Computed:    true,
				Description: `Entity ID`,
			},
			"domain": schema.StringAttribute{
				Computed:    true,
				Description: `The URL on which the portal is accessible`,
			},
			"email_templates": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"advanced_auth": schema.StringAttribute{
						Computed:    true,
						Description: `Entity ID`,
					},
					"advanced_mfa": schema.StringAttribute{
						Computed:    true,
						Description: `Entity ID`,
					},
					"confirm_account": schema.StringAttribute{
						Computed:    true,
						Description: `Entity ID`,
					},
					"confirm_email_update": schema.StringAttribute{
						Computed:    true,
						Description: `Entity ID`,
					},
					"forgot_password": schema.StringAttribute{
						Computed:    true,
						Description: `Entity ID`,
					},
					"invitation": schema.StringAttribute{
						Computed:    true,
						Description: `Entity ID`,
					},
					"journey_login_otp": schema.StringAttribute{
						Computed:    true,
						Description: `Entity ID`,
					},
					"journey_sign_in_one_time_password": schema.StringAttribute{
						Computed:    true,
						Description: `Entity ID`,
					},
					"journey_sign_up": schema.StringAttribute{
						Computed:    true,
						Description: `Entity ID`,
					},
					"on_doc_upload": schema.StringAttribute{
						Computed:    true,
						Description: `Entity ID`,
					},
					"on_map_a_pending_user": schema.StringAttribute{
						Computed:    true,
						Description: `Entity ID`,
					},
					"on_new_quote": schema.StringAttribute{
						Computed:    true,
						Description: `Entity ID`,
					},
					"on_workflow_step_assigned": schema.StringAttribute{
						Computed:    true,
						Description: `Entity ID`,
					},
					"verify_code_to_set_password": schema.StringAttribute{
						Computed:    true,
						Description: `Entity ID`,
					},
				},
				Description: `Email templates used for authentication and internal processes`,
			},
			"enabled": schema.BoolAttribute{
				Computed:    true,
				Description: `Enable/Disable the portal access`,
			},
			"entity_actions": schema.ListNestedAttribute{
				Computed: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"action_label": schema.SingleNestedAttribute{
							Computed: true,
							Attributes: map[string]schema.Attribute{
								"de": schema.StringAttribute{
									Computed: true,
								},
								"en": schema.StringAttribute{
									Computed: true,
								},
							},
						},
						"journey_id": schema.StringAttribute{
							Computed:    true,
							Description: `Entity ID`,
						},
						"slug": schema.StringAttribute{
							Computed:    true,
							Description: `URL-friendly identifier for the entity schema`,
						},
					},
				},
				Description: `Journey actions allowed on an entity by a portal user`,
			},
			"entity_edit_rules": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: `Rules for editing an entity by a portal user. Parsed as JSON.`,
			},
			"entity_identifiers": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"type": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"attributes": schema.ListAttribute{
								Computed:    true,
								ElementType: types.StringType,
								Description: `Attributes used to identify an entity`,
							},
							"is_enabled": schema.BoolAttribute{
								Computed:    true,
								Description: `Enable/Disable the entity identifier`,
							},
						},
					},
				},
				DeprecationMessage: `This will be removed in a future release, please migrate away from it as soon as possible`,
				Description:        `Identifiers used to identify an entity by a portal user. Deprecated. Use contract_identifiers instead.`,
			},
			"extension_hooks": schema.MapNestedAttribute{
				Computed: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"app_id": schema.StringAttribute{
							Computed:    true,
							Description: `The ID of the app that is being hooked into.`,
						},
						"hook_id": schema.StringAttribute{
							Computed:    true,
							Description: `The ID of the hook that is being configured.`,
						},
					},
				},
				Description: `Configured Portal extensions hooks`,
			},
			"extensions": schema.ListNestedAttribute{
				Computed: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							Computed:    true,
							Description: `Name of the extension`,
						},
						"options": schema.MapAttribute{
							Computed:    true,
							ElementType: types.StringType,
							Description: `Extension option values.`,
						},
						"status": schema.StringAttribute{
							Computed:    true,
							Description: `Status of the extension`,
						},
					},
				},
				Description: `Configured Portal extensions`,
			},
			"feature_flags": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: `Feature flags for the portal. Parsed as JSON.`,
			},
			"feature_settings": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"billing": schema.BoolAttribute{
						Computed:    true,
						Description: `Billing feature flag`,
					},
					"change_due_date": schema.BoolAttribute{
						Computed:    true,
						Description: `Change due date feature flag`,
					},
					"new_design": schema.BoolAttribute{
						Computed:    true,
						Description: `Enable or disable the new design for the portal`,
					},
					"start_page": schema.BoolAttribute{
						Computed:    true,
						Description: `Start page feature flag`,
					},
				},
				Description: `Feature settings for the portal`,
			},
			"grants": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: `Permissions granted to a portal user while accessing entities. Parsed as JSON.`,
			},
			"identity_providers": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: `Parsed as JSON.`,
			},
			"images": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"order_left_teaser": schema.StringAttribute{
						Computed:    true,
						Description: `URL of the order left teaser image`,
					},
					"order_right_teaser": schema.StringAttribute{
						Computed:    true,
						Description: `URL of the order right teaser image`,
					},
					"welcome_banner": schema.StringAttribute{
						Computed:    true,
						Description: `URL of the welcome banner image`,
					},
				},
				Description: `Teaser & Banner Image web links`,
			},
			"inactive_contract_cutoff_years": schema.Float64Attribute{
				Computed:    true,
				Description: `Number of years to look back for showing inactive contracts in the portal`,
			},
			"is_dummy": schema.BoolAttribute{
				Computed:    true,
				Description: `Whether this is a dummy/test portal configuration`,
			},
			"is_epilot_domain": schema.BoolAttribute{
				Computed:    true,
				Description: `Mark true if the domain is an Epilot domain`,
			},
			"meter_reading_grace_period": schema.Float64Attribute{
				Computed:    true,
				Description: `Grace period in days for meter readings`,
			},
			"name": schema.StringAttribute{
				Computed:    true,
				Description: `A short name to identify your portal`,
			},
			"org_settings": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"canary": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"enabled": schema.BoolAttribute{
								Computed:    true,
								Description: `Enable/Disable the canary feature`,
							},
						},
						Description: `Canary feature flag`,
					},
					"notracking": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"enabled": schema.BoolAttribute{
								Computed:    true,
								Description: `Disable browser-side scripts that track advanced usage metrics`,
							},
						},
						Description: `Disable Advanced Usage Metrics`,
					},
				},
				Description: `Organization settings`,
			},
			"organization_id": schema.StringAttribute{
				Computed:    true,
				Description: `ID of the organization`,
			},
			"origin": schema.StringAttribute{
				Computed:    true,
				Description: `Origin of the portal`,
			},
			"pages": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: `Parsed as JSON.`,
			},
			"portal_id": schema.StringAttribute{
				Required:    true,
				Description: `Portal ID (readonly UUID generated on portal creation)`,
			},
			"portal_sk_v3": schema.StringAttribute{
				Computed:    true,
				Description: `Key of the portal config`,
			},
			"prevent_search_engine_indexing": schema.BoolAttribute{
				Computed:    true,
				Description: `Prevent indexing by search engines`,
			},
			"registration_identifiers": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: `Identifiers to identify a contact of a portal user during the registration. Parsed as JSON.`,
			},
			"self_registration_setting": schema.StringAttribute{
				Computed: true,
			},
			"triggered_journeys": schema.ListNestedAttribute{
				Computed: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"journey_id": schema.StringAttribute{
							Computed:    true,
							Description: `Entity ID`,
						},
						"trigger_name": schema.StringAttribute{
							Computed: true,
						},
					},
				},
				Description: `Journeys automatically opened on a portal user action`,
			},
		},
	}
}

func (r *PortalConfigDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.SDK)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.SDK, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *PortalConfigDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *PortalConfigDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsGetPortalConfigV3Request(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.ECPAdmin.GetPortalConfigV3(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.PortalConfigV3 != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedPortalConfigV3(ctx, res.PortalConfigV3)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
