// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/provider/typeconvert"
	tfTypes "github.com/epilot-dev/terraform-provider-epilot-portal/internal/provider/types"
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/operations"
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *PortalPageResourceModel) RefreshFromSharedPage(ctx context.Context, resp *shared.Page) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		if resp.AdditionalProperties == nil {
			r.AdditionalProperties = jsontypes.NewNormalizedNull()
		} else {
			additionalPropertiesResult, _ := json.Marshal(resp.AdditionalProperties)
			r.AdditionalProperties = jsontypes.NewNormalizedValue(string(additionalPropertiesResult))
		}
		if len(resp.Blocks) > 0 {
			r.Blocks = make(map[string]tfTypes.Block, len(resp.Blocks))
			for blockKey, blockValue := range resp.Blocks {
				var blockResult tfTypes.Block
				if blockValue.AdditionalProperties == nil {
					blockResult.AdditionalProperties = jsontypes.NewNormalizedNull()
				} else {
					additionalPropertiesResult1, _ := json.Marshal(blockValue.AdditionalProperties)
					blockResult.AdditionalProperties = jsontypes.NewNormalizedValue(string(additionalPropertiesResult1))
				}
				blockResult.ID = types.StringPointerValue(blockValue.ID)
				blockResult.Order = types.Float64Value(blockValue.Order)
				blockResult.ParentID = types.StringPointerValue(blockValue.ParentID)
				if blockValue.Props == nil {
					blockResult.Props = nil
				} else {
					blockResult.Props = &tfTypes.BlockProps{}
					if blockValue.Props.AdditionalProperties == nil {
						blockResult.Props.AdditionalProperties = jsontypes.NewNormalizedNull()
					} else {
						additionalPropertiesResult2, _ := json.Marshal(blockValue.Props.AdditionalProperties)
						blockResult.Props.AdditionalProperties = jsontypes.NewNormalizedValue(string(additionalPropertiesResult2))
					}
					if len(blockValue.Props.Content) > 0 {
						blockResult.Props.Content = make(map[string]jsontypes.Normalized, len(blockValue.Props.Content))
						for key, value := range blockValue.Props.Content {
							result, _ := json.Marshal(value)
							blockResult.Props.Content[key] = jsontypes.NewNormalizedValue(string(result))
						}
					}
					if len(blockValue.Props.Design) > 0 {
						blockResult.Props.Design = make(map[string]jsontypes.Normalized, len(blockValue.Props.Design))
						for key1, value1 := range blockValue.Props.Design {
							result1, _ := json.Marshal(value1)
							blockResult.Props.Design[key1] = jsontypes.NewNormalizedValue(string(result1))
						}
					}
					if len(blockValue.Props.Visibility) > 0 {
						blockResult.Props.Visibility = make(map[string]jsontypes.Normalized, len(blockValue.Props.Visibility))
						for key2, value2 := range blockValue.Props.Visibility {
							result2, _ := json.Marshal(value2)
							blockResult.Props.Visibility[key2] = jsontypes.NewNormalizedValue(string(result2))
						}
					}
				}
				blockResult.Type = types.StringValue(blockValue.Type)

				r.Blocks[blockKey] = blockResult
			}
		}
		if len(resp.Content) > 0 {
			r.Content = make(map[string]jsontypes.Normalized, len(resp.Content))
			for key3, value3 := range resp.Content {
				result3, _ := json.Marshal(value3)
				r.Content[key3] = jsontypes.NewNormalizedValue(string(result3))
			}
		}
		if len(resp.Design) > 0 {
			r.Design = make(map[string]jsontypes.Normalized, len(resp.Design))
			for key4, value4 := range resp.Design {
				result4, _ := json.Marshal(value4)
				r.Design[key4] = jsontypes.NewNormalizedValue(string(result4))
			}
		}
		r.ID = types.StringPointerValue(resp.ID)
		r.IsDeleted = types.BoolPointerValue(resp.IsDeleted)
		r.IsEntryRoute = types.BoolPointerValue(resp.IsEntryRoute)
		r.IsPublic = types.BoolPointerValue(resp.IsPublic)
		r.IsSystem = types.BoolPointerValue(resp.IsSystem)
		r.LastModifiedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.LastModifiedAt))
		r.Order = types.Float64Value(resp.Order)
		r.ParentID = types.StringPointerValue(resp.ParentID)
		r.Path = types.StringPointerValue(resp.Path)
		r.Schema = make([]types.String, 0, len(resp.Schema))
		for _, v := range resp.Schema {
			r.Schema = append(r.Schema, types.StringValue(string(v)))
		}
		r.Slug = types.StringValue(resp.Slug)
		if len(resp.Visibility) > 0 {
			r.Visibility = make(map[string]jsontypes.Normalized, len(resp.Visibility))
			for key5, value5 := range resp.Visibility {
				result5, _ := json.Marshal(value5)
				r.Visibility[key5] = jsontypes.NewNormalizedValue(string(result5))
			}
		}
	}

	return diags
}

func (r *PortalPageResourceModel) ToOperationsCreatePortalPageRequest(ctx context.Context) (*operations.CreatePortalPageRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	pageRequest, pageRequestDiags := r.ToSharedPageRequest(ctx)
	diags.Append(pageRequestDiags...)

	if diags.HasError() {
		return nil, diags
	}

	var domain string
	domain = r.Domain.ValueString()

	out := operations.CreatePortalPageRequest{
		PageRequest: *pageRequest,
		Domain:      domain,
	}

	return &out, diags
}

func (r *PortalPageResourceModel) ToOperationsDeletePortalPageRequest(ctx context.Context) (*operations.DeletePortalPageRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	out := operations.DeletePortalPageRequest{
		ID: id,
	}

	return &out, diags
}

func (r *PortalPageResourceModel) ToOperationsGetPortalPageRequest(ctx context.Context) (*operations.GetPortalPageRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	out := operations.GetPortalPageRequest{
		ID: id,
	}

	return &out, diags
}

func (r *PortalPageResourceModel) ToOperationsUpdatePortalPageRequest(ctx context.Context) (*operations.UpdatePortalPageRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	pageRequest, pageRequestDiags := r.ToSharedPageRequest(ctx)
	diags.Append(pageRequestDiags...)

	if diags.HasError() {
		return nil, diags
	}

	var id string
	id = r.ID.ValueString()

	out := operations.UpdatePortalPageRequest{
		PageRequest: *pageRequest,
		ID:          id,
	}

	return &out, diags
}

func (r *PortalPageResourceModel) ToSharedPageRequest(ctx context.Context) (*shared.PageRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var additionalProperties interface{}
	if !r.AdditionalProperties.IsUnknown() && !r.AdditionalProperties.IsNull() {
		_ = json.Unmarshal([]byte(r.AdditionalProperties.ValueString()), &additionalProperties)
	}
	blocks := make(map[string]shared.Block)
	for blocksKey, blocksValue := range r.Blocks {
		var additionalProperties1 interface{}
		if !blocksValue.AdditionalProperties.IsUnknown() && !blocksValue.AdditionalProperties.IsNull() {
			_ = json.Unmarshal([]byte(blocksValue.AdditionalProperties.ValueString()), &additionalProperties1)
		}
		id := new(string)
		if !blocksValue.ID.IsUnknown() && !blocksValue.ID.IsNull() {
			*id = blocksValue.ID.ValueString()
		} else {
			id = nil
		}
		var order float64
		order = blocksValue.Order.ValueFloat64()

		parentID := new(string)
		if !blocksValue.ParentID.IsUnknown() && !blocksValue.ParentID.IsNull() {
			*parentID = blocksValue.ParentID.ValueString()
		} else {
			parentID = nil
		}
		var props *shared.BlockProps
		if blocksValue.Props != nil {
			var additionalProperties2 interface{}
			if !blocksValue.Props.AdditionalProperties.IsUnknown() && !blocksValue.Props.AdditionalProperties.IsNull() {
				_ = json.Unmarshal([]byte(blocksValue.Props.AdditionalProperties.ValueString()), &additionalProperties2)
			}
			content := make(map[string]interface{})
			for contentKey, contentValue := range blocksValue.Props.Content {
				var contentInst interface{}
				_ = json.Unmarshal([]byte(contentValue.ValueString()), &contentInst)
				content[contentKey] = contentInst
			}
			design := make(map[string]interface{})
			for designKey, designValue := range blocksValue.Props.Design {
				var designInst interface{}
				_ = json.Unmarshal([]byte(designValue.ValueString()), &designInst)
				design[designKey] = designInst
			}
			visibility := make(map[string]interface{})
			for visibilityKey, visibilityValue := range blocksValue.Props.Visibility {
				var visibilityInst interface{}
				_ = json.Unmarshal([]byte(visibilityValue.ValueString()), &visibilityInst)
				visibility[visibilityKey] = visibilityInst
			}
			props = &shared.BlockProps{
				AdditionalProperties: additionalProperties2,
				Content:              content,
				Design:               design,
				Visibility:           visibility,
			}
		}
		var typeVar string
		typeVar = blocksValue.Type.ValueString()

		blocksInst := shared.Block{
			AdditionalProperties: additionalProperties1,
			ID:                   id,
			Order:                order,
			ParentID:             parentID,
			Props:                props,
			Type:                 typeVar,
		}
		blocks[blocksKey] = blocksInst
	}
	content1 := make(map[string]interface{})
	for contentKey1, contentValue1 := range r.Content {
		var contentInst1 interface{}
		_ = json.Unmarshal([]byte(contentValue1.ValueString()), &contentInst1)
		content1[contentKey1] = contentInst1
	}
	design1 := make(map[string]interface{})
	for designKey1, designValue1 := range r.Design {
		var designInst1 interface{}
		_ = json.Unmarshal([]byte(designValue1.ValueString()), &designInst1)
		design1[designKey1] = designInst1
	}
	isDeleted := new(bool)
	if !r.IsDeleted.IsUnknown() && !r.IsDeleted.IsNull() {
		*isDeleted = r.IsDeleted.ValueBool()
	} else {
		isDeleted = nil
	}
	isEntryRoute := new(bool)
	if !r.IsEntryRoute.IsUnknown() && !r.IsEntryRoute.IsNull() {
		*isEntryRoute = r.IsEntryRoute.ValueBool()
	} else {
		isEntryRoute = nil
	}
	isPublic := new(bool)
	if !r.IsPublic.IsUnknown() && !r.IsPublic.IsNull() {
		*isPublic = r.IsPublic.ValueBool()
	} else {
		isPublic = nil
	}
	isSystem := new(bool)
	if !r.IsSystem.IsUnknown() && !r.IsSystem.IsNull() {
		*isSystem = r.IsSystem.ValueBool()
	} else {
		isSystem = nil
	}
	var order1 float64
	order1 = r.Order.ValueFloat64()

	parentId1 := new(string)
	if !r.ParentID.IsUnknown() && !r.ParentID.IsNull() {
		*parentId1 = r.ParentID.ValueString()
	} else {
		parentId1 = nil
	}
	path := new(string)
	if !r.Path.IsUnknown() && !r.Path.IsNull() {
		*path = r.Path.ValueString()
	} else {
		path = nil
	}
	schema := make([]shared.PageRequestSchema, 0, len(r.Schema))
	for _, schemaItem := range r.Schema {
		schema = append(schema, shared.PageRequestSchema(schemaItem.ValueString()))
	}
	var slug string
	slug = r.Slug.ValueString()

	visibility1 := make(map[string]interface{})
	for visibilityKey1, visibilityValue1 := range r.Visibility {
		var visibilityInst1 interface{}
		_ = json.Unmarshal([]byte(visibilityValue1.ValueString()), &visibilityInst1)
		visibility1[visibilityKey1] = visibilityInst1
	}
	out := shared.PageRequest{
		AdditionalProperties: additionalProperties,
		Blocks:               blocks,
		Content:              content1,
		Design:               design1,
		IsDeleted:            isDeleted,
		IsEntryRoute:         isEntryRoute,
		IsPublic:             isPublic,
		IsSystem:             isSystem,
		Order:                order1,
		ParentID:             parentId1,
		Path:                 path,
		Schema:               schema,
		Slug:                 slug,
		Visibility:           visibility1,
	}

	return &out, diags
}
