// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/provider/typeconvert"
	tfTypes "github.com/epilot-dev/terraform-provider-epilot-portal/internal/provider/types"
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/operations"
	"github.com/epilot-dev/terraform-provider-epilot-portal/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *PortalPageDataSourceModel) RefreshFromSharedPage(ctx context.Context, resp *shared.Page) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		if resp.AdditionalProperties == nil {
			r.AdditionalProperties = jsontypes.NewNormalizedNull()
		} else {
			additionalPropertiesResult, _ := json.Marshal(resp.AdditionalProperties)
			r.AdditionalProperties = jsontypes.NewNormalizedValue(string(additionalPropertiesResult))
		}
		if len(resp.Blocks) > 0 {
			r.Blocks = make(map[string]tfTypes.BlockRequest, len(resp.Blocks))
			for blockRequestKey, blockRequestValue := range resp.Blocks {
				var blockRequestResult tfTypes.BlockRequest
				if blockRequestValue.AdditionalProperties == nil {
					blockRequestResult.AdditionalProperties = jsontypes.NewNormalizedNull()
				} else {
					additionalPropertiesResult1, _ := json.Marshal(blockRequestValue.AdditionalProperties)
					blockRequestResult.AdditionalProperties = jsontypes.NewNormalizedValue(string(additionalPropertiesResult1))
				}
				blockRequestResult.Order = types.Float64Value(blockRequestValue.Order)
				blockRequestResult.ParentID = types.StringPointerValue(blockRequestValue.ParentID)
				if blockRequestValue.Props == nil {
					blockRequestResult.Props = nil
				} else {
					blockRequestResult.Props = &tfTypes.BlockProps{}
					if blockRequestValue.Props.AdditionalProperties == nil {
						blockRequestResult.Props.AdditionalProperties = jsontypes.NewNormalizedNull()
					} else {
						additionalPropertiesResult2, _ := json.Marshal(blockRequestValue.Props.AdditionalProperties)
						blockRequestResult.Props.AdditionalProperties = jsontypes.NewNormalizedValue(string(additionalPropertiesResult2))
					}
					if blockRequestValue.Props.Content == nil {
						blockRequestResult.Props.Content = nil
					} else {
						blockRequestResult.Props.Content = &tfTypes.Content{}
					}
					if blockRequestValue.Props.Design == nil {
						blockRequestResult.Props.Design = nil
					} else {
						blockRequestResult.Props.Design = &tfTypes.Content{}
					}
					if blockRequestValue.Props.Visibility == nil {
						blockRequestResult.Props.Visibility = nil
					} else {
						blockRequestResult.Props.Visibility = &tfTypes.Content{}
					}
				}
				blockRequestResult.Type = types.StringValue(blockRequestValue.Type)

				r.Blocks[blockRequestKey] = blockRequestResult
			}
		}
		if len(resp.Content) > 0 {
			r.Content = make(map[string]jsontypes.Normalized, len(resp.Content))
			for key, value := range resp.Content {
				result, _ := json.Marshal(value)
				r.Content[key] = jsontypes.NewNormalizedValue(string(result))
			}
		}
		if len(resp.Design) > 0 {
			r.Design = make(map[string]jsontypes.Normalized, len(resp.Design))
			for key1, value1 := range resp.Design {
				result1, _ := json.Marshal(value1)
				r.Design[key1] = jsontypes.NewNormalizedValue(string(result1))
			}
		}
		r.ID = types.StringPointerValue(resp.ID)
		r.IsDeleted = types.BoolPointerValue(resp.IsDeleted)
		r.IsEntryRoute = types.BoolPointerValue(resp.IsEntryRoute)
		r.IsPublic = types.BoolPointerValue(resp.IsPublic)
		r.IsSystem = types.BoolPointerValue(resp.IsSystem)
		r.LastModifiedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.LastModifiedAt))
		r.Order = types.Float64Value(resp.Order)
		r.ParentID = types.StringPointerValue(resp.ParentID)
		r.Path = types.StringPointerValue(resp.Path)
		r.Schema = make([]types.String, 0, len(resp.Schema))
		for _, v := range resp.Schema {
			r.Schema = append(r.Schema, types.StringValue(string(v)))
		}
		r.Slug = types.StringValue(resp.Slug)
		if len(resp.Visibility) > 0 {
			r.Visibility = make(map[string]jsontypes.Normalized, len(resp.Visibility))
			for key2, value2 := range resp.Visibility {
				result2, _ := json.Marshal(value2)
				r.Visibility[key2] = jsontypes.NewNormalizedValue(string(result2))
			}
		}
	}

	return diags
}

func (r *PortalPageDataSourceModel) ToOperationsGetPortalPageRequest(ctx context.Context) (*operations.GetPortalPageRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	out := operations.GetPortalPageRequest{
		ID: id,
	}

	return &out, diags
}
