// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type AllowedFileExtensions struct {
	Archive      []types.String `tfsdk:"archive"`
	AudioVideo   []types.String `tfsdk:"audio_video"`
	Cad          []types.String `tfsdk:"cad"`
	Calendar     []types.String `tfsdk:"calendar"`
	Document     []types.String `tfsdk:"document"`
	Email        []types.String `tfsdk:"email"`
	Image        []types.String `tfsdk:"image"`
	Other        []types.String `tfsdk:"other"`
	Presentation []types.String `tfsdk:"presentation"`
	Spreadsheet  []types.String `tfsdk:"spreadsheet"`
}
