// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type Block struct {
	AdditionalProperties jsontypes.Normalized `tfsdk:"additional_properties"`
	ID                   types.String         `tfsdk:"id"`
	Order                types.Float64        `tfsdk:"order"`
	ParentID             types.String         `tfsdk:"parent_id"`
	Props                *BlockProps          `tfsdk:"props"`
	Type                 types.String         `tfsdk:"type"`
}
