// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type BlockProps struct {
	AdditionalProperties types.String `tfsdk:"additional_properties"`
	Content              *Content     `tfsdk:"content"`
	Design               *Content     `tfsdk:"design"`
	Visibility           *Content     `tfsdk:"visibility"`
}
