// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
)

type BlockProps struct {
	AdditionalProperties jsontypes.Normalized            `tfsdk:"additional_properties"`
	Content              map[string]jsontypes.Normalized `tfsdk:"content"`
	Design               map[string]jsontypes.Normalized `tfsdk:"design"`
	Visibility           map[string]jsontypes.Normalized `tfsdk:"visibility"`
}
