// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type EmailTemplates struct {
	AdvancedAuth                 types.String `tfsdk:"advanced_auth"`
	AdvancedMFA                  types.String `tfsdk:"advanced_mfa"`
	ConfirmAccount               types.String `tfsdk:"confirm_account"`
	ConfirmEmailUpdate           types.String `tfsdk:"confirm_email_update"`
	ForgotPassword               types.String `tfsdk:"forgot_password"`
	Invitation                   types.String `tfsdk:"invitation"`
	JourneyLoginOTP              types.String `tfsdk:"journey_login_otp"`
	JourneySignInOneTimePassword types.String `tfsdk:"journey_sign_in_one_time_password"`
	JourneySignUp                types.String `tfsdk:"journey_sign_up"`
	OnDocUpload                  types.String `tfsdk:"on_doc_upload"`
	OnMapAPendingUser            types.String `tfsdk:"on_map_a_pending_user"`
	OnNewQuote                   types.String `tfsdk:"on_new_quote"`
	OnWorkflowStepAssigned       types.String `tfsdk:"on_workflow_step_assigned"`
	VerifyCodeToSetPassword      types.String `tfsdk:"verify_code_to_set_password"`
}
