// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type EntityActions struct {
	ActionLabel *UpsertPortalConfigActionLabel `tfsdk:"action_label"`
	JourneyID   types.String                   `tfsdk:"journey_id"`
	Slug        types.String                   `tfsdk:"slug"`
}
