// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type OIDCProviderConfig struct {
	ClientID     types.String          `tfsdk:"client_id"`
	ClientSecret types.String          `tfsdk:"client_secret"`
	Metadata     *OIDCProviderMetadata `tfsdk:"metadata"`
	OidcIssuer   types.String          `tfsdk:"oidc_issuer"`
	Prompt       types.String          `tfsdk:"prompt"`
	RedirectURI  types.String          `tfsdk:"redirect_uri"`
	Scope        types.String          `tfsdk:"scope"`
}
