// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type Page struct {
	AdditionalProperties types.String            `tfsdk:"additional_properties"`
	Blocks               map[string]Block        `tfsdk:"blocks"`
	Content              map[string]types.String `tfsdk:"content"`
	Design               map[string]types.String `tfsdk:"design"`
	ID                   types.String            `tfsdk:"id"`
	IsDeleted            types.Bool              `tfsdk:"is_deleted"`
	IsEntryRoute         types.Bool              `tfsdk:"is_entry_route"`
	IsPublic             types.Bool              `tfsdk:"is_public"`
	IsSystem             types.Bool              `tfsdk:"is_system"`
	LastModifiedAt       types.String            `tfsdk:"last_modified_at"`
	Order                types.Number            `tfsdk:"order"`
	ParentID             types.String            `tfsdk:"parent_id"`
	Path                 types.String            `tfsdk:"path"`
	Schema               []types.String          `tfsdk:"schema"`
	Slug                 types.String            `tfsdk:"slug"`
	Visibility           map[string]types.String `tfsdk:"visibility"`
}
