// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type UpsertPortalConfigV3Type struct {
	Attributes []types.String `tfsdk:"attributes"`
	IsEnabled  types.Bool     `tfsdk:"is_enabled"`
}
