// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type UpsertPortalConfigV3AuthSettings struct {
	EntryPoint            types.String                     `tfsdk:"entry_point"`
	PasswordlessLogin     *UpsertPortalConfigV3AdvancedMfa `tfsdk:"passwordless_login"`
	PreferredSsoProviders []types.String                   `tfsdk:"preferred_sso_providers"`
}
