// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type UpsertPortalConfigV3CognitoDetails struct {
	CognitoUserPoolArn      types.String                        `tfsdk:"cognito_user_pool_arn"`
	CognitoUserPoolClientID types.String                        `tfsdk:"cognito_user_pool_client_id"`
	CognitoUserPoolID       types.String                        `tfsdk:"cognito_user_pool_id"`
	PasswordPolicy          *UpsertPortalConfigV3PasswordPolicy `tfsdk:"password_policy"`
}
