// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type UpsertPortalConfigV3FeatureSettings struct {
	Billing       types.Bool `tfsdk:"billing"`
	ChangeDueDate types.Bool `tfsdk:"change_due_date"`
	NewDesign     types.Bool `tfsdk:"new_design"`
	StartPage     types.Bool `tfsdk:"start_page"`
}
