// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type UpsertPortalConfigV3Images struct {
	OrderLeftTeaser  types.String `tfsdk:"order_left_teaser"`
	OrderRightTeaser types.String `tfsdk:"order_right_teaser"`
	WelcomeBanner    types.String `tfsdk:"welcome_banner"`
}
